from collections.abc import Callable

from _typeshed import Incomplete

import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.cat.properties
import sage_categories.cat.slices
import sage_categories.kernel.roles
import sage_categories.sets.finite
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.cones import LimitConesCategory as LimitConesCategory
from sage_categories.cat.declarations import Sets as Sets
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.leaf_categories import (
    FaithfulStructureCategory as FaithfulStructureCategory,
)
from sage_categories.cat.morphisms import Mor as Mor
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Axiom as Axiom
from sage_categories.cat.predicates import Predicate as Predicate
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import conjunction as conjunction
from sage_categories.cat.predicates import disjunction as disjunction
from sage_categories.cat.predicates import implication as implication
from sage_categories.cat.predicates import register_handler as register_handler
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.cat.shapes import Discrete as Discrete
from sage_categories.cat.shapes import ThinCategory as ThinCategory
from sage_categories.cat.slices import SliceProperty as SliceProperty
from sage_categories.sets.cardinals import Cardinal as Cardinal
from sage_categories.sets.cardinals import CardinalCategory as CardinalCategory
from sage_categories.sets.finite import SetsCategory as SetsCategory

__all__ = [
    "BinaryRelations",
    "BinaryRelationsCategory",
    "FiniteGradedPosetsCategory",
    "FinitePosets",
    "FinitePosetsCategory",
    "FinitePosetsWithBottomCategory",
    "FinitePosetsWithTopCategory",
    "FiniteRankedPosetsCategory",
    "FiniteTotallyOrderedSets",
    "FiniteTotallyOrderedSetsCategory",
    "Posets",
    "PosetsCategory",
    "Thin",
    "TotallyOrderedSets",
    "order_preserving",
]
type OrderRule = Callable[[CategoryOfCategories.ElementType, CategoryOfCategories.ElementType], Proposition]
order_preserving: Incomplete

class _StaticRoles_BinaryRelationsCategory:
    class ObjectType(sage_categories.sets.finite._StaticRoles_SetsCategory.ObjectType):
        def __init__(self, relation: CategoryOfCategories.ElementType) -> None: ...
        def relation(self) -> CategoryOfCategories.ElementType: ...
        def carrier(self) -> CategoryOfCategories.ElementType: ...
        def related(self, first: CategoryOfCategories.ElementType, second: CategoryOfCategories.ElementType) -> Proposition: ...

    class ElementType(sage_categories.sets.finite._StaticRoles_SetsCategory.ElementType): ...

    class MorphismType(sage_categories.sets.finite._StaticRoles_SetsCategory.MorphismType):
        def __init__(self, underlying: MorphismCategory.ObjectType) -> None: ...
        def underlying_map(self) -> MorphismCategory.ObjectType: ...
        def domain(self) -> BinaryRelationsCategory.ObjectType: ...
        def codomain(self) -> BinaryRelationsCategory.ObjectType: ...

class BinaryRelationsCategory(
    _StaticRoles_BinaryRelationsCategory,
    FaithfulStructureCategory[
        _StaticRoles_BinaryRelationsCategory.ObjectType, _StaticRoles_BinaryRelationsCategory.ElementType, _StaticRoles_BinaryRelationsCategory.MorphismType
    ],
):
    PartialOrder: Incomplete

    def __call__(self, relation: CategoryOfCategories.ElementType) -> BinaryRelationsCategory.ObjectType: ...
    def from_predicate(self, carrier: CategoryOfCategories.ElementType, rule: OrderRule) -> BinaryRelationsCategory.ObjectType: ...
    def lift_order(self, diagram: Functor, presentation: LimitConesCategory.ObjectType) -> BinaryRelationsCategory.ObjectType: ...
    def transport(self, relation_object: BinaryRelationsCategory.ObjectType, bijection: MorphismCategory.ObjectType) -> BinaryRelationsCategory.MorphismType: ...
    def to_sets(self) -> Functor: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def construct_morphism(
        self, source: BinaryRelationsCategory.ObjectType, target: BinaryRelationsCategory.ObjectType, underlying: MorphismCategory.ObjectType
    ) -> BinaryRelationsCategory.MorphismType: ...

class _StaticRoles_PosetsCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(_StaticRoles_BinaryRelationsCategory.ObjectType): ...

    class ElementType(_StaticRoles_BinaryRelationsCategory.ElementType):
        def __le__(self, other: CategoryOfCategories.ElementType) -> Proposition: ...

    class MorphismType(_StaticRoles_BinaryRelationsCategory.MorphismType):
        def domain(self) -> PosetsCategory.ObjectType: ...
        def codomain(self) -> PosetsCategory.ObjectType: ...

class PosetsCategory(
    _StaticRoles_PosetsCategory,
    PropertySubcategory[..., ..., _StaticRoles_PosetsCategory.ObjectType, _StaticRoles_PosetsCategory.ElementType, _StaticRoles_PosetsCategory.MorphismType],
):
    Total: Incomplete

    def to_sets(self) -> Functor: ...
    Finite: Incomplete

    def subobjects_type(self) -> type[PosetSubobjects]: ...

class _StaticRoles_PosetSubobjects(sage_categories.cat.slices._StaticRoles_SliceProperty):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> PosetSubobjects.ObjectType: ...
        def codomain(self) -> PosetSubobjects.ObjectType: ...

class PosetSubobjects(
    _StaticRoles_PosetSubobjects, SliceProperty[_StaticRoles_PosetSubobjects.ObjectType, _StaticRoles_PosetSubobjects.ElementType, _StaticRoles_PosetSubobjects.MorphismType]
):
    def from_predicate(self, predicate: Callable[[PosetsCategory.ElementType], Proposition]) -> PosetSubobjects.ObjectType: ...

class _StaticRoles_FinitePosetsCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def covers(self, lower: FinitePosetsCategory.ElementType, upper: FinitePosetsCategory.ElementType) -> Proposition: ...
        def height(self) -> CardinalCategory.ObjectType: ...
        def width(self) -> CardinalCategory.ObjectType: ...
        def linear_extension(self) -> FiniteTotallyOrderedSetsCategory.ObjectType: ...
        def lower_covers(self, member: FinitePosetsCategory.ElementType) -> PosetSubobjects.ObjectType: ...
        def upper_covers(self, member: FinitePosetsCategory.ElementType) -> PosetSubobjects.ObjectType: ...
        def open_interval(self, lower: FinitePosetsCategory.ElementType, upper: FinitePosetsCategory.ElementType) -> PosetSubobjects.ObjectType: ...
        def closed_interval(self, lower: FinitePosetsCategory.ElementType, upper: FinitePosetsCategory.ElementType) -> PosetSubobjects.ObjectType: ...
        def principal_order_ideal(self, member: FinitePosetsCategory.ElementType) -> PosetSubobjects.ObjectType: ...
        def principal_order_filter(self, member: FinitePosetsCategory.ElementType) -> PosetSubobjects.ObjectType: ...
        def common_lower_covers(self, members: PosetSubobjects.ObjectType) -> PosetSubobjects.ObjectType: ...
        def common_upper_covers(self, members: PosetSubobjects.ObjectType) -> PosetSubobjects.ObjectType: ...
        def order_ideal(self, members: PosetSubobjects.ObjectType) -> PosetSubobjects.ObjectType: ...
        def order_filter(self, members: PosetSubobjects.ObjectType) -> PosetSubobjects.ObjectType: ...
        def minimal_elements(self) -> PosetSubobjects.ObjectType: ...
        def maximal_elements(self) -> PosetSubobjects.ObjectType: ...
        def is_chain_of_poset(self, members: PosetSubobjects.ObjectType) -> Proposition: ...
        def is_antichain_of_poset(self, members: PosetSubobjects.ObjectType) -> Proposition: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> FinitePosetsCategory.ObjectType: ...
        def codomain(self) -> FinitePosetsCategory.ObjectType: ...

class FinitePosetsCategory(
    _StaticRoles_FinitePosetsCategory,
    Category[..., ..., _StaticRoles_FinitePosetsCategory.ObjectType, _StaticRoles_FinitePosetsCategory.ElementType, _StaticRoles_FinitePosetsCategory.MorphismType],
):
    Ranked: Incomplete
    Graded: Incomplete
    WithBottom: Incomplete
    WithTop: Incomplete

    def structure_functors(self) -> tuple[Functor, ...]: ...

class _StaticRoles_FiniteRankedPosetsCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def rank_of_element(self, member: FinitePosetsCategory.ElementType) -> CardinalCategory.ObjectType: ...
        def rank(self) -> CardinalCategory.ObjectType: ...
        def level_sets(self) -> Functor: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> FiniteRankedPosetsCategory.ObjectType: ...
        def codomain(self) -> FiniteRankedPosetsCategory.ObjectType: ...

class FiniteRankedPosetsCategory(
    _StaticRoles_FiniteRankedPosetsCategory,
    PropertySubcategory[
        ..., ..., _StaticRoles_FiniteRankedPosetsCategory.ObjectType, _StaticRoles_FiniteRankedPosetsCategory.ElementType, _StaticRoles_FiniteRankedPosetsCategory.MorphismType
    ],
): ...

class _StaticRoles_FiniteGradedPosetsCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(_StaticRoles_FiniteRankedPosetsCategory.ObjectType): ...
    class ElementType(_StaticRoles_FiniteRankedPosetsCategory.ElementType): ...

    class MorphismType(_StaticRoles_FiniteRankedPosetsCategory.MorphismType):
        def domain(self) -> FiniteGradedPosetsCategory.ObjectType: ...
        def codomain(self) -> FiniteGradedPosetsCategory.ObjectType: ...

class FiniteGradedPosetsCategory(
    _StaticRoles_FiniteGradedPosetsCategory,
    PropertySubcategory[
        ..., ..., _StaticRoles_FiniteGradedPosetsCategory.ObjectType, _StaticRoles_FiniteGradedPosetsCategory.ElementType, _StaticRoles_FiniteGradedPosetsCategory.MorphismType
    ],
): ...

class _StaticRoles_FinitePosetsWithBottomCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def bottom(self) -> FinitePosetsCategory.ElementType: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> FinitePosetsWithBottomCategory.ObjectType: ...
        def codomain(self) -> FinitePosetsWithBottomCategory.ObjectType: ...

class FinitePosetsWithBottomCategory(
    _StaticRoles_FinitePosetsWithBottomCategory,
    PropertySubcategory[
        ...,
        ...,
        _StaticRoles_FinitePosetsWithBottomCategory.ObjectType,
        _StaticRoles_FinitePosetsWithBottomCategory.ElementType,
        _StaticRoles_FinitePosetsWithBottomCategory.MorphismType,
    ],
): ...

class _StaticRoles_FinitePosetsWithTopCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def top(self) -> FinitePosetsCategory.ElementType: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> FinitePosetsWithTopCategory.ObjectType: ...
        def codomain(self) -> FinitePosetsWithTopCategory.ObjectType: ...

class FinitePosetsWithTopCategory(
    _StaticRoles_FinitePosetsWithTopCategory,
    PropertySubcategory[
        ...,
        ...,
        _StaticRoles_FinitePosetsWithTopCategory.ObjectType,
        _StaticRoles_FinitePosetsWithTopCategory.ElementType,
        _StaticRoles_FinitePosetsWithTopCategory.MorphismType,
    ],
): ...

class _StaticRoles_FiniteTotallyOrderedSetsCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> FiniteTotallyOrderedSetsCategory.ObjectType: ...
        def codomain(self) -> FiniteTotallyOrderedSetsCategory.ObjectType: ...

class FiniteTotallyOrderedSetsCategory(
    _StaticRoles_FiniteTotallyOrderedSetsCategory,
    Category[
        ...,
        ...,
        _StaticRoles_FiniteTotallyOrderedSetsCategory.ObjectType,
        _StaticRoles_FiniteTotallyOrderedSetsCategory.ElementType,
        _StaticRoles_FiniteTotallyOrderedSetsCategory.MorphismType,
    ],
):
    def structure_functors(self) -> tuple[Functor, ...]: ...

def BinaryRelations() -> BinaryRelationsCategory: ...
def Posets() -> Category: ...
def TotallyOrderedSets() -> Category: ...
def FinitePosets() -> FinitePosetsCategory: ...
def FiniteTotallyOrderedSets() -> FiniteTotallyOrderedSetsCategory: ...

Thin: Functor
