from sage_categories.cat.category import Category as Category
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.native import has_native_category as has_native_category, has_native_functor as has_native_functor, has_native_transformation as has_native_transformation, retain_native_category as retain_native_category, retain_native_functor as retain_native_functor, retain_native_transformation as retain_native_transformation
from sage_categories.kernel.refinement import is_placed as is_placed
from sage_categories.kernel.sage_runtime import MonoDict as MonoDict

def ensure_native_category(owner: Category) -> object:
    ...

def ensure_native_functor(functor: MorphismCategory.ObjectType) -> object:
    ...

def functor_object_image(functor: MorphismCategory.ObjectType, value: object) -> object:
    ...

def functor_morphism_image(functor: MorphismCategory.ObjectType, value: object) -> object:
    ...

def ensure_native_transformation(value: MorphismCategory.ObjectType) -> object:
    ...

def transformation_component(value: MorphismCategory.ObjectType, member_object: object) -> object:
    ...

def identity_transformation(value: MorphismCategory.ObjectType) -> None:
    ...

def compose_transformations(value: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> None:
    ...

def whisker_left(value: MorphismCategory.ObjectType, functor: MorphismCategory.ObjectType, transformation: MorphismCategory.ObjectType) -> None:
    ...

def whisker_right(value: MorphismCategory.ObjectType, transformation: MorphismCategory.ObjectType, functor: MorphismCategory.ObjectType) -> None:
    ...

def horizontal_composite(value: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> None:
    ...

def presented_coproduct(categories: tuple[object, ...]) -> object:
    ...

def presented_coproduct_data(value: object) -> tuple[tuple[str, ...], tuple[tuple[str, str, str], ...], tuple[tuple[tuple[str, ...], tuple[str, ...]], ...]]:
    ...

def presented_coproduct_object_image(value: object, factor: int, object_index: int) -> str:
    ...

def presented_coproduct_path_image(value: object, categories: tuple[object, ...], factor: int, word: tuple[str, ...], source: object) -> tuple[str, ...]:
    ...

def presented_functor(source: object, target: Category, object_images: tuple[object, ...], generator_images: tuple[object, ...]) -> object:
    ...

def presented_functor_morphism_image(functor: object, source: object, morphism: object) -> object:
    ...
