import sage_categories_homotopy as homotopy

from sage_categories.cat.category import Category
from sage_categories.cat.morphisms import MorphismCategory

def native_signature(owner: Category) -> homotopy.Signature: ...
def native_object(owner: Category, value: object) -> homotopy.Cell: ...
def native_cell(owner: Category, value: MorphismCategory.ObjectType) -> homotopy.Cell: ...
def typecheck(owner: Category, value: MorphismCategory.ObjectType) -> None: ...
