from collections.abc import Callable

from discopy.monoidal import Box, Diagram, Ty

class NonstrictMonoidalModel:
    def __init__(self, *, unit: object, tensor_object: Callable[[object, object], object], tensor_morphism: Callable[[object, object], object], identity: Callable[[object], object], compose: Callable[[object, object], object], inverse: Callable[[object], object], comparison: Callable[[tuple[object, ...], tuple[object, ...]], object]) -> None: ...
    def wire(self, value: object) -> Ty: ...
    def box(self, name: str, domain: tuple[object, ...], codomain: tuple[object, ...], value: object) -> Box: ...
    def evaluate(self, diagram: Diagram) -> object: ...


def evaluate_path(arrows: tuple[object, ...], *, domain: object, codomain: object, identity: Callable[[object], object], compose: Callable[[object, object], object]) -> object: ...
