from collections.abc import Callable

from discopy.monoidal import Box, Diagram, Ty

type DiagramBox = Box

class NonstrictMonoidalModel[Object, Arrow]:
    def __init__(self, *, unit: Object, tensor_object: Callable[[Object, Object], Object], tensor_morphism: Callable[[Arrow, Arrow], Arrow], identity: Callable[[Object], Arrow], compose: Callable[[Arrow, Arrow], Arrow], inverse: Callable[[Arrow], Arrow], comparison: Callable[[tuple[Object, ...], tuple[Object, ...]], Arrow]) -> None: ...
    def wire(self, value: Object) -> Ty: ...
    def box(self, name: str, domain: tuple[Object, ...], codomain: tuple[Object, ...], value: Arrow) -> DiagramBox: ...
    def evaluate(self, diagram: Diagram) -> Arrow: ...


def evaluate_path(arrows: tuple[object, ...], *, domain: object, codomain: object, identity: Callable[[object], object], compose: Callable[[object, object], object]) -> object: ...
