from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory
from typing import Literal
__all__ = ['cartesian_associator', 'cartesian_left_unitor', 'cartesian_right_unitor', 'is_monomorphism', 'is_epimorphism', 'equal_morphisms', 'inverse_morphism', 'image_factorization', 'factor_through_monomorphism', 'hom_morphisms', 'finite_limit', 'finite_colimit', 'primitive_limit', 'primitive_colimit']

def cartesian_associator(first: object, second: object, third: object, source: object, target: object, *, forward: bool) -> MorphismCategory.ObjectType:
    ...

def cartesian_left_unitor(value: object, source: object, target: object, *, forward: bool) -> MorphismCategory.ObjectType:
    ...

def cartesian_right_unitor(value: object, source: object, target: object, *, forward: bool) -> MorphismCategory.ObjectType:
    ...

def is_monomorphism(value: MorphismCategory.ObjectType) -> bool:
    ...

def is_epimorphism(value: MorphismCategory.ObjectType) -> bool:
    ...

def equal_morphisms(first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> bool:
    ...

def inverse_morphism(value: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType:
    ...

def image_factorization(value: MorphismCategory.ObjectType) -> tuple[MorphismCategory.ObjectType, MorphismCategory.ObjectType]:
    ...

def factor_through_monomorphism(mono: MorphismCategory.ObjectType, value: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType | Literal[False]:
    ...

def hom_morphisms(source: object, target: object) -> tuple[MorphismCategory.ObjectType, ...]:
    ...

def finite_limit(diagram: Functor) -> object:
    ...

def finite_colimit(diagram: Functor) -> object:
    ...

def primitive_limit(diagram: Functor) -> object:
    ...

def primitive_colimit(diagram: Functor) -> object:
    ...
