from typing import Literal

from sage_categories.cat.morphisms import MorphismCategory

def is_monomorphism(value: MorphismCategory.ObjectType) -> bool: ...
def is_epimorphism(value: MorphismCategory.ObjectType) -> bool: ...
def equal_morphisms(first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> bool: ...
def inverse_morphism(value: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
def image_factorization(value: MorphismCategory.ObjectType) -> tuple[MorphismCategory.ObjectType, MorphismCategory.ObjectType]: ...
def factor_through_monomorphism(mono: MorphismCategory.ObjectType, value: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType | Literal[False]: ...
def hom_morphisms(source: object, target: object) -> tuple[MorphismCategory.ObjectType, ...]: ...

def primitive_limit(diagram: object) -> object: ...
def primitive_colimit(diagram: object) -> object: ...

def finite_limit(diagram: object) -> object: ...
def finite_colimit(diagram: object) -> object: ...


def cartesian_associator(first: object, second: object, third: object, source: object, target: object, *, forward: bool) -> MorphismCategory.ObjectType: ...
def cartesian_left_unitor(value: object, source: object, target: object, *, forward: bool) -> MorphismCategory.ObjectType: ...
def cartesian_right_unitor(value: object, source: object, target: object, *, forward: bool) -> MorphismCategory.ObjectType: ...
