from typing import Any

def reduce_word(category: Any, source: Any, target: Any, word: tuple[str, ...]) -> tuple[str, ...]: ...
def finite_morphisms(category: Any) -> tuple[tuple[int, int, tuple[str, ...]], ...] | None: ...
