from sage.libs.gap.element import GapElement

from sage_categories.engines.gap import FINITE_CATEGORY_PACKAGES as FINITE_CATEGORY_PACKAGES
from sage_categories.engines.gap import load_packages as load_packages

__all__ = ["finite_morphisms", "native_category", "native_morphism", "native_object", "owned_morphism", "owned_object", "reduce_word", "terminal_object"]

def reduce_word(category: object, source: object, target: object, word: tuple[str, ...]) -> tuple[str, ...]: ...
def finite_morphisms(category: object) -> tuple[tuple[int, int, tuple[str, ...]], ...] | None: ...
def native_category(category: object) -> GapElement: ...
def native_object(category: object, value: object) -> GapElement: ...
def native_morphism(category: object, value: object) -> GapElement: ...
def owned_object(category: object, native: GapElement) -> object: ...
def terminal_object(category: object) -> object | None: ...
def owned_morphism(category: object, native: GapElement) -> object: ...
