def prime_field(characteristic: int) -> object: ...
def polynomial_ring(base: object, names: tuple[str, ...]) -> tuple[object, tuple[object, ...]]: ...
def quotient(ring: object, relations: tuple[object, ...]) -> tuple[object, object]: ...
def localization_at_element(ring: object, element: object) -> tuple[object, object]: ...
def prime_ideal(ring: object, generators: tuple[object, ...]) -> object: ...
def prime_ideal_preimage(mapping: object, prime: object) -> object: ...
def localization_at_prime(ring: object, prime: object) -> tuple[object, object]: ...
def stalk_map(mapping: object, source_localized: object, target_localized: object, target_localization: object) -> object: ...
def hom(source: object, target: object, images: tuple[object, ...]) -> object: ...
def localization_hom(localized: object, target: object, base_map: object) -> object: ...
def map_apply(mapping: object, element: object) -> object: ...
def domain(mapping: object) -> object: ...
def codomain(mapping: object) -> object: ...
def generators(ring: object) -> tuple[object, ...]: ...
def ring_contains(ring: object, element: object) -> bool: ...
def ring_zero(ring: object) -> object: ...
def ring_one(ring: object) -> object: ...
def ring_add(first: object, second: object) -> object: ...
def ring_multiply(first: object, second: object) -> object: ...
def ring_negate(element: object) -> object: ...
def ring_coerce(ring: object, value: object) -> object: ...
def ring_inverse(element: object) -> object: ...
def same_native(first: object, second: object) -> bool: ...
def affine_spec(ring: object) -> object: ...
def affine_morphism(source_scheme: object, target_scheme: object, pullback_map: object) -> object: ...
def affine_morphism_direct(source_scheme: object, target_scheme: object, pullback_map: object) -> object: ...
def affine_pullback(mapping: object) -> object: ...
def affine_domain(mapping: object) -> object: ...
def affine_codomain(mapping: object) -> object: ...
def covered_scheme(scheme: object) -> object: ...
def simple_gluing(left_chart: object, right_chart: object, left_to_right: object, right_to_left: object) -> object: ...
def glued_covered_scheme(left_chart: object, right_chart: object, gluing: object) -> object: ...
def covered_patches(scheme: object) -> tuple[object, ...]: ...
def covered_chart_inclusion(source: object, chart: object, glued: object) -> object: ...
def gluing_mediator(glued: object, target: object, left_chart: object, right_chart: object, left_map: object, right_map: object) -> object: ...
def covered_domain(mapping: object) -> object: ...
def covered_codomain(mapping: object) -> object: ...
def structure_sheaf(scheme: object) -> object: ...
def sheaf_value(sheaf: object, open_subset: object) -> object: ...
def sheaf_restriction(sheaf: object, larger: object, smaller: object) -> object: ...
def principal_open(scheme: object, element: object) -> object: ...
def principal_open_ambient(open_subset: object) -> object: ...
def principal_open_inclusion(open_subset: object) -> object: ...
