module SageCategoriesOscarBridge

using Oscar

export prime_field, polynomial_ring_with_generators, quotient_ring,
       localization_at_element, localization_at_prime, ring_hom, localization_hom,
       prime_ideal_from_generators, prime_ideal_preimage, prime_ideal_extension,
       ideal_generators, ideal_contains, stalk_map,
       map_apply, map_domain, map_codomain, ring_identity, ring_compose, ring_map_equal, ring_generators,
       ring_contains, ring_equal, ring_zero, ring_one, ring_add, ring_multiply, ring_negate,
       ring_coerce, ring_inverse, same_native,
       affine_spec, affine_coordinate_ring, affine_morphism_from_pullback, affine_pullback,
       affine_domain, affine_codomain, covered_scheme_of,
       structure_sheaf, sheaf_value, sheaf_restriction,
       affine_open_union, affine_open_section_ring, affine_open_restriction,
       affine_open_contains, affine_open_intersection,
       principal_open_subset, principal_open_ambient,
       principal_open_inclusion, affine_morphism_direct,
       simple_gluing, glued_covered_scheme, covered_patches,
       general_gluing, finite_covered_scheme, gluing_cocycle,
       covered_open_contains, covered_open_restriction,
       covered_chart_open_preimage, affine_open_complement_equations,
       covered_open_family_compatible, covered_component_intersection,
       finite_gluing_mediator,
       covered_chart_inclusion, gluing_mediator,
       covered_chart_map, covered_domain, covered_codomain,
       covered_identity, covered_compose, covered_equal

"""The prime field ``GF(p)`` used by the affine-ring consumer."""
prime_field(p::Integer) = GF(p)

"""A multivariate polynomial ring over ``base`` with the supplied generator names."""
polynomial_ring_with_generators(base, names) = polynomial_ring(base, Symbol.(collect(names)))

"""The quotient by the ideal generated by ``relations``, together with its projection."""
quotient_ring(ring, relations) = quo(ring, ideal(ring, collect(relations)))

"""The principal localization ``R_f`` and its canonical map ``R -> R_f``."""
localization_at_element(ring, element) = localization(ring, powers_of_element(element))

"""A checked prime ideal generated by ``generators``."""
function prime_ideal_from_generators(ring, generators)
    result = ideal(ring, collect(generators))
    is_prime(result) || error("ideal is not prime")
    result
end

prime_ideal_preimage(map, prime) = preimage(map, prime)

function prime_ideal_extension(map, prime)
    target = codomain(map)
    images = [map(generator) for generator in gens(prime)]
    result = isempty(images) ? ideal(target, zero(target)) : ideal(target, images)
    is_prime(result) || error("extended ideal is not prime")
    result
end

ideal_generators(ideal_value) = collect(gens(ideal_value))
ideal_contains(ideal_value, element) = element in ideal_value

"""The local ring ``R_p`` and its canonical localization map."""
localization_at_prime(ring, prime) = localization(ring, complement_of_prime_ideal(prime))

"""The induced local map ``A_p -> B_q`` for ``p = phi^-1(q)``."""
function stalk_map(phi, source_localized, target_localized, target_localization)
    restricted = compose(phi, target_localization)
    hom(source_localized, target_localized, restricted)
end

"""The ring homomorphism determined by the images of the source generators."""
ring_hom(source, target, images) = hom(source, target, collect(images))

"""Extend a ring map across a principal localization when the selected element becomes a unit."""
localization_hom(localized, target, base_map) = hom(localized, target, base_map)

map_apply(map, element) = map(element)
map_domain(map) = domain(map)
map_codomain(map) = codomain(map)
ring_identity(ring) = identity_map(ring)
ring_compose(second, first) = compose(first, second)
ring_map_equal(first, second) = first == second
ring_generators(ring) = gens(ring)
ring_contains(ring, element) = try
    parent(element) === ring
catch
    false
end
ring_equal(first, second) = first == second
ring_zero(ring) = zero(ring)
ring_one(ring) = one(ring)
ring_add(first, second) = first + second
ring_multiply(first, second) = first * second
ring_negate(element) = -element
ring_coerce(ring, value) = ring(value)
ring_inverse(element) = inv(element)
same_native(first, second) = first === second

"""The affine scheme ``Spec(R)`` for a supported OSCAR coordinate ring."""
affine_spec(ring) = spec(ring)
affine_coordinate_ring(scheme) = OO(scheme)

"""The affine morphism ``Spec(B) -> Spec(A)`` defined by a ring map ``A -> B``."""
function affine_morphism_from_pullback(source_scheme, target_scheme, ring_map)
    images = [ring_map(generator) for generator in gens(OO(target_scheme))]
    morphism(source_scheme, target_scheme, images)
end

affine_pullback(map) = pullback(map)
affine_domain(map) = domain(map)
affine_codomain(map) = codomain(map)
covered_scheme_of(scheme) = covered_scheme(scheme)
structure_sheaf(scheme) = StructureSheafOfRings(scheme)
sheaf_value(sheaf, open_subset) = sheaf(open_subset)
sheaf_restriction(sheaf, larger, smaller) = restriction_map(sheaf, larger, smaller)

function affine_open_union(patches)
    opens = [AffineSchemeOpenSubscheme(patch) for patch in collect(patches)]
    isempty(opens) && error("an affine-open union needs at least one principal patch")
    result = reduce(union, opens)
    result.patches = collect(patches)
    result
end

affine_open_section_ring(open_subset) = OO(open_subset)
affine_open_restriction(larger, smaller) = restriction_map(larger, smaller)

function affine_open_contains(smaller, larger)
    try
        restriction_map(larger, smaller)
        true
    catch
        false
    end
end

affine_open_intersection(first, second) = intersect(first, second)

principal_open_subset(scheme, element) = PrincipalOpenSubset(scheme, element)
principal_open_ambient(open_subset) = ambient_scheme(open_subset)
principal_open_inclusion(open_subset) = inclusion_morphism(open_subset)

"""An affine-scheme morphism from its exact pullback ring map."""
affine_morphism_direct(source_scheme, target_scheme, pullback_map) = morphism(source_scheme, target_scheme, pullback_map)

"""A checked gluing of two affine charts along inverse principal-open maps."""
simple_gluing(left_chart, right_chart, left_to_right, right_to_left) =
    SimpleGluing(left_chart, right_chart, left_to_right, right_to_left)

function affine_open_piecewise_morphism(source_open, target_open, source_patches, target_patches, pullbacks)
    source_patches = collect(source_patches)
    target_patches = collect(target_patches)
    pullbacks = collect(pullbacks)
    length(source_patches) == length(target_patches) == length(pullbacks) ||
        error("piecewise open morphism data have inconsistent lengths")
    target_ambient = ambient_scheme(target_open)
    target_generators = gens(OO(target_ambient))
    maps = AbsAffineSchemeMor[]
    for (source_patch, target_patch, pullback_map) in zip(source_patches, target_patches, pullbacks)
        target_restriction = pullback(inclusion_morphism(target_patch))
        images = [pullback_map(target_restriction(generator)) for generator in target_generators]
        push!(maps, morphism(source_patch, target_ambient, images, check=false))
    end
    AffineSchemeOpenSubschemeMor(source_open, target_open, maps, check=true)
end

function general_gluing(
    left_chart,
    right_chart,
    left_open,
    right_open,
    left_patches,
    right_patches,
    left_to_right_pullbacks,
    right_to_left_pullbacks,
)
    left_to_right = affine_open_piecewise_morphism(
        left_open,
        right_open,
        left_patches,
        right_patches,
        left_to_right_pullbacks,
    )
    right_to_left = affine_open_piecewise_morphism(
        right_open,
        left_open,
        right_patches,
        left_patches,
        right_to_left_pullbacks,
    )
    Gluing(left_chart, right_chart, left_to_right, right_to_left, check=true)
end

function gluing_cocycle(first, second, direct)
    try
        composed = compose(first, second)
        if patches(composed)[1] !== patches(direct)[1]
            direct = inverse(direct)
        end
        composed_map = gluing_morphisms(composed)[1]
        direct_map = gluing_morphisms(direct)[1]
        restricted = restrict(
            direct_map,
            domain(composed_map),
            codomain(composed_map),
            check=true,
        )
        composed_map == restricted
    catch
        false
    end
end

function finite_covered_scheme(patches, gluings)
    covering = Covering(collect(patches))
    for gluing in collect(gluings)
        add_gluing!(covering, gluing)
    end
    CoveredScheme(covering)
end

function covered_open_contains(scheme, smaller, larger)
    try
        restriction_map(StructureSheafOfRings(scheme), larger, smaller)
        true
    catch
        false
    end
end

covered_open_restriction(scheme, larger, smaller) =
    restriction_map(StructureSheafOfRings(scheme), larger, smaller)

function covered_chart_open_preimage(scheme, source_chart, target_open)
    target_chart = ambient_scheme(target_open)
    target_as_open = target_open isa AffineSchemeOpenSubscheme ? target_open : AffineSchemeOpenSubscheme(target_open)
    if source_chart === target_chart
        return target_as_open
    end
    gluing = default_covering(scheme)[source_chart, target_chart]
    forward = gluing_morphisms(gluing)[1]
    target_part = intersect(codomain(forward), target_as_open)
    preimage(forward, target_part)
end

affine_open_complement_equations(open_subset) = collect(complement_equations(open_subset))

function affine_open_equal(first, second)
    affine_open_contains(first, second) && affine_open_contains(second, first)
end


function covered_open_family_compatible(scheme, opens)
    opens = collect(opens)
    cover = default_covering(scheme)
    for left_index in eachindex(opens)
        for right_index in eachindex(opens)
            left_index < right_index || continue
            left_open = opens[left_index]
            right_open = opens[right_index]
            left_chart = ambient_scheme(left_open)
            right_chart = ambient_scheme(right_open)
            gluing = cover[left_chart, right_chart]
            forward = gluing_morphisms(gluing)[1]
            left_part = intersect(left_open, domain(forward))
            right_part = intersect(right_open, codomain(forward))
            transported = preimage(forward, right_part)
            affine_open_equal(left_part, transported) || return false
        end
    end
    true
end


function covered_component_intersection(scheme, source_open, target_open)
    source_chart = ambient_scheme(source_open)
    target_chart = ambient_scheme(target_open)
    source_chart === target_chart && return intersect(source_open, target_open)
    gluing = default_covering(scheme)[source_chart, target_chart]
    forward = gluing_morphisms(gluing)[1]
    target_part = intersect(target_open, codomain(forward))
    intersect(source_open, preimage(forward, target_part))
end


function finite_gluing_mediator(source, target, chart_maps)
    source_cover = default_covering(source)
    target_cover = default_covering(target)
    source_patches = patches(source_cover)
    chart_maps = collect(chart_maps)
    length(source_patches) == length(chart_maps) ||
        error("one chart map is required for each source affine chart")
    local_maps = IdDict{AbsAffineScheme, AbsAffineSchemeMor}(
        patch => chart_map[patch]
        for (patch, chart_map) in zip(source_patches, chart_maps)
    )
    covering_map = CoveringMorphism(source_cover, target_cover, local_maps; check=false)
    CoveredSchemeMorphism(source, target, covering_map; check=false)
end


"""The covered scheme obtained from two charts and their gluing."""
function glued_covered_scheme(left_chart, right_chart, gluing)
    covering = Covering([left_chart, right_chart])
    add_gluing!(covering, gluing)
    CoveredScheme(covering)
end

covered_patches(scheme) = patches(scheme)

"""The canonical map from one affine chart into a covered scheme containing it."""
function covered_chart_inclusion(source, chart, glued)
    source_cover = default_covering(source)
    target_cover = default_covering(glued)
    maps = IdDict{AbsAffineScheme, AbsAffineSchemeMor}(chart => identity_map(chart))
    covering_map = CoveringMorphism(source_cover, target_cover, maps)
    CoveredSchemeMorphism(source, glued, covering_map)
end

"""A covered-scheme map from one affine source chart into a chosen target chart."""
function covered_chart_map(source, source_chart, target, affine_map)
    source_cover = default_covering(source)
    target_cover = default_covering(target)
    maps = IdDict{AbsAffineScheme, AbsAffineSchemeMor}(source_chart => affine_map)
    covering_map = CoveringMorphism(source_cover, target_cover, maps)
    CoveredSchemeMorphism(source, target, covering_map)
end

"""The unique covered-scheme map induced by compatible maps on two glued charts."""
function gluing_mediator(glued, target, left_chart, right_chart, left_map, right_map)
    source_cover = default_covering(glued)
    target_cover = default_covering(target)
    maps = IdDict{AbsAffineScheme, AbsAffineSchemeMor}(
        left_chart => left_map[left_chart],
        right_chart => right_map[right_chart],
    )
    covering_map = CoveringMorphism(source_cover, target_cover, maps)
    CoveredSchemeMorphism(glued, target, covering_map)
end

covered_domain(map) = domain(map)
covered_codomain(map) = codomain(map)
covered_identity(scheme) = identity_map(scheme)
covered_compose(second, first) = compose(first, second)
covered_equal(first, second) = first == second

end
