module SageCategoriesOscarBridge

using Oscar

export prime_field, polynomial_ring_with_generators, quotient_ring,
       localization_at_element, localization_at_prime, ring_hom, localization_hom,
       prime_ideal_from_generators, prime_ideal_preimage, stalk_map,
       map_apply, map_domain, map_codomain, ring_generators,
       ring_contains, ring_zero, ring_one, ring_add, ring_multiply, ring_negate,
       ring_coerce, ring_inverse, same_native,
       affine_spec, affine_morphism_from_pullback, affine_pullback,
       affine_domain, affine_codomain, covered_scheme_of,
       structure_sheaf, sheaf_value, sheaf_restriction,
       principal_open_subset, principal_open_ambient,
       principal_open_inclusion

"""The prime field ``GF(p)`` used by the affine-ring consumer."""
prime_field(p::Integer) = GF(p)

"""A multivariate polynomial ring over ``base`` with the supplied generator names."""
polynomial_ring_with_generators(base, names) = polynomial_ring(base, Symbol.(collect(names)))

"""The quotient by the ideal generated by ``relations``, together with its projection."""
quotient_ring(ring, relations) = quo(ring, ideal(ring, collect(relations)))

"""The principal localization ``R_f`` and its canonical map ``R -> R_f``."""
localization_at_element(ring, element) = localization(ring, powers_of_element(element))

"""A checked prime ideal generated by ``generators``."""
function prime_ideal_from_generators(ring, generators)
    result = ideal(ring, collect(generators))
    is_prime(result) || error("ideal is not prime")
    result
end

prime_ideal_preimage(map, prime) = preimage(map, prime)

"""The local ring ``R_p`` and its canonical localization map."""
localization_at_prime(ring, prime) = localization(ring, complement_of_prime_ideal(prime))

"""The induced local map ``A_p -> B_q`` for ``p = phi^-1(q)``."""
function stalk_map(phi, source_localized, target_localized, target_localization)
    restricted = compose(phi, target_localization)
    hom(source_localized, target_localized, restricted)
end

"""The ring homomorphism determined by the images of the source generators."""
ring_hom(source, target, images) = hom(source, target, collect(images))

"""Extend a ring map across a principal localization when the selected element becomes a unit."""
localization_hom(localized, target, base_map) = hom(localized, target, base_map)

map_apply(map, element) = map(element)
map_domain(map) = domain(map)
map_codomain(map) = codomain(map)
ring_generators(ring) = gens(ring)
ring_contains(ring, element) = try
    parent(element) === ring
catch
    false
end
ring_zero(ring) = zero(ring)
ring_one(ring) = one(ring)
ring_add(first, second) = first + second
ring_multiply(first, second) = first * second
ring_negate(element) = -element
ring_coerce(ring, value) = ring(value)
ring_inverse(element) = inv(element)
same_native(first, second) = first === second

"""The affine scheme ``Spec(R)`` for a supported OSCAR coordinate ring."""
affine_spec(ring) = spec(ring)

"""The affine morphism ``Spec(B) -> Spec(A)`` defined by a ring map ``A -> B``."""
function affine_morphism_from_pullback(source_scheme, target_scheme, ring_map)
    images = [ring_map(generator) for generator in gens(OO(target_scheme))]
    morphism(source_scheme, target_scheme, images)
end

affine_pullback(map) = pullback(map)
affine_domain(map) = domain(map)
affine_codomain(map) = codomain(map)
covered_scheme_of(scheme) = covered_scheme(scheme)
structure_sheaf(scheme) = OO(scheme)
sheaf_value(sheaf, open_subset) = sheaf(open_subset)
sheaf_restriction(sheaf, larger, smaller) = restriction_map(sheaf, larger, smaller)
principal_open_subset(scheme, element) = PrincipalOpenSubset(scheme, element)
principal_open_ambient(open_subset) = ambient_scheme(open_subset)
principal_open_inclusion(open_subset) = inclusion_morphism(open_subset)

end
