"""Pinned OSCAR operations allocated to commutative rings and affine geometry."""

from __future__ import annotations

from sage_categories.engines.julia_bridge import OscarHandle
from sage_categories.engines.julia_bridge import oscar_bridge as bridge

__all__ = [
    "affine_codomain",
    "affine_coordinate_ring",
    "affine_domain",
    "affine_morphism",
    "affine_morphism_direct",
    "affine_open_contains",
    "affine_open_intersection",
    "affine_open_restriction",
    "affine_open_section_ring",
    "affine_open_union",
    "affine_pullback",
    "affine_spec",
    "codomain",
    "covered_chart_inclusion",
    "covered_chart_map",
    "covered_chart_open_preimage",
    "covered_codomain",
    "covered_component_intersection",
    "covered_compose",
    "covered_domain",
    "covered_equal",
    "covered_identity",
    "covered_open_contains",
    "covered_open_family_compatible",
    "covered_open_restriction",
    "covered_patches",
    "covered_scheme",
    "domain",
    "finite_covered_scheme",
    "finite_gluing_mediator",
    "general_gluing",
    "generators",
    "glued_covered_scheme",
    "gluing_cocycle",
    "gluing_mediator",
    "hom",
    "ideal_contains",
    "ideal_generators",
    "integer_ring",
    "localization_at_element",
    "localization_at_prime",
    "localization_hom",
    "map_apply",
    "polynomial_ring",
    "prime_field",
    "prime_ideal",
    "prime_ideal_extension",
    "prime_ideal_preimage",
    "principal_open",
    "principal_open_ambient",
    "principal_open_inclusion",
    "quotient",
    "ring_add",
    "ring_coerce",
    "ring_compose",
    "ring_contains",
    "ring_equal",
    "ring_identity",
    "ring_inverse",
    "ring_map_equal",
    "ring_multiply",
    "ring_negate",
    "ring_one",
    "ring_zero",
    "same_native",
    "sheaf_restriction",
    "sheaf_value",
    "simple_gluing",
    "stalk_map",
    "structure_sheaf",
    "version",
]


def version() -> str:
    """Return the OSCAR package version loaded by the isolated worker."""
    return bridge().text("version")


def integer_ring() -> OscarHandle:
    """Return OSCAR's integer ring ``ZZ``."""
    return bridge().handle("integer_ring")


def prime_field(characteristic: int) -> OscarHandle:
    """Return OSCAR's prime field ``GF(characteristic)``."""
    return bridge().handle("prime_field", characteristic)


def polynomial_ring(base: OscarHandle, names: tuple[str, ...]) -> tuple[OscarHandle, tuple[OscarHandle, ...]]:
    """Return OSCAR's multivariate polynomial ring and its ordered generators."""
    ring, generators = bridge().handle_and_handles("polynomial_ring_with_generators", base, list(names))
    return ring, tuple(generators)


def quotient(ring: OscarHandle, relations: tuple[OscarHandle, ...]) -> tuple[OscarHandle, OscarHandle]:
    """Return ``ring/(relations)`` and its canonical projection."""
    quotient_ring, projection = bridge().pair("quotient_ring", ring, list(relations))
    return quotient_ring, projection


def localization_at_element(ring: OscarHandle, element: OscarHandle) -> tuple[OscarHandle, OscarHandle]:
    """Return the principal localization ``ring[element^-1]`` and its canonical map."""
    localized, canonical = bridge().pair("localization_at_element", ring, element)
    return localized, canonical


def prime_ideal(ring: OscarHandle, generators: tuple[OscarHandle, ...]) -> OscarHandle:
    """Return the checked OSCAR prime ideal generated by ``generators``."""
    return bridge().handle("prime_ideal_from_generators", ring, list(generators))


def prime_ideal_preimage(mapping: OscarHandle, prime: OscarHandle) -> OscarHandle:
    """Return the inverse-image prime ideal under ``mapping``."""
    return bridge().handle("prime_ideal_preimage", mapping, prime)


def prime_ideal_extension(mapping: OscarHandle, prime: OscarHandle) -> OscarHandle:
    """Return the ideal generated by the image of ``prime``, checked prime."""
    return bridge().handle("prime_ideal_extension", mapping, prime)


def ideal_generators(ideal: OscarHandle) -> tuple[OscarHandle, ...]:
    """Return the native generators retained by an OSCAR ideal."""
    return bridge().handles("ideal_generators", ideal)


def ideal_contains(ideal: OscarHandle, element: OscarHandle) -> bool:
    """Decide membership of one OSCAR ring element in an ideal."""
    return bridge().boolean("ideal_contains", ideal, element)


def localization_at_prime(ring: OscarHandle, prime: OscarHandle) -> tuple[OscarHandle, OscarHandle]:
    """Return the local ring ``ring_prime`` and its canonical map."""
    localized, canonical = bridge().pair("localization_at_prime", ring, prime)
    return localized, canonical


def stalk_map(
    mapping: OscarHandle,
    source_localized: OscarHandle,
    target_localized: OscarHandle,
    target_localization: OscarHandle,
) -> OscarHandle:
    """Return the induced local homomorphism on prime localizations."""
    return bridge().handle("stalk_map", mapping, source_localized, target_localized, target_localization)


def hom(source: OscarHandle, target: OscarHandle, images: tuple[OscarHandle, ...]) -> OscarHandle:
    """Return the OSCAR ring homomorphism defined by generator images."""
    return bridge().handle("ring_hom", source, target, list(images))


def localization_hom(localized: OscarHandle, target: OscarHandle, base_map: OscarHandle) -> OscarHandle:
    """Extend ``base_map`` uniquely across a principal localization."""
    return bridge().handle("localization_hom", localized, target, base_map)


def map_apply(mapping: OscarHandle, element: OscarHandle) -> OscarHandle:
    return bridge().handle("map_apply", mapping, element)


def domain(mapping: OscarHandle) -> OscarHandle:
    return bridge().handle("map_domain", mapping)


def codomain(mapping: OscarHandle) -> OscarHandle:
    return bridge().handle("map_codomain", mapping)


def ring_identity(ring: OscarHandle) -> OscarHandle:
    """Return OSCAR's identity map of a ring."""
    return bridge().handle("ring_identity", ring)


def ring_compose(second: OscarHandle, first: OscarHandle) -> OscarHandle:
    """Return ``second * first`` through OSCAR ring-map composition."""
    return bridge().handle("ring_compose", second, first)


def ring_map_equal(first: OscarHandle, second: OscarHandle) -> bool:
    """Decide equality of two OSCAR ring maps."""
    return bridge().boolean("ring_map_equal", first, second)


def generators(ring: OscarHandle) -> tuple[OscarHandle, ...]:
    return bridge().handles("ring_generators", ring)


def ring_contains(ring: OscarHandle, element: OscarHandle | int) -> bool:
    return bridge().boolean("ring_contains", ring, element)


def ring_equal(first: OscarHandle, second: OscarHandle) -> bool:
    """Decide equality of two OSCAR ring elements."""
    return bridge().boolean("ring_equal", first, second)


def ring_zero(ring: OscarHandle) -> OscarHandle:
    return bridge().handle("ring_zero", ring)


def ring_one(ring: OscarHandle) -> OscarHandle:
    return bridge().handle("ring_one", ring)


def ring_add(first: OscarHandle, second: OscarHandle) -> OscarHandle:
    return bridge().handle("ring_add", first, second)


def ring_multiply(first: OscarHandle, second: OscarHandle) -> OscarHandle:
    return bridge().handle("ring_multiply", first, second)


def ring_negate(element: OscarHandle) -> OscarHandle:
    return bridge().handle("ring_negate", element)


def ring_coerce(ring: OscarHandle, value: OscarHandle | int) -> OscarHandle:
    return bridge().handle("ring_coerce", ring, value)


def ring_inverse(element: OscarHandle) -> OscarHandle:
    return bridge().handle("ring_inverse", element)


def same_native(first: OscarHandle, second: OscarHandle) -> bool:
    return bridge().boolean("same_native", first, second)


def affine_spec(ring: OscarHandle) -> OscarHandle:
    """Return OSCAR's affine scheme ``Spec(ring)``."""
    return bridge().handle("affine_spec", ring)


def affine_coordinate_ring(scheme: OscarHandle) -> OscarHandle:
    """Return OSCAR's coordinate ring ``OO(scheme)`` for an affine scheme."""
    return bridge().handle("affine_coordinate_ring", scheme)


def affine_morphism(source_scheme: OscarHandle, target_scheme: OscarHandle, pullback_map: OscarHandle) -> OscarHandle:
    """Return ``source_scheme -> target_scheme`` with the supplied contravariant ring map."""
    return bridge().handle("affine_morphism_from_pullback", source_scheme, target_scheme, pullback_map)


def affine_morphism_direct(source_scheme: OscarHandle, target_scheme: OscarHandle, pullback_map: OscarHandle) -> OscarHandle:
    """Return an OSCAR affine map using an already constructed pullback map."""
    return bridge().handle("affine_morphism_direct", source_scheme, target_scheme, pullback_map)


def affine_pullback(mapping: OscarHandle) -> OscarHandle:
    """Return the coordinate-ring pullback of an affine scheme morphism."""
    return bridge().handle("affine_pullback", mapping)


def affine_open_union(patches: tuple[OscarHandle, ...]) -> OscarHandle:
    """Return the union of finitely many principal opens in one affine ambient."""
    return bridge().handle("affine_open_union", list(patches))


def affine_open_section_ring(open_subset: OscarHandle) -> OscarHandle:
    """Return OSCAR's ring of regular functions on an affine open subscheme."""
    return bridge().handle("affine_open_section_ring", open_subset)


def affine_open_restriction(larger: OscarHandle, smaller: OscarHandle) -> OscarHandle:
    """Return the structure-sheaf restriction ``OO(larger) -> OO(smaller)``."""
    return bridge().handle("affine_open_restriction", larger, smaller)


def affine_open_contains(smaller: OscarHandle, larger: OscarHandle) -> bool:
    """Decide containment of two represented affine opens."""
    return bridge().boolean("affine_open_contains", smaller, larger)


def affine_open_intersection(first: OscarHandle, second: OscarHandle) -> OscarHandle:
    """Return the represented intersection of two affine opens."""
    return bridge().handle("affine_open_intersection", first, second)


def affine_domain(mapping: OscarHandle) -> OscarHandle:
    return bridge().handle("affine_domain", mapping)


def affine_codomain(mapping: OscarHandle) -> OscarHandle:
    return bridge().handle("affine_codomain", mapping)


def covered_scheme(scheme: OscarHandle) -> OscarHandle:
    return bridge().handle("covered_scheme_of", scheme)


def simple_gluing(
    left_chart: OscarHandle,
    right_chart: OscarHandle,
    left_to_right: OscarHandle,
    right_to_left: OscarHandle,
) -> OscarHandle:
    """Return OSCAR's checked simple gluing of two affine charts."""
    return bridge().handle("simple_gluing", left_chart, right_chart, left_to_right, right_to_left)


def general_gluing(
    left_chart: OscarHandle,
    right_chart: OscarHandle,
    left_open: OscarHandle,
    right_open: OscarHandle,
    left_patches: tuple[OscarHandle, ...],
    right_patches: tuple[OscarHandle, ...],
    left_to_right_pullbacks: tuple[OscarHandle, ...],
    right_to_left_pullbacks: tuple[OscarHandle, ...],
) -> OscarHandle:
    """Return a checked gluing along finite affine covers of general open subsets."""
    return bridge().handle(
        "general_gluing",
        left_chart,
        right_chart,
        left_open,
        right_open,
        list(left_patches),
        list(right_patches),
        list(left_to_right_pullbacks),
        list(right_to_left_pullbacks),
    )


def gluing_cocycle(first: OscarHandle, second: OscarHandle, direct: OscarHandle) -> bool:
    """Check the direct transition against the composite on the triple-overlap domain."""
    return bridge().boolean("gluing_cocycle", first, second, direct)


def finite_covered_scheme(
    patches: tuple[OscarHandle, ...],
    gluings: tuple[OscarHandle, ...],
) -> OscarHandle:
    """Return a covered scheme with all supplied pairwise gluings retained."""
    return bridge().handle("finite_covered_scheme", list(patches), list(gluings))


def covered_open_contains(scheme: OscarHandle, smaller: OscarHandle, larger: OscarHandle) -> bool:
    """Decide represented-open containment through the covered structure sheaf."""
    return bridge().boolean("covered_open_contains", scheme, smaller, larger)


def covered_open_restriction(scheme: OscarHandle, larger: OscarHandle, smaller: OscarHandle) -> OscarHandle:
    """Return the covered structure-sheaf restriction between represented affine opens."""
    return bridge().handle("covered_open_restriction", scheme, larger, smaller)


def covered_chart_open_preimage(
    scheme: OscarHandle,
    source_chart: OscarHandle,
    target_open: OscarHandle,
) -> OscarHandle:
    """Pull one represented chart-affine open back into another chart."""
    return bridge().handle("covered_chart_open_preimage", scheme, source_chart, target_open)


def affine_open_complement_equations(open_subset: OscarHandle) -> tuple[OscarHandle, ...]:
    """Return root-coordinate equations whose principal opens cover ``open_subset``."""
    return bridge().handles("affine_open_complement_equations", open_subset)


def covered_open_family_compatible(
    scheme: OscarHandle,
    opens: tuple[OscarHandle, ...],
) -> bool:
    """Check that chart-local opens agree across every retained gluing."""
    return bridge().boolean("covered_open_family_compatible", scheme, list(opens))


def covered_component_intersection(
    scheme: OscarHandle,
    source_open: OscarHandle,
    target_open: OscarHandle,
) -> OscarHandle:
    """Return the source-chart intersection with the transported target open."""
    return bridge().handle("covered_component_intersection", scheme, source_open, target_open)


def finite_gluing_mediator(
    source: OscarHandle,
    target: OscarHandle,
    chart_maps: tuple[OscarHandle, ...],
) -> OscarHandle:
    """Glue compatible chart maps to the checked unique covered-scheme morphism."""
    return bridge().handle("finite_gluing_mediator", source, target, list(chart_maps))


def glued_covered_scheme(left_chart: OscarHandle, right_chart: OscarHandle, gluing: OscarHandle) -> OscarHandle:
    """Return the covered scheme represented by the two-chart gluing."""
    return bridge().handle("glued_covered_scheme", left_chart, right_chart, gluing)


def covered_patches(scheme: OscarHandle) -> tuple[OscarHandle, ...]:
    return bridge().handles("covered_patches", scheme)


def covered_chart_inclusion(source: OscarHandle, chart: OscarHandle, glued: OscarHandle) -> OscarHandle:
    """Return the native open chart map into a covered scheme."""
    return bridge().handle("covered_chart_inclusion", source, chart, glued)


def covered_chart_map(source: OscarHandle, source_chart: OscarHandle, target: OscarHandle, affine_map: OscarHandle) -> OscarHandle:
    """Return a covered map from one affine source into a chosen target chart."""
    return bridge().handle("covered_chart_map", source, source_chart, target, affine_map)


def gluing_mediator(
    glued: OscarHandle,
    target: OscarHandle,
    left_chart: OscarHandle,
    right_chart: OscarHandle,
    left_map: OscarHandle,
    right_map: OscarHandle,
) -> OscarHandle:
    """Return the checked map induced by compatible maps on the two charts."""
    return bridge().handle("gluing_mediator", glued, target, left_chart, right_chart, left_map, right_map)


def covered_domain(mapping: OscarHandle) -> OscarHandle:
    return bridge().handle("covered_domain", mapping)


def covered_codomain(mapping: OscarHandle) -> OscarHandle:
    return bridge().handle("covered_codomain", mapping)


def covered_identity(scheme: OscarHandle) -> OscarHandle:
    """Return OSCAR's identity morphism of a covered scheme."""
    return bridge().handle("covered_identity", scheme)


def covered_compose(second: OscarHandle, first: OscarHandle) -> OscarHandle:
    """Return ``second * first`` through OSCAR's covered-scheme composition."""
    return bridge().handle("covered_compose", second, first)


def covered_equal(first: OscarHandle, second: OscarHandle) -> bool:
    """Decide equality of two covered-scheme morphisms on compatible coverings."""
    return bridge().boolean("covered_equal", first, second)


def structure_sheaf(scheme: OscarHandle) -> OscarHandle:
    return bridge().handle("structure_sheaf", scheme)


def sheaf_value(sheaf: OscarHandle, open_subset: OscarHandle) -> OscarHandle:
    return bridge().handle("sheaf_value", sheaf, open_subset)


def sheaf_restriction(sheaf: OscarHandle, larger: OscarHandle, smaller: OscarHandle) -> OscarHandle:
    return bridge().handle("sheaf_restriction", sheaf, larger, smaller)


def principal_open(scheme: OscarHandle, element: OscarHandle) -> OscarHandle:
    """Return OSCAR's genuine ``PrincipalOpenSubset(scheme, element)``."""
    return bridge().handle("principal_open_subset", scheme, element)


def principal_open_ambient(open_subset: OscarHandle) -> OscarHandle:
    return bridge().handle("principal_open_ambient", open_subset)


def principal_open_inclusion(open_subset: OscarHandle) -> OscarHandle:
    return bridge().handle("principal_open_inclusion", open_subset)
