from sage_categories.engines.julia_bridge import OscarHandle

__all__ = ['prime_field', 'polynomial_ring', 'quotient', 'localization_at_element', 'prime_ideal', 'prime_ideal_preimage', 'localization_at_prime', 'stalk_map', 'hom', 'localization_hom', 'map_apply', 'domain', 'codomain', 'generators', 'ring_contains', 'ring_zero', 'ring_one', 'ring_add', 'ring_multiply', 'ring_negate', 'ring_coerce', 'ring_inverse', 'same_native', 'affine_spec', 'affine_morphism', 'affine_morphism_direct', 'affine_pullback', 'affine_domain', 'affine_codomain', 'covered_scheme', 'simple_gluing', 'glued_covered_scheme', 'covered_patches', 'covered_chart_inclusion', 'covered_chart_map', 'gluing_mediator', 'covered_domain', 'covered_codomain', 'structure_sheaf', 'sheaf_value', 'sheaf_restriction', 'principal_open', 'principal_open_ambient', 'principal_open_inclusion']

def prime_field(characteristic: int) -> OscarHandle: ...
def polynomial_ring(base: OscarHandle, names: tuple[str, ...]) -> tuple[OscarHandle, tuple[OscarHandle, ...]]: ...
def quotient(ring: OscarHandle, relations: tuple[OscarHandle, ...]) -> tuple[OscarHandle, OscarHandle]: ...
def localization_at_element(ring: OscarHandle, element: OscarHandle) -> tuple[OscarHandle, OscarHandle]: ...
def prime_ideal(ring: OscarHandle, generators: tuple[OscarHandle, ...]) -> OscarHandle: ...
def prime_ideal_preimage(mapping: OscarHandle, prime: OscarHandle) -> OscarHandle: ...
def localization_at_prime(ring: OscarHandle, prime: OscarHandle) -> tuple[OscarHandle, OscarHandle]: ...
def stalk_map(mapping: OscarHandle, source_localized: OscarHandle, target_localized: OscarHandle, target_localization: OscarHandle) -> OscarHandle: ...
def hom(source: OscarHandle, target: OscarHandle, images: tuple[OscarHandle, ...]) -> OscarHandle: ...
def localization_hom(localized: OscarHandle, target: OscarHandle, base_map: OscarHandle) -> OscarHandle: ...
def map_apply(mapping: OscarHandle, element: OscarHandle) -> OscarHandle: ...
def domain(mapping: OscarHandle) -> OscarHandle: ...
def codomain(mapping: OscarHandle) -> OscarHandle: ...
def generators(ring: OscarHandle) -> tuple[OscarHandle, ...]: ...
def ring_contains(ring: OscarHandle, element: OscarHandle | int) -> bool: ...
def ring_zero(ring: OscarHandle) -> OscarHandle: ...
def ring_one(ring: OscarHandle) -> OscarHandle: ...
def ring_add(first: OscarHandle, second: OscarHandle) -> OscarHandle: ...
def ring_multiply(first: OscarHandle, second: OscarHandle) -> OscarHandle: ...
def ring_negate(element: OscarHandle) -> OscarHandle: ...
def ring_coerce(ring: OscarHandle, value: OscarHandle | int) -> OscarHandle: ...
def ring_inverse(element: OscarHandle) -> OscarHandle: ...
def same_native(first: OscarHandle, second: OscarHandle) -> bool: ...
def affine_spec(ring: OscarHandle) -> OscarHandle: ...
def affine_morphism(source_scheme: OscarHandle, target_scheme: OscarHandle, pullback_map: OscarHandle) -> OscarHandle: ...
def affine_morphism_direct(source_scheme: OscarHandle, target_scheme: OscarHandle, pullback_map: OscarHandle) -> OscarHandle: ...
def affine_pullback(mapping: OscarHandle) -> OscarHandle: ...
def affine_domain(mapping: OscarHandle) -> OscarHandle: ...
def affine_codomain(mapping: OscarHandle) -> OscarHandle: ...
def covered_scheme(scheme: OscarHandle) -> OscarHandle: ...
def simple_gluing(left_chart: OscarHandle, right_chart: OscarHandle, left_to_right: OscarHandle, right_to_left: OscarHandle) -> OscarHandle: ...
def glued_covered_scheme(left_chart: OscarHandle, right_chart: OscarHandle, gluing: OscarHandle) -> OscarHandle: ...
def covered_patches(scheme: OscarHandle) -> tuple[OscarHandle, ...]: ...
def covered_chart_inclusion(source: OscarHandle, chart: OscarHandle, glued: OscarHandle) -> OscarHandle: ...
def covered_chart_map(source: OscarHandle, source_chart: OscarHandle, target: OscarHandle, affine_map: OscarHandle) -> OscarHandle: ...
def gluing_mediator(glued: OscarHandle, target: OscarHandle, left_chart: OscarHandle, right_chart: OscarHandle, left_map: OscarHandle, right_map: OscarHandle) -> OscarHandle: ...
def covered_domain(mapping: OscarHandle) -> OscarHandle: ...
def covered_codomain(mapping: OscarHandle) -> OscarHandle: ...
def structure_sheaf(scheme: OscarHandle) -> OscarHandle: ...
def sheaf_value(sheaf: OscarHandle, open_subset: OscarHandle) -> OscarHandle: ...
def sheaf_restriction(sheaf: OscarHandle, larger: OscarHandle, smaller: OscarHandle) -> OscarHandle: ...
def principal_open(scheme: OscarHandle, element: OscarHandle) -> OscarHandle: ...
def principal_open_ambient(open_subset: OscarHandle) -> OscarHandle: ...
def principal_open_inclusion(open_subset: OscarHandle) -> OscarHandle: ...
