from sage_categories.cat.category import CategoryDeclaration as CategoryDeclaration
from sage_categories.sets.cardinals import CardinalObjectDeclaration as CardinalObjectDeclaration
from _typeshed import Incomplete
from collections.abc import Hashable
from dataclasses import dataclass
from sage_categories.cat.category import Category as Category
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, ask as ask
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, role_of as role_of
from sage_categories.sets.cardinals import CardinalObject as CardinalObject

def bind_cardinals() -> None: ...
type Key = tuple[Hashable, ...]

@dataclass(frozen=True, eq=False, slots=True)
class OrdinalObjectData:
    key: Key
    terms: tuple[OrdinalObject, ...]

class OrdinalObjectDeclaration(ObjectOfCategory):
    def __init__(self, data: OrdinalObjectData) -> None: ...
    def is_initial(self) -> AppliedPredicate: ...
    def initial_index(self) -> OrdinalObject: ...
    def cardinality(self) -> CardinalObject: ...
    def __add__(self, other: OrdinalObject | int) -> OrdinalObject: ...
    def __radd__(self, other: int) -> OrdinalObject: ...
    def __mul__(self, other: OrdinalObject | int) -> OrdinalObject: ...
    def __rmul__(self, other: int) -> OrdinalObject: ...
    def ordinal_sum(self, other: OrdinalObject | int) -> OrdinalObject: ...
    def ordinal_product(self, other: OrdinalObject | int) -> OrdinalObject: ...
    def ordinal_power(self, exponent: OrdinalObject | int) -> OrdinalObject: ...
    def __le__(self, other: OrdinalObject | int) -> AppliedPredicate: ...
    def __lt__(self, other: OrdinalObject | int) -> AppliedPredicate: ...
    def __ge__(self, other: OrdinalObject | int) -> AppliedPredicate: ...
    def __gt__(self, other: OrdinalObject | int) -> AppliedPredicate: ...
    def __hash__(self) -> int: ...

initial: Predicate
at_most: Predicate
less_than: Predicate

class OrdinalsCategory(CategoryDeclaration[[], []]):
    @property
    def ObjectType(self) -> type[OrdinalObjectDeclaration]: ...
    @property
    def ElementType(self) -> type[OrdinalsCategory.DeclaredElementType]: ...
    @property
    def MorphismType(self) -> type[OrdinalsCategory.DeclaredMorphismType]: ...
    DeclaredObjectType = OrdinalObjectDeclaration
    class DeclaredElementType(ElementOfObject):
        ...
    class DeclaredMorphismType(MorphismOfCategory):
        ...
    def __init__(self) -> None: ...
    def __call__(self, value: OrdinalObject | int) -> OrdinalObject: ...
    def omega(self, index: OrdinalObject | int) -> OrdinalObject: ...
    def zero(self) -> OrdinalObject: ...
    def one(self) -> OrdinalObject: ...
    def natural_sum(self, *summands: OrdinalObject) -> OrdinalObject: ...
    def natural_product(self, *factors: OrdinalObject) -> OrdinalObject: ...
    def ordinal_sum(self, left: OrdinalObject, right: OrdinalObject) -> OrdinalObject: ...
    def ordinal_product(self, left: OrdinalObject, right: OrdinalObject) -> OrdinalObject: ...
    def ordinal_power(self, base: OrdinalObject, exponent: OrdinalObject) -> OrdinalObject: ...

OrdinalObject = OrdinalObjectDeclaration

def Ordinals() -> OrdinalsCategory: ...
def ordinal(value: OrdinalObject | int) -> OrdinalObject: ...
def omega(index: OrdinalObject | int) -> OrdinalObject: ...

omega0: OrdinalObject
