# Native surface used by the isolated worker. Source: fadoss/maude-bindings
# 060c4f202861e94ffaf2b9204bf02edb6874acb8, swig/{maude,module,misc,term,vector}.i.
from collections.abc import Iterator, Sequence
from typing import Self

def init(loadPrelude: bool = True, randomSeed: int = 0, advise: bool = True, handleInterrupts: bool = False) -> bool: ...
def input(text: str) -> bool: ...
def getModule(name: str) -> Module | None: ...

class Module:
    def getSymbols(self) -> SymbolVector: ...

class ModuleItem: ...

class Symbol(ModuleItem):
    def makeTerm(self, args: Sequence[Term]) -> Term: ...

class SymbolVector:
    def __iter__(self) -> Iterator[Symbol]: ...

class Term:
    def symbol(self) -> Symbol: ...
    def arguments(self, normalize: bool = True) -> ArgumentIterator: ...
    def reduce(self) -> int: ...
    def equal(self, other: Term) -> bool: ...

class ArgumentIterator:
    def __iter__(self) -> Self: ...
    def __next__(self) -> Term: ...
