from typing import Literal

class Cell:
    def dimension(self) -> int: ...
    def same_as(self, other: Cell) -> bool: ...
    def source(self) -> Cell: ...
    def target(self) -> Cell: ...
    def identity(self) -> Cell: ...
    def inverse(self) -> Cell: ...
    def boundary(self, side: Literal["source", "target"], depth: int) -> Cell: ...
    def embeddings(self, cell: Cell) -> list[list[int]]: ...
    def attach(self, cell: Cell, side: Literal["source", "target"], embedding: list[int]) -> Cell: ...

class Signature:
    def __init__(self) -> None: ...
    def add_object(self) -> Cell: ...
    def add_generator(
        self,
        source: Cell,
        target: Cell,
        invertibility: Literal["directed", "invertible", "dualisable"] = "directed",
        dualisable: int | None = None,
    ) -> Cell: ...
    def strengthen_invertibility(
        self,
        cell: Cell,
        invertibility: Literal["directed", "invertible", "dualisable"] = "invertible",
        dualisable: int | None = None,
    ) -> None: ...
    def typecheck(self, cell: Cell, recursive: bool) -> None: ...
