from sage_categories.algebra.commutative_rings import PrimeIdeal
from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.cat.native import (
    NativeMorphismRealization,
    NativeObjectRealization,
)
from sage_categories.geometry.sheaves import RingPresheaf

class AffineSchemeConstruction:
    coordinate_ring: CategoryOfCategories.ElementType

class AffineSpectrumPoint:
    scheme: AffineSchemesCategory.ObjectType
    prime: PrimeIdeal
    local_ring: CategoryOfCategories.ElementType
    localization: MorphismCategory.ObjectType

class AffineOpenCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def native(self) -> object: ...
        def section_ring(self) -> CategoryOfCategories.ElementType: ...
        def restriction_to(self, ancestor: AffineOpenCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    class ElementType(CategoryOfCategories.ElementType): ...
    class MorphismType(MorphismCategory.ObjectType): ...
    def __init__(self, scheme: AffineSchemesCategory.ObjectType) -> None: ...
    def scheme(self) -> AffineSchemesCategory.ObjectType: ...
    def root(self) -> ObjectType: ...
    def principal_open(self, parent: ObjectType, element: CategoryOfCategories.ElementType) -> ObjectType: ...

AffineOpen = AffineOpenCategory.ObjectType

class AffineSchemesCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def coordinate_ring(self) -> CategoryOfCategories.ElementType: ...
    class ElementType(CategoryOfCategories.ElementType): ...
    class MorphismType(MorphismCategory.ObjectType):
        def pullback(self) -> MorphismCategory.ObjectType: ...
    def from_native(self, coordinate_ring: CategoryOfCategories.ElementType, native: object) -> ObjectType: ...
    def from_native_morphism(self, source: ObjectType, target: ObjectType, pullback: MorphismCategory.ObjectType, native: object) -> MorphismType: ...
    def spectrum_point(self, scheme: ObjectType, generators: tuple[CategoryOfCategories.ElementType, ...]) -> AffineSpectrumPoint: ...
    def map_spectrum_point(self, mapping: MorphismType, point: AffineSpectrumPoint) -> tuple[AffineSpectrumPoint, MorphismCategory.ObjectType]: ...

def AffineSchemes() -> AffineSchemesCategory: ...
def native_affine_scheme(value: CategoryOfCategories.ElementType) -> NativeObjectRealization[object, AffineSchemeConstruction]: ...
def native_affine_morphism(value: MorphismCategory.ObjectType) -> NativeMorphismRealization[object]: ...
def affine_structure_sheaf(scheme: AffineSchemesCategory.ObjectType) -> tuple[AffineOpenCategory, RingPresheaf]: ...
Spec: Functor
