from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.cat.native import NativeMorphismRealization, NativeObjectRealization

class AffineSchemeConstruction:
    coordinate_ring: CategoryOfCategories.ElementType

class AffineSchemesCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def coordinate_ring(self) -> CategoryOfCategories.ElementType: ...
    class ElementType(CategoryOfCategories.ElementType): ...
    class MorphismType(MorphismCategory.ObjectType):
        def pullback(self) -> MorphismCategory.ObjectType: ...
    def from_native(self, coordinate_ring: CategoryOfCategories.ElementType, native: object) -> ObjectType: ...
    def from_native_morphism(self, source: ObjectType, target: ObjectType, pullback: MorphismCategory.ObjectType, native: object) -> MorphismType: ...

def AffineSchemes() -> AffineSchemesCategory: ...
def native_affine_scheme(value: CategoryOfCategories.ElementType) -> NativeObjectRealization[object, AffineSchemeConstruction]: ...
def native_affine_morphism(value: MorphismCategory.ObjectType) -> NativeMorphismRealization[object]: ...
Spec: Functor
