from collections.abc import Callable, Hashable

from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor, NaturalTransformation
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.geometry.sheaves import RingSheaf
from sage_categories.geometry.spaces import TopologicalSpacesCategory

type SheafComponentRule = Callable[[frozenset[Hashable]], MorphismCategory.ObjectType]

class RingedSpacesCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def space(self) -> TopologicalSpacesCategory.ObjectType: ...
        def sheaf(self) -> RingSheaf: ...
    class ElementType(CategoryOfCategories.ElementType): ...
    class MorphismType(MorphismCategory.ObjectType):
        def continuous_map(self) -> MorphismCategory.ObjectType: ...
        def sheaf_map(self) -> NaturalTransformation: ...
    def to_spaces(self) -> Functor: ...
    def __call__(self, space: TopologicalSpacesCategory.ObjectType, sheaf: RingSheaf) -> ObjectType: ...
    def homomorphism(self, source: ObjectType, target: ObjectType, continuous: MorphismCategory.ObjectType, component_rule: SheafComponentRule) -> MorphismType: ...

def RingedSpaces() -> RingedSpacesCategory: ...
