from collections.abc import Callable, Hashable

from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory

class TopologicalSpacesCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def carrier(self) -> CategoryOfCategories.ElementType: ...
        def opens(self) -> CategoryOfCategories.ElementType: ...
        def open_category(self) -> Category: ...
        def open_point(self, key: object) -> CategoryOfCategories.ElementType: ...
        def open_object(self, key: object) -> CategoryOfCategories.ElementType: ...

    class ElementType(CategoryOfCategories.ElementType): ...

    class MorphismType(MorphismCategory.ObjectType):
        def underlying_map(self) -> MorphismCategory.ObjectType: ...
        def inverse_image(self) -> Functor: ...

    def to_sets(self) -> Functor: ...
    def __call__(self, carrier: CategoryOfCategories.ElementType, opens: tuple[frozenset[Hashable], ...]) -> ObjectType: ...
    def from_open_category(
        self,
        carrier: CategoryOfCategories.ElementType,
        opens: CategoryOfCategories.ElementType,
        open_category: Category,
        open_point_rule: Callable[[object], CategoryOfCategories.ElementType],
        open_object_rule: Callable[[object], CategoryOfCategories.ElementType],
    ) -> ObjectType: ...
    def construct_morphism(self, source: ObjectType, target: ObjectType, underlying: MorphismCategory.ObjectType) -> MorphismType: ...
    def morphism_with_inverse_image(self, source: ObjectType, target: ObjectType, underlying: MorphismCategory.ObjectType, inverse: Functor) -> MorphismType: ...

def TopologicalSpaces() -> TopologicalSpacesCategory: ...
