from collections.abc import Hashable

from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory

class TopologicalSpacesCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def carrier(self) -> CategoryOfCategories.ElementType: ...
        def opens(self) -> CategoryOfCategories.ElementType: ...
        def open_category(self) -> Category: ...
        def open_point(self, subset: frozenset[Hashable]) -> CategoryOfCategories.ElementType: ...
        def open_object(self, subset: frozenset[Hashable]) -> CategoryOfCategories.ElementType: ...
    class ElementType(CategoryOfCategories.ElementType): ...
    class MorphismType(MorphismCategory.ObjectType):
        def underlying_map(self) -> MorphismCategory.ObjectType: ...
        def inverse_image(self) -> Functor: ...
    def to_sets(self) -> Functor: ...
    def __call__(self, carrier: CategoryOfCategories.ElementType, opens: tuple[frozenset[Hashable], ...]) -> ObjectType: ...
    def construct_morphism(self, source: ObjectType, target: ObjectType, underlying: MorphismCategory.ObjectType) -> MorphismType: ...

def TopologicalSpaces() -> TopologicalSpacesCategory: ...
