from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.geometry.spaces import TopologicalSpacesCategory

class TopologicalRingsCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def ring(self) -> CategoryOfCategories.ElementType: ...
        def space(self) -> TopologicalSpacesCategory.ObjectType: ...
    class ElementType(CategoryOfCategories.ElementType): ...
    class MorphismType(MorphismCategory.ObjectType):
        def ring_map(self) -> MorphismCategory.ObjectType: ...
        def continuous_map(self) -> TopologicalSpacesCategory.MorphismType: ...
    def to_rings(self) -> Functor: ...
    def to_spaces(self) -> Functor: ...
    def __call__(self, ring: CategoryOfCategories.ElementType, space: TopologicalSpacesCategory.ObjectType) -> ObjectType: ...
    def homomorphism(self, source: ObjectType, target: ObjectType, ring_map: MorphismCategory.ObjectType, continuous_map: TopologicalSpacesCategory.MorphismType) -> MorphismType: ...

def TopologicalRings() -> TopologicalRingsCategory: ...
