from collections.abc import Callable

from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.geometry.spaces import TopologicalSpacesCategory

class ProductTopologyOpen:
    space: TopologicalSpacesCategory.ObjectType
    membership: Callable[[tuple[object, object]], bool | None]
    construction: object
    def contains(self, first: object, second: object) -> bool | None: ...

class BinaryContinuity:
    space: TopologicalSpacesCategory.ObjectType
    operation: MorphismCategory.ObjectType
    preimage_rule: Callable[[CategoryOfCategories.ElementType], ProductTopologyOpen]
    def preimage(self, open_object: CategoryOfCategories.ElementType) -> ProductTopologyOpen: ...

class TopologicalRingsCategory(Category):
    class ObjectType(CategoryOfCategories.ElementType):
        def ring(self) -> CategoryOfCategories.ElementType: ...
        def space(self) -> TopologicalSpacesCategory.ObjectType: ...
        def addition_continuity(self) -> BinaryContinuity: ...
        def multiplication_continuity(self) -> BinaryContinuity: ...
        def addition_preimage(self, open_object: CategoryOfCategories.ElementType) -> ProductTopologyOpen: ...
        def multiplication_preimage(self, open_object: CategoryOfCategories.ElementType) -> ProductTopologyOpen: ...
    class ElementType(CategoryOfCategories.ElementType): ...
    class MorphismType(MorphismCategory.ObjectType):
        def ring_map(self) -> MorphismCategory.ObjectType: ...
        def continuous_map(self) -> TopologicalSpacesCategory.MorphismType: ...
    def to_rings(self) -> Functor: ...
    def to_spaces(self) -> Functor: ...
    def __call__(self, ring: CategoryOfCategories.ElementType, space: TopologicalSpacesCategory.ObjectType, addition: BinaryContinuity, multiplication: BinaryContinuity) -> ObjectType: ...
    def homomorphism(self, source: ObjectType, target: ObjectType, ring_map: MorphismCategory.ObjectType, continuous_map: TopologicalSpacesCategory.MorphismType) -> MorphismType: ...

def TopologicalRings() -> TopologicalRingsCategory: ...
