from sage_categories.cat.adjunctions import Adjunctions as Adjunctions, Equivalences as Equivalences
from sage_categories.cat.calculus import binary_product_data as binary_product_data, curry as curry, currying as currying, evaluation as evaluation, natural_isomorphism as natural_isomorphism, pair_maps as pair_maps, power_functor as power_functor, precompose as precompose, product_functor as product_functor, transpose as transpose, uncurry as uncurry
from sage_categories.cat.category import Category as Category
from sage_categories.cat.cones import cocones as Cocones, colimit_cocones as ColimitCocones, cones as Cones, limit_cones as LimitCones
from sage_categories.cat.declarations import MagmaObjects as MagmaObjects, MonoidObjects as MonoidObjects, NN as NN, Posets as Posets, RingObjects as RingObjects, SemiringObjects as SemiringObjects, Sets as Sets, TotallyOrderedSets as TotallyOrderedSets, ZZ as ZZ, omega as omega
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.indexed import Grothendieck as Grothendieck, IndexedCategories as IndexedCategories
from sage_categories.cat.kan import left_kan_adjunction as left_kan_adjunction, left_kan_desc as left_kan_desc, left_kan_extension as left_kan_extension, left_kan_unit as left_kan_unit, right_kan_adjunction as right_kan_adjunction, right_kan_counit as right_kan_counit, right_kan_extension as right_kan_extension, right_kan_lift as right_kan_lift
from sage_categories.cat.limit_basis import DiagramPresentation as DiagramPresentation, colimit_from_coproducts_coequalizers as colimit_from_coproducts_coequalizers, diagram_presentation as diagram_presentation, limit_from_products_equalizers as limit_from_products_equalizers, parallel_pair as parallel_pair
from sage_categories.cat.morphisms import Mor as Mor
from sage_categories.cat.opposites import Op as Op
from sage_categories.cat.predicates import Axiom as Axiom, Decision as Decision, Predicate as Predicate, Query as Query, Unknown as Unknown, UnknownClass as UnknownClass, ask as ask, assume as assume, retract as retract
from sage_categories.cat.profunctors import Profunctors as Profunctors, compose_profunctor_transformations as compose_profunctor_transformations, compose_profunctors as compose_profunctors, identity_profunctor as identity_profunctor, profunctor_unitor as profunctor_unitor
from sage_categories.cat.relations import Relations as Relations
from sage_categories.cat.shapes import Discrete as Discrete, Thin as Thin
from sage_categories.cat.structured_objects import Algebras as Algebras, EilenbergMoore as EilenbergMoore, Equifier as Equifier, Inserter as Inserter, Magmas as Magmas, Monoids as Monoids, PointedMagmas as PointedMagmas
from sage_categories.cat.total_cones import total_cones as TotalCones
from sage_categories.cat.universal_arrows import InitialObjects as InitialObjects, LeftUniversalArrows as LeftUniversalArrows, RightUniversalArrows as RightUniversalArrows, TerminalObjects as TerminalObjects, left_mate as left_mate, right_mate as right_mate
from sage_categories.cat.weighted import Elements as Elements, coend as coend, coyoneda as coyoneda, element as element, element_projection as element_projection, end as end, end_to_natural_transformation as end_to_natural_transformation, hom_functor as hom_functor, natural_transformation_diagram as natural_transformation_diagram, natural_transformation_to_end as natural_transformation_to_end, weighted_colimit as weighted_colimit, weighted_colimit_desc as weighted_colimit_desc, weighted_colimit_map as weighted_colimit_map, weighted_injection as weighted_injection, weighted_limit as weighted_limit, weighted_limit_lift as weighted_limit_lift, weighted_limit_map as weighted_limit_map, weighted_projection as weighted_projection, yoneda as yoneda
__all__ = ['Adjunctions', 'Equivalences', 'binary_product_data', 'curry', 'currying', 'evaluation', 'natural_isomorphism', 'pair_maps', 'power_functor', 'precompose', 'product_functor', 'transpose', 'uncurry', 'Category', 'Cocones', 'ColimitCocones', 'Cones', 'LimitCones', 'NN', 'ZZ', 'MagmaObjects', 'MonoidObjects', 'Posets', 'RingObjects', 'SemiringObjects', 'Sets', 'TotallyOrderedSets', 'omega', 'Cat', 'Fun', 'Grothendieck', 'IndexedCategories', 'left_kan_adjunction', 'left_kan_desc', 'left_kan_extension', 'left_kan_unit', 'right_kan_adjunction', 'right_kan_counit', 'right_kan_extension', 'right_kan_lift', 'DiagramPresentation', 'colimit_from_coproducts_coequalizers', 'diagram_presentation', 'limit_from_products_equalizers', 'parallel_pair', 'Mor', 'Op', 'Axiom', 'Decision', 'Predicate', 'Query', 'Unknown', 'UnknownClass', 'ask', 'assume', 'retract', 'Profunctors', 'compose_profunctor_transformations', 'compose_profunctors', 'identity_profunctor', 'profunctor_unitor', 'Relations', 'Discrete', 'Thin', 'Algebras', 'EilenbergMoore', 'Equifier', 'Inserter', 'Magmas', 'Monoids', 'PointedMagmas', 'TotalCones', 'InitialObjects', 'LeftUniversalArrows', 'RightUniversalArrows', 'TerminalObjects', 'left_mate', 'right_mate', 'Elements', 'coend', 'coyoneda', 'element', 'element_projection', 'end', 'end_to_natural_transformation', 'hom_functor', 'natural_transformation_diagram', 'natural_transformation_to_end', 'weighted_colimit', 'weighted_colimit_desc', 'weighted_colimit_map', 'weighted_injection', 'weighted_limit', 'weighted_limit_lift', 'weighted_limit_map', 'weighted_projection', 'yoneda', '__version__', 'version']
__version__: str

def version() -> str:
    ...
