"""Owned categories with Sage confined to explicit realizations."""

from importlib.metadata import version as _distribution_version

from sage_categories.abstract_categories.arrow_categories import (
    ArrowCategory,
    Core,
    WideSubcategory,
    declare_isomorphism,
)
from sage_categories.abstract_categories.cat import Cat
from sage_categories.abstract_categories.functors import (
    ComposedFunctor,
    Functor,
    IdentityFunctor,
    NaturalIsomorphism,
    NaturalTransformation,
    NaturalTransformations,
    StructuralFunctor,
)
from sage_categories.abstract_categories.products import (
    Biproduct,
    Cocone,
    Cone,
    Coproduct,
    Product,
)
from sage_categories.abstract_categories.slice_categories import (
    Coslice,
    Covered,
    Covering,
    Slice,
    Subobject,
    Superobject,
)
from sage_categories.category import Category
from sage_categories.theories.cardinals import (
    Aleph0,
    Cardinal,
    CardinalComparison,
    CardinalHomCategory,
    CardinalMorphism,
    Cardinals,
    Continuum,
    aleph,
    aleph0,
    cardinal,
    continuum,
)
from sage_categories.theories.ordinals import (
    Ordinal,
    Ordinals,
    omega,
    omega0,
    ordinal,
)
from sage_categories.theories.sets import (
    Aleph,
    CartesianProductMorphismOfFamily,
    CartesianProductOfFamily,
    CartesianProductOfSets,
    ColimitOfSets,
    ConditionSet,
    CoproductMorphismOfFamily,
    CoproductOfFamily,
    CoproductOfSets,
    Delta,
    DiscreteCategories,
    DiscreteCategory,
    ExponentialOfSets,
    FiniteSubsets,
    FiniteDiscreteCategories,
    FiniteSet,
    FinitelySupportedFunctions,
    ImageSet,
    LimitOfSets,
    NaturalNumbers,
    ObjectSet,
    PartiallyOrderedSets,
    PowerSet,
    ProductOfSets,
    Set,
    SetFamily,
    SetMap,
    SetMapFromMapping,
    Sets,
    SubsetsOfSize,
    TotallyOrderedSets,
    TruthValues,
    cardinality_functor,
    cartesian_product_morphism,
    coproduct_morphism,
    finite_ordered_set,
    ordered_set_owned_by,
)
from sage_categories.values import (
    UNKNOWN,
    Arrow,
    Decision,
    MathematicalElement,
    MathematicalObject,
    Unknown,
)

__all__ = [
    "Aleph",
    "Aleph0",
    "Arrow",
    "ArrowCategory",
    "Biproduct",
    "Cardinal",
    "CardinalComparison",
    "CardinalHomCategory",
    "CardinalMorphism",
    "Cardinals",
    "CartesianProductMorphismOfFamily",
    "CartesianProductOfFamily",
    "CartesianProductOfSets",
    "Cat",
    "Category",
    "Cocone",
    "ColimitOfSets",
    "ComposedFunctor",
    "ConditionSet",
    "Cone",
    "Continuum",
    "Coproduct",
    "CoproductMorphismOfFamily",
    "CoproductOfFamily",
    "CoproductOfSets",
    "Core",
    "Coslice",
    "Covered",
    "Covering",
    "Decision",
    "Delta",
    "DiscreteCategories",
    "DiscreteCategory",
    "ExponentialOfSets",
    "FiniteDiscreteCategories",
    "FiniteSet",
    "FiniteSubsets",
    "FinitelySupportedFunctions",
    "Functor",
    "IdentityFunctor",
    "ImageSet",
    "LimitOfSets",
    "MathematicalElement",
    "MathematicalObject",
    "NaturalIsomorphism",
    "NaturalNumbers",
    "NaturalTransformation",
    "NaturalTransformations",
    "ObjectSet",
    "Ordinal",
    "Ordinals",
    "PartiallyOrderedSets",
    "PowerSet",
    "Product",
    "ProductOfSets",
    "Set",
    "SetFamily",
    "SetMap",
    "SetMapFromMapping",
    "Sets",
    "Slice",
    "StructuralFunctor",
    "Subobject",
    "SubsetsOfSize",
    "Superobject",
    "TotallyOrderedSets",
    "TruthValues",
    "UNKNOWN",
    "Unknown",
    "WideSubcategory",
    "__version__",
    "aleph",
    "aleph0",
    "cardinal",
    "cardinality_functor",
    "cartesian_product_morphism",
    "continuum",
    "coproduct_morphism",
    "declare_isomorphism",
    "finite_ordered_set",
    "omega",
    "omega0",
    "ordinal",
    "ordered_set_owned_by",
    "version",
]

# One source of truth. The version is declared once, in pyproject.toml, and
# read back from the installed distribution metadata rather than restated
# here, so a package built from this tree cannot disagree with itself.
__version__: str = _distribution_version("sage-categories")


def version() -> str:
    """Return the installed version of this package.

    At a Sage prompt the result prints on its own, so this is also the
    version print: ``import sage_categories; sage_categories.version()``.
    """
    return __version__
