from sage_categories.cat.category import CategoryDeclaration as CategoryDeclaration
from sage_categories.cat.functors import FunctorDeclaration as FunctorDeclaration
from sage_categories.posets.finite import FinitePosetRole as FinitePosetRole
from sage_categories.sets.category import Sets_Finite_ElementType as Sets_Finite_ElementType
from sage_categories.sets.category import Sets_Finite_MorphismType as Sets_Finite_MorphismType
from sage_categories.sets.elements import SetElementDeclaration as SetElementDeclaration
from sage_categories.sets.maps import SetMapDeclaration as SetMapDeclaration
from sage_categories.sets.objects import SetObjectDeclaration as SetObjectDeclaration
from _typeshed import Incomplete
from dataclasses import dataclass, field
from sage.misc.cachefunc import cached_method
from sage.structure.coerce_dict import MonoDict
from sage_categories.cat.category import Category as Category
from sage_categories.cat.constructions import cone as cone
from sage_categories.cat.diagrams import sequence_position as sequence_position
from sage_categories.cat.functors import Fun as Fun, Functor as Functor
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.cat.shapes import ThinCategory as ThinCategory
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, Proposition as Proposition, ask as ask, conjunction as conjunction, disjunction as disjunction, implication as implication, negation as negation
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, Role as Role, role_of as role_of
from sage_categories.sets.category import SetMap as SetMap, Sets as Sets
from sage_categories.sets.elements import Datum as Datum, SetElement as SetElement
from sage_categories.sets.maps import Rule as Rule
from sage_categories.sets.objects import MembershipRule as MembershipRule, SetObject as SetObject

partial_order: Predicate
order_preserving: Predicate
type Relation = dict[tuple[int, int], Decision]

@dataclass(eq=False, slots=True)
class PosetObjectData:
    relation: SetObject
    elements: MonoDict = field(default_factory=MonoDict)

@dataclass(frozen=True, eq=False, slots=True)
class PosetMorphismData:
    set_map: SetMap

class PosetDeclaration(SetObjectDeclaration):
    def __init__(self, data: PosetObjectData) -> None: ...
    def relation(self) -> SetObject: ...
    def element(self, point: SetElement) -> PosetElement: ...
    def sub_poset(self, predicate: MembershipRule) -> Poset: ...
    def is_total(self) -> AppliedPredicate: ...
    @cached_method
    def thin_category(self) -> ThinCategory: ...

class PosetElementDeclaration(SetElementDeclaration):
    def __le__(self, other: PosetElement) -> AppliedPredicate: ...
    def __lt__(self, other: PosetElement) -> Proposition: ...
    def __ge__(self, other: PosetElement) -> AppliedPredicate: ...
    def __gt__(self, other: PosetElement) -> Proposition: ...

class MonotoneMapDeclaration(SetMapDeclaration):
    ...

class PosetsCategory(CategoryDeclaration[[Rule], []]):
    @property
    def ObjectType(self) -> type[PosetDeclaration]: ...
    @property
    def ElementType(self) -> type[PosetElementDeclaration]: ...
    @property
    def MorphismType(self) -> type[MonotoneMapDeclaration]: ...
    DeclaredObjectType = PosetDeclaration
    DeclaredElementType = PosetElementDeclaration
    DeclaredMorphismType = MonotoneMapDeclaration
    def __init__(self) -> None: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    @cached_method
    def underlying_set_functor(self) -> Functor: ...
    def separating_family(self) -> tuple[Poset, ...]: ...
    def __call__(self, relation: SetObject) -> Poset: ...
    def carrier(self, relation: SetObject) -> SetObject: ...
    def is_partial_order(self, relation: SetObject) -> AppliedPredicate: ...
    def is_order_preserving(self, source: Poset, target: Poset, set_map: SetMap) -> AppliedPredicate: ...
    @cached_method
    def Simplex(self, dimension: int) -> Poset: ...
    @cached_method
    def Terminal(self) -> Poset: ...
    @cached_method
    def subset_poset(self, base_set: SetObject) -> Poset: ...
    @cached_method
    def Finite(self) -> Category[[Rule], []]: ...
    def TotallyOrdered(self) -> Category[[Rule], []]: ...
    def element_from_defining_morphism(self, defining_morphism: MonotoneMap) -> PosetElement: ...
    def construct_morphism(self, domain: Poset, codomain: Poset, rule: Rule) -> MonotoneMap: ...
    def construct_identity(self, poset: Poset) -> MonotoneMap: ...
    def composite(self, second: MonotoneMap, first: MonotoneMap) -> MonotoneMap: ...
    def inverse_morphism(self, monotone: MonotoneMap) -> MonotoneMap: ...

Poset = PosetDeclaration
PosetElement = PosetElementDeclaration
MonotoneMap = MonotoneMapDeclaration

def Posets() -> PosetsCategory: ...
def FinitePosets() -> Category[[Rule], []]: ...
def TotallyOrderedSets() -> Category[[Rule], []]: ...
def FiniteTotallyOrderedSets() -> Category[[Rule], []]: ...

class Posets_TotallyOrdered_ElementType(PosetElementDeclaration):
    ...

class Posets_TotallyOrdered_MorphismType(MonotoneMapDeclaration):
    ...

class Posets_TotallyOrdered_ObjectType(PosetDeclaration):
    ...

class Posets_Finite_ElementType(PosetElementDeclaration, Sets_Finite_ElementType):
    ...

class Posets_Finite_MorphismType(MonotoneMapDeclaration, Sets_Finite_MorphismType):
    ...

class Posets_Finite_WithBottom_ElementType(Posets_Finite_ElementType):
    ...

class Posets_Finite_WithBottom_MorphismType(Posets_Finite_MorphismType):
    ...

class Posets_Finite_WithTop_ElementType(Posets_Finite_ElementType):
    ...

class Posets_Finite_WithTop_MorphismType(Posets_Finite_MorphismType):
    ...

class Posets_Finite_Ranked_ElementType(Posets_Finite_ElementType):
    ...

class Posets_Finite_Ranked_MorphismType(Posets_Finite_MorphismType):
    ...

class Posets_Finite_Graded_ElementType(Posets_Finite_Ranked_ElementType, Posets_Finite_ElementType):
    ...

class Posets_Finite_Graded_MorphismType(Posets_Finite_Ranked_MorphismType, Posets_Finite_MorphismType):
    ...

class Posets_TotallyOrdered_Finite_ElementType(Posets_Finite_ElementType, Posets_TotallyOrdered_ElementType, PosetElementDeclaration):
    ...

class Posets_TotallyOrdered_Finite_MorphismType(Posets_Finite_MorphismType, Posets_TotallyOrdered_MorphismType, MonotoneMapDeclaration):
    ...

class Posets_TotallyOrdered_Finite_ObjectType(FinitePosetRole, Posets_TotallyOrdered_ObjectType, PosetDeclaration):
    ...
