from sage_categories.posets.finite import FinitePosetRole as FinitePosetRole
from sage_categories.sets.category import Sets_Finite_ElementType as Sets_Finite_ElementType
from sage_categories.sets.category import Sets_Finite_MorphismType as Sets_Finite_MorphismType
from _typeshed import Incomplete
from sage.misc.cachefunc import cached_method
from sage_categories.cat.category import Category as Category
from sage_categories.cat.constructions import cone as cone
from sage_categories.cat.diagrams import sequence_position as sequence_position
from sage_categories.cat.functors import Fun as Fun, Functor as Functor
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.cat.shapes import ThinCategory as ThinCategory
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, decision_and as decision_and, decision_not as decision_not, decision_or as decision_or
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, Proposition as Proposition, ask as ask
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, Role as Role, role_of as role_of
from sage_categories.sets.category import Sets as Sets
from sage_categories.sets.elements import Datum as Datum, SetPoint as SetPoint
from sage_categories.sets.maps import Rule as Rule, SetMap as SetMap
from sage_categories.sets.objects import MembershipRule as MembershipRule, SetObject as SetObject

partial_order: Incomplete
order_preserving: Incomplete
type Relation = dict[tuple[int, int], Decision]

class Poset(SetObject):
    def __init__(self, category: Category, underlying_set: SetObject, relation: SetObject) -> None: ...
    def relation(self) -> SetObject: ...
    def element(self, point: SetPoint) -> PosetElement: ...
    def sub_poset(self, predicate: MembershipRule) -> Poset: ...
    def is_total(self) -> AppliedPredicate: ...
    def thin_category(self) -> ThinCategory: ...

class PosetElement(SetPoint):
    def __init__(self, defining_morphism: MonotoneMap) -> None: ...
    def __le__(self, other: PosetElement) -> AppliedPredicate: ...
    def __lt__(self, other: PosetElement) -> Proposition: ...
    def __ge__(self, other: PosetElement) -> AppliedPredicate: ...
    def __gt__(self, other: PosetElement) -> Proposition: ...

class MonotoneMap(SetMap):
    def __init__(self, category: Category, domain: Poset, codomain: Poset, set_map: SetMap) -> None: ...

class PosetsCategory(Category[[Rule], []]):
    @property
    def ObjectType(self) -> type[Poset]: ...
    @property
    def ElementType(self) -> type[PosetElement]: ...
    @property
    def MorphismType(self) -> type[MonotoneMap]: ...
    def __init__(self) -> None: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def underlying_set_functor(self) -> Functor: ...
    def classical_stages(self) -> tuple[Poset, ...]: ...
    def __call__(self, relation: SetObject) -> Poset: ...
    def is_partial_order(self, relation: SetObject) -> AppliedPredicate: ...
    def is_order_preserving(self, source: Poset, target: Poset, set_map: SetMap) -> AppliedPredicate: ...
    def Simplex(self, dimension: int) -> Poset: ...
    def Terminal(self) -> Poset: ...
    def subset_poset(self, base_set: SetObject) -> Poset: ...
    @cached_method
    def Finite(self) -> Category[[Rule], []]: ...
    def TotallyOrdered(self) -> Category[[Rule], []]: ...
    def element_from_defining_morphism(self, defining_morphism: MonotoneMap) -> PosetElement: ...
    def construct_morphism(self, domain: Poset, codomain: Poset, rule: Rule) -> MonotoneMap: ...
    def construct_identity(self, poset: Poset) -> MonotoneMap: ...
    def composite(self, second: MonotoneMap, first: MonotoneMap) -> MonotoneMap: ...
    def inverse_morphism(self, monotone: MonotoneMap) -> MonotoneMap: ...

def Posets() -> PosetsCategory: ...
def FinitePosets() -> Category[[Rule], []]: ...
def TotallyOrderedSets() -> Category[[Rule], []]: ...
def FiniteTotallyOrderedSets() -> Category[[Rule], []]: ...

class Posets_TotallyOrdered_ElementType(PosetElement):
    ...

class Posets_TotallyOrdered_MorphismType(MonotoneMap):
    ...

class Posets_TotallyOrdered_ObjectType(Poset):
    ...

class Posets_Finite_ElementType(PosetElement, Sets_Finite_ElementType):
    ...

class Posets_Finite_MorphismType(MonotoneMap, Sets_Finite_MorphismType):
    ...

class Posets_Finite_WithBottom_ElementType(Posets_Finite_ElementType):
    ...

class Posets_Finite_WithBottom_MorphismType(Posets_Finite_MorphismType):
    ...

class Posets_Finite_WithTop_ElementType(Posets_Finite_ElementType):
    ...

class Posets_Finite_WithTop_MorphismType(Posets_Finite_MorphismType):
    ...

class Posets_Finite_Ranked_ElementType(Posets_Finite_ElementType):
    ...

class Posets_Finite_Ranked_MorphismType(Posets_Finite_MorphismType):
    ...

class Posets_Finite_Graded_ElementType(Posets_Finite_Ranked_ElementType, Posets_Finite_ElementType):
    ...

class Posets_Finite_Graded_MorphismType(Posets_Finite_Ranked_MorphismType, Posets_Finite_MorphismType):
    ...

class Posets_TotallyOrdered_Finite_ElementType(Posets_Finite_ElementType, Posets_TotallyOrdered_ElementType, PosetElement):
    ...

class Posets_TotallyOrdered_Finite_MorphismType(Posets_Finite_MorphismType, Posets_TotallyOrdered_MorphismType, MonotoneMap):
    ...

class Posets_TotallyOrdered_Finite_ObjectType(FinitePosetRole, Posets_TotallyOrdered_ObjectType, Poset):
    ...
