from sage_categories.posets.category import Posets_Finite_ElementType as Posets_Finite_ElementType
from sage_categories.posets.category import Posets_Finite_MorphismType as Posets_Finite_MorphismType
from sage_categories.sets.objects import FiniteSetRole as FiniteSetRole
from sage_categories.cat.category import Category as Category
from sage_categories.cat.diagrams import sequence_position as sequence_position
from sage_categories.cat.functors import Fun as Fun, Functor as Functor
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.cat.shapes import Discrete as Discrete
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, ask as ask
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ObjectOfCategory as ObjectOfCategory, Role as Role
from sage_categories.posets.category import Poset as Poset, PosetElement as PosetElement
from sage_categories.sets.cardinals import Cardinal as Cardinal, CardinalObject as CardinalObject
from sage_categories.sets.category import Sets as Sets
from sage_categories.sets.maps import Rule as Rule

class FinitePosetRole(Poset, FiniteSetRole):
    def has_bottom(self) -> AppliedPredicate: ...
    def has_top(self) -> AppliedPredicate: ...
    def is_ranked(self) -> AppliedPredicate: ...
    def is_graded(self) -> AppliedPredicate: ...
    def height(self) -> CardinalObject: ...
    def width(self) -> CardinalObject: ...
    def covers(self, lower: PosetElement, upper: PosetElement) -> Decision: ...
    def lower_covers(self, member: PosetElement) -> Poset: ...
    def upper_covers(self, member: PosetElement) -> Poset: ...
    def minimal_elements(self) -> Poset: ...
    def maximal_elements(self) -> Poset: ...
    def common_lower_covers(self, members: Poset) -> Poset: ...
    def common_upper_covers(self, members: Poset) -> Poset: ...
    def open_interval(self, lower: PosetElement, upper: PosetElement) -> Poset: ...
    def closed_interval(self, lower: PosetElement, upper: PosetElement) -> Poset: ...
    def principal_order_ideal(self, member: PosetElement) -> Poset: ...
    def principal_order_filter(self, member: PosetElement) -> Poset: ...
    def order_ideal(self, members: Poset) -> Poset: ...
    def order_filter(self, members: Poset) -> Poset: ...
    def is_chain_of_poset(self, members: Poset) -> Decision: ...
    def is_antichain_of_poset(self, members: Poset) -> Decision: ...
    def linear_extension(self) -> Poset: ...

class WithBottomRole(FinitePosetRole):
    def bottom(self) -> PosetElement: ...

class WithTopRole(FinitePosetRole):
    def top(self) -> PosetElement: ...

class RankedRole(FinitePosetRole):
    def rank(self) -> CardinalObject: ...
    def rank_of_element(self, member: PosetElement) -> CardinalObject: ...
    def level_sets(self) -> Functor: ...

class GradedRole(RankedRole, FinitePosetRole):
    ...

class FinitePosetsCategory(PropertySubcategory[[Rule], []]):
    @property
    def ObjectType(self) -> type[FinitePosetRole]: ...
    @property
    def ElementType(self) -> type[Posets_Finite_ElementType]: ...
    @property
    def MorphismType(self) -> type[Posets_Finite_MorphismType]: ...
    def __init__(self, ambient: Category[[Rule], []], name: str, roles: dict[Role, type], implications: tuple[Category, ...]) -> None: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def __call__(self, poset: Poset) -> Poset: ...
    def TotallyOrdered(self) -> Category[[Rule], []]: ...
    def WithBottom(self) -> Category[[Rule], []]: ...
    def WithTop(self) -> Category[[Rule], []]: ...
    def Ranked(self) -> Category[[Rule], []]: ...
    def Graded(self) -> Category[[Rule], []]: ...
