"""The theory of ``Cat()``: categories, functors, morphism categories, properties, shapes."""

from sage_categories.cat import _bootstrap as _bootstrap
from sage_categories.cat.adjunctions import Adjunctions, Equivalences
from sage_categories.cat.calculus import (
    binary_product_data,
    curry,
    currying,
    evaluation,
    natural_isomorphism,
    pair_maps,
    power_functor,
    precompose,
    product_functor,
    transpose,
    uncurry,
)
from sage_categories.cat.concrete import ConcreteCategory
from sage_categories.cat.cones import cones as Cones
from sage_categories.cat.cones import limit_cones as LimitCones
from sage_categories.cat.functors import Cat, Fun
from sage_categories.cat.kan import left_kan_adjunction, right_kan_adjunction
from sage_categories.cat.limit_basis import (
    DiagramPresentation,
    colimit_from_coproducts_coequalizers,
    diagram_presentation,
    limit_from_products_equalizers,
    parallel_pair,
)
from sage_categories.cat.modules import Modules
from sage_categories.cat.monoidal import (
    Actions,
    Cartesian,
    Composition,
    MonoidalStructures,
    SelfAction,
    TrivialAction,
)
from sage_categories.cat.morphisms import Mor
from sage_categories.cat.opposites import Op
from sage_categories.cat.profunctors import (
    Profunctors,
    compose_profunctor_transformations,
    compose_profunctors,
    identity_profunctor,
    profunctor_unitor,
)
from sage_categories.cat.relations import Relations
from sage_categories.cat.structured_objects import (
    AdditiveGroups,
    AdditiveMagmas,
    AdditiveMonoids,
    EilenbergMoore,
    EndofunctorAlgebras,
    Equifier,
    Groups,
    Inserter,
    Magmas,
    Monoids,
    MultiplicativeMagmas,
    MultiplicativeMonoids,
    PointedMagmas,
    Rings,
    Semirings,
)
from sage_categories.cat.total_cones import total_cones as TotalCones
from sage_categories.cat.universal_arrows import (
    InitialObjects,
    LeftUniversalArrows,
    RightUniversalArrows,
    TerminalObjects,
    left_mate,
    right_mate,
)
from sage_categories.cat.weighted import (
    Elements,
    coend,
    coyoneda,
    element,
    element_projection,
    end,
    end_to_natural_transformation,
    hom_functor,
    natural_transformation_diagram,
    natural_transformation_to_end,
    restricted_yoneda,
    separating_evaluation,
    separating_evaluation_injection,
    weighted_colimit,
    weighted_colimit_desc,
    weighted_colimit_map,
    weighted_injection,
    weighted_limit,
    weighted_limit_lift,
    weighted_limit_map,
    weighted_projection,
    yoneda,
)

del _bootstrap

__all__ = [
    "Actions",
    "AdditiveGroups",
    "AdditiveMagmas",
    "AdditiveMonoids",
    "Adjunctions",
    "Cartesian",
    "Cat",
    "Composition",
    "ConcreteCategory",
    "Cones",
    "DiagramPresentation",
    "EilenbergMoore",
    "Elements",
    "EndofunctorAlgebras",
    "Equifier",
    "Equivalences",
    "Fun",
    "Groups",
    "InitialObjects",
    "Inserter",
    "LeftUniversalArrows",
    "LimitCones",
    "Magmas",
    "Modules",
    "MonoidalStructures",
    "Monoids",
    "Mor",
    "MultiplicativeMagmas",
    "MultiplicativeMonoids",
    "Op",
    "PointedMagmas",
    "Profunctors",
    "Relations",
    "RightUniversalArrows",
    "Rings",
    "SelfAction",
    "Semirings",
    "TerminalObjects",
    "TotalCones",
    "TrivialAction",
    "binary_product_data",
    "coend",
    "colimit_from_coproducts_coequalizers",
    "compose_profunctor_transformations",
    "compose_profunctors",
    "coyoneda",
    "curry",
    "currying",
    "diagram_presentation",
    "element",
    "element_projection",
    "end",
    "end_to_natural_transformation",
    "evaluation",
    "hom_functor",
    "identity_profunctor",
    "left_kan_adjunction",
    "left_mate",
    "limit_from_products_equalizers",
    "natural_isomorphism",
    "natural_transformation_diagram",
    "natural_transformation_to_end",
    "restricted_yoneda",
    "separating_evaluation",
    "separating_evaluation_injection",
    "pair_maps",
    "parallel_pair",
    "power_functor",
    "precompose",
    "product_functor",
    "profunctor_unitor",
    "right_kan_adjunction",
    "right_mate",
    "transpose",
    "uncurry",
    "weighted_colimit",
    "weighted_colimit_desc",
    "weighted_colimit_map",
    "weighted_injection",
    "weighted_limit",
    "weighted_limit_lift",
    "weighted_limit_map",
    "weighted_projection",
    "yoneda",
]
