from collections.abc import Hashable
from dataclasses import dataclass

import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.declarations import Sets as Sets
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import Unknown as Unknown
from sage_categories.cat.predicates import UnknownClass as UnknownClass
from sage_categories.cat.predicates import ask as ask
from sage_categories.cat.predicates import register_handler as register_handler
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.sage_runtime import MonoDict as MonoDict
from sage_categories.kernel.sage_runtime import cached_function as cached_function

__all__ = ["FinitePresentedCategory", "boundary", "empty_category", "enumerated_datum", "horn", "simplex", "walking_isomorphism", "walking_parallel_pair"]
type Word = tuple[str, ...]
type Generator = tuple[str, Hashable, Hashable]
type Relation = tuple[Word, Word]

@dataclass(frozen=True, eq=False, slots=True)
class VertexData:
    label: Hashable

@dataclass(frozen=True, eq=False, slots=True)
class PathData:
    word: Word

class _StaticRoles_FinitePresentedCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def __init__(self, data: VertexData) -> None: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def __init__(self, data: PathData) -> None: ...
        def word(self) -> Word: ...
        def domain(self) -> FinitePresentedCategory.ObjectType: ...
        def codomain(self) -> FinitePresentedCategory.ObjectType: ...

class FinitePresentedCategory(
    _StaticRoles_FinitePresentedCategory,
    Category[[Word], [], _StaticRoles_FinitePresentedCategory.ObjectType, _StaticRoles_FinitePresentedCategory.ElementType, _StaticRoles_FinitePresentedCategory.MorphismType],
):
    def __init__(self, name: str, labels: tuple[Hashable, ...], generators: tuple[Generator, ...], relations: tuple[Relation, ...]) -> None: ...
    def __call__(self, label: Hashable) -> FinitePresentedCategory.ObjectType: ...
    def label(self, vertex: FinitePresentedCategory.ObjectType) -> Hashable: ...
    def labels(self) -> tuple[Hashable, ...]: ...
    def generator_names(self) -> tuple[str, ...]: ...
    def is_discrete(self) -> bool: ...
    def generator(self, name: str) -> FinitePresentedCategory.MorphismType: ...
    def object_set(self) -> CategoryOfCategories.ElementType: ...
    def object_at(self, point: CategoryOfCategories.ElementType) -> FinitePresentedCategory.ObjectType: ...
    def object_point(self, vertex: FinitePresentedCategory.ObjectType) -> CategoryOfCategories.ElementType: ...
    def finite_morphisms(self) -> tuple[FinitePresentedCategory.MorphismType, ...] | UnknownClass: ...
    def Terminal(self) -> FinitePresentedCategory.ObjectType: ...
    def morphism_at(self, point: CategoryOfCategories.ElementType) -> FinitePresentedCategory.MorphismType: ...
    def generating_morphisms(self) -> tuple[FinitePresentedCategory.MorphismType, ...]: ...
    def relations(self) -> tuple[Relation, ...]: ...
    def construct_morphism(
        self, domain: FinitePresentedCategory.ObjectType, codomain: FinitePresentedCategory.ObjectType, word: Word
    ) -> FinitePresentedCategory.MorphismType: ...
    def construct_identity(self, vertex: FinitePresentedCategory.ObjectType) -> FinitePresentedCategory.MorphismType: ...
    def composite(self, second: FinitePresentedCategory.MorphismType, first: FinitePresentedCategory.MorphismType) -> FinitePresentedCategory.MorphismType: ...
    def inverse_morphism(self, morphism: FinitePresentedCategory.MorphismType) -> FinitePresentedCategory.MorphismType: ...

def enumerated_datum(finite_set: CategoryOfCategories.ElementType, point: CategoryOfCategories.ElementType) -> Hashable: ...
def empty_category() -> FinitePresentedCategory: ...
def simplex(dimension: int) -> FinitePresentedCategory: ...
def boundary(dimension: int) -> FinitePresentedCategory: ...
def horn(dimension: int, omitted_face: int) -> FinitePresentedCategory: ...
def walking_isomorphism() -> FinitePresentedCategory: ...
def walking_parallel_pair() -> FinitePresentedCategory: ...
@cached_function
def _finite_discrete(length: int) -> FinitePresentedCategory: ...
