from sage_categories.cat.category import CategoryDeclaration as CategoryDeclaration
from sage_categories.cat.elements import CategoryPointDeclaration as CategoryPointDeclaration
from collections.abc import Hashable
from dataclasses import dataclass
from sage_categories.cat.category import Category as Category
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory
from sage_categories.sets.elements import SetElement as SetElement
from sage_categories.sets.objects import SetObject as SetObject

type Word = tuple[str, ...]
type Generator = tuple[str, Hashable, Hashable]
type Relation = tuple[Word, Word]
@dataclass(frozen=True, eq=False, slots=True)
class VertexData:
    label: Hashable

class Vertex(ObjectOfCategory):
    def __init__(self, data: VertexData) -> None: ...

@dataclass(frozen=True, eq=False, slots=True)
class PathData:
    word: Word

class Path(MorphismOfCategory):
    def __init__(self, data: PathData) -> None: ...
    def word(self) -> Word: ...

class FinitePresentedCategory(CategoryDeclaration[[Word], []]):
    DeclaredObjectType = Vertex
    DeclaredMorphismType = Path
    class DeclaredElementType(ElementOfObject):
        ...
    def __init__(self, name: str, labels: tuple[Hashable, ...], generators: tuple[Generator, ...], relations: tuple[Relation, ...]) -> None: ...
    def __call__(self, label: Hashable) -> Vertex: ...
    def label(self, vertex: Vertex) -> Hashable: ...
    def labels(self) -> tuple[Hashable, ...]: ...
    def generator_names(self) -> tuple[str, ...]: ...
    def generator(self, name: str) -> Path: ...
    def object_set(self) -> SetObject: ...
    def object_at(self, point: SetElement) -> Vertex: ...
    def object_point(self, vertex: Vertex) -> SetElement: ...
    def morphism_set(self) -> SetObject | UnknownClass: ...
    def morphism_at(self, point: SetElement) -> Path: ...
    def generating_morphisms(self) -> tuple[Path, ...]: ...
    def construct_morphism(self, domain: Vertex, codomain: Vertex, word: Word) -> Path: ...
    def construct_identity(self, vertex: Vertex) -> Path: ...
    def composite(self, second: Path, first: Path) -> Path: ...
    def inverse_morphism(self, morphism: Path) -> Path: ...

def enumerated_datum(finite_set: SetObject, point: SetElement) -> Hashable: ...
def empty_category() -> FinitePresentedCategory: ...
def simplex(dimension: int) -> FinitePresentedCategory: ...
def boundary(dimension: int) -> FinitePresentedCategory: ...
def horn(dimension: int, omitted_face: int) -> FinitePresentedCategory: ...
def walking_isomorphism() -> FinitePresentedCategory: ...
def walking_parallel_pair() -> FinitePresentedCategory: ...
