from collections.abc import Hashable
from sage_categories.cat.category import Category as Category
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory
from sage_categories.sets.elements import SetPoint as SetPoint
from sage_categories.sets.objects import SetObject as SetObject

type Word = tuple[str, ...]
type Generator = tuple[str, Hashable, Hashable]
type Relation = tuple[Word, Word]
class Vertex(ObjectOfCategory):
    def __init__(self, category: Category, label: Hashable) -> None: ...

class Path(MorphismOfCategory):
    def __init__(self, category: Category, domain: Vertex, codomain: Vertex, word: Word) -> None: ...
    def word(self) -> Word: ...

class FinitePresentedCategory(Category[[Word], []]):
    @property
    def ObjectType(self) -> type[ObjectOfCategory]: ...
    @property
    def ElementType(self) -> type[ElementOfObject]: ...
    @property
    def MorphismType(self) -> type[MorphismOfCategory]: ...
    class ElementType(ElementOfObject):
        ...
    def __init__(self, name: str, labels: tuple[Hashable, ...], generators: tuple[Generator, ...], relations: tuple[Relation, ...]) -> None: ...
    def __call__(self, label: Hashable) -> Vertex: ...
    def label(self, vertex: Vertex) -> Hashable: ...
    def labels(self) -> tuple[Hashable, ...]: ...
    def generator_names(self) -> tuple[str, ...]: ...
    def generator(self, name: str) -> Path: ...
    def object_set(self) -> SetObject: ...
    def object_at(self, point: SetPoint) -> Vertex: ...
    def object_point(self, vertex: Vertex) -> SetPoint: ...
    def morphism_set(self) -> SetObject | UnknownClass: ...
    def morphism_at(self, point: SetPoint) -> Path: ...
    def generating_morphisms(self) -> tuple[Path, ...]: ...
    def construct_morphism(self, domain: Vertex, codomain: Vertex, word: Word) -> Path: ...
    def construct_identity(self, vertex: Vertex) -> Path: ...
    def composite(self, second: Path, first: Path) -> Path: ...
    def inverse_morphism(self, morphism: Path) -> Path: ...

def enumerated_datum(finite_set: SetObject, point: SetPoint) -> Hashable: ...
def empty_category() -> FinitePresentedCategory: ...
def simplex(dimension: int) -> FinitePresentedCategory: ...
def boundary(dimension: int) -> FinitePresentedCategory: ...
def horn(dimension: int, omitted_face: int) -> FinitePresentedCategory: ...
def walking_isomorphism() -> FinitePresentedCategory: ...
def walking_parallel_pair() -> FinitePresentedCategory: ...
