from collections.abc import Callable, Hashable
from dataclasses import dataclass
from sage.misc.cachefunc import cached_method
from sage_categories.cat.canonical import FinitePresentedCategory
from sage_categories.cat.functors import Functor, FunctorsCategory, NaturalTransformation
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.cat.points import PointCategory
from sage.misc.unknown import UnknownClass as _UnknownClass
from sage_categories.cat.predicates import AppliedQuery, Axiom, Decision, Predicate, Proposition, Query, ask, assume
from typing import Literal, overload

type OnObject = Callable[[CategoryOfCategories.ElementType], CategoryOfCategories.ElementType]
type OnMorphism = Callable[[MorphismCategory.ObjectType], MorphismCategory.ObjectType]
type Assignment = Callable[[CategoryOfCategories.ElementType], MorphismCategory.ObjectType]
type LiftRule = Callable[[MorphismCategory.ObjectType, CategoryOfCategories.ElementType], MorphismCategory.ObjectType]
member: Predicate

@dataclass(frozen=True, eq=False, slots=True)
class FunctorData:
    on_object: OnObject
    on_morphism: OnMorphism

def _morphism_set() -> Query: ...

class CategoryDeclaration[**MorphismData, **TwoMorphismData]:
    class ObjectType: ...
    class ElementType: ...
    class MorphismType:
        def op(self) -> CategoryDeclaration.MorphismType: ...
    def __init__(self, data: None = None) -> None: ...
    def __mul__(self, other: Category) -> Category: ...
    def __add__(self, other: Category) -> Category: ...
    def __pow__(self, exponent: Category) -> Category: ...
    def op(self) -> Category: ...
    def universe(self) -> CategoryOfCategories: ...
    def ordinal(self) -> int: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def retain_datum[Datum](self, value: CategoryOfCategories.ElementType, datum: Datum) -> None: ...
    def retained_datum[Datum](self, value: CategoryOfCategories.ElementType) -> Datum: ...
    def has_ambient(self) -> bool: ...
    def has_full_ambient(self) -> bool: ...
    def ambient(self) -> Category[MorphismData, TwoMorphismData]: ...
    def subcategory_monomorphism(self) -> Functor: ...
    def _chosen_hom_inhabited(self, hom_category: Category) -> Decision: ...
    def equality(self) -> Predicate: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __contains__(self, candidate: CategoryOfCategories.ElementType) -> bool: ...
    @overload
    def morphism_category(self, level: Literal[0]) -> Category[MorphismData, TwoMorphismData]: ...
    @overload
    def morphism_category(self, level: Literal[1]) -> MorphismCategory[MorphismData, TwoMorphismData]: ...
    @overload
    def morphism_category(self, level: Literal[2]) -> MorphismCategory[TwoMorphismData, []]: ...
    @overload
    def morphism_category(self, level: int) -> MorphismCategory[[], []]: ...
    def morphism_category_type(self) -> type[MorphismCategory[MorphismData, TwoMorphismData]]: ...
    def base_category(self) -> Category: ...
    def identity_morphism(self, member_object: CategoryDeclaration.ObjectType) -> CategoryDeclaration.MorphismType: ...
    def retain_inverses(self, forward: CategoryDeclaration.MorphismType, backward: CategoryDeclaration.MorphismType) -> None: ...
    def compose_morphisms(self, second: CategoryDeclaration.MorphismType, first: CategoryDeclaration.MorphismType) -> CategoryDeclaration.MorphismType: ...
    def inverse_morphism(self, morphism: CategoryDeclaration.MorphismType) -> CategoryDeclaration.MorphismType: ...
    def element_from_defining_morphism(self, defining_morphism: CategoryDeclaration.MorphismType) -> CategoryDeclaration.ElementType: ...
    def construct_morphism(self, domain: CategoryDeclaration.ObjectType, codomain: CategoryDeclaration.ObjectType, *args: MorphismData.args, **kwargs: MorphismData.kwargs) -> CategoryDeclaration.MorphismType: ...
    def construct_identity(self, member_object: CategoryDeclaration.ObjectType) -> CategoryDeclaration.MorphismType: ...
    def composite(self, second: CategoryDeclaration.MorphismType, first: CategoryDeclaration.MorphismType) -> CategoryDeclaration.MorphismType: ...
    def identity_two_morphism(self, morphism: CategoryDeclaration.MorphismType) -> CategoryDeclaration.MorphismType: ...
    def compose_two_morphisms(self, second: CategoryDeclaration.MorphismType, first: CategoryDeclaration.MorphismType) -> CategoryDeclaration.MorphismType: ...
    def construct_two_morphism(self, first: CategoryDeclaration.MorphismType, second: CategoryDeclaration.MorphismType, *args: TwoMorphismData.args, **kwargs: TwoMorphismData.kwargs) -> CategoryDeclaration.MorphismType: ...
    def point_functor(self, member_object: CategoryDeclaration.ObjectType) -> Functor: ...
    def arrow_functor(self, morphism: CategoryDeclaration.MorphismType) -> Functor: ...
    def represented_functor(self) -> Functor: ...
    @cached_method
    def Products(self) -> Category: ...
    @cached_method
    def Coproducts(self) -> Category: ...
    def Limits(self, shape: Category) -> Category: ...
    def Colimits(self, shape: Category) -> Category: ...
    def Pullbacks(self) -> Category: ...
    def Pushouts(self) -> Category: ...
    def Equalizers(self) -> Category: ...
    def Coequalizers(self) -> Category: ...
    def StrictImage(self, functor: Functor) -> Category: ...
    def FullImage(self, functor: Functor) -> Category: ...
    def EssentialImage(self, functor: Functor) -> Category: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], CategoryDeclaration.ObjectType]: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], CategoryDeclaration.ObjectType]: ...
    def SliceOver(self, member_object: CategoryDeclaration.ObjectType) -> Category: ...
    def CosliceUnder(self, member_object: CategoryDeclaration.ObjectType) -> Category: ...
    def Comma(self, first: Functor, second: Functor) -> Category: ...
    def Subobjects(self, member_object: CategoryDeclaration.ObjectType) -> Category: ...
    def Superobjects(self, member_object: CategoryDeclaration.ObjectType) -> Category: ...
    def CoveringObjects(self, member_object: CategoryDeclaration.ObjectType) -> Category: ...
    def CoveredObjects(self, member_object: CategoryDeclaration.ObjectType) -> Category: ...
    def Core(self) -> Category: ...
    def object_set(self) -> CategoryDeclaration.ObjectType: ...
    def object_at(self, point: CategoryDeclaration.ElementType) -> CategoryDeclaration.ObjectType: ...
    def object_point(self, member_object: CategoryDeclaration.ObjectType) -> CategoryDeclaration.ElementType: ...
    def morphism_set(self) -> AppliedQuery: ...
    def _chosen_morphism_set(self) -> CategoryDeclaration.ObjectType | _UnknownClass: ...
    def morphism_at(self, point: CategoryDeclaration.ElementType) -> CategoryDeclaration.MorphismType: ...
    def generating_morphisms(self) -> tuple[CategoryDeclaration.MorphismType, ...] | _UnknownClass: ...
    def biproduct(self, first: CategoryDeclaration.ObjectType, second: CategoryDeclaration.ObjectType) -> CategoryDeclaration.ObjectType: ...
    def exponential(self, exponent: CategoryDeclaration.ObjectType, base: CategoryDeclaration.ObjectType) -> CategoryDeclaration.ObjectType: ...
    def name(self) -> str: ...
    def narrowing_base(self) -> Category[MorphismData, TwoMorphismData]: ...
    def narrowing_roots(self) -> tuple[Category[MorphismData, TwoMorphismData], ...]: ...
    def intersection(self, roots: tuple[Category[MorphismData, TwoMorphismData], ...]) -> Category[MorphismData, TwoMorphismData]: ...
    def property_subcategory(self, property_category: Category[MorphismData, TwoMorphismData]) -> Category[MorphismData, TwoMorphismData]: ...
    def narrowing_type(self) -> type[Category[MorphismData, TwoMorphismData]]: ...
Category = CategoryDeclaration

class CategoryOfCategories(CategoryDeclaration[[OnObject, OnMorphism], [Assignment]]):
    class MorphismType(CategoryDeclaration.MorphismType):
        def __init__(self, data: FunctorData) -> None: ...
        def on_object(self, member_object: Category.ObjectType) -> Category.ObjectType: ...
        def on_morphism(self, morphism: Category.MorphismType) -> Category.MorphismType: ...
        def on_element(self, element: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
        def __call__(self, value: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
        def inverse_image(self, subcategory: Category) -> Category: ...
        def op(self) -> Functor: ...
        def Fiber(self, member_object: CategoryOfCategories.ElementType) -> Category: ...
        def retain_terminal_comparison(self, comparison: Category.MorphismType) -> None: ...
        def terminal_comparison(self) -> Category.MorphismType: ...
        def after_terminal_comparison(self, image: Category.MorphismType, defining: Category.MorphismType) -> Category.MorphismType: ...
        def retain_factors(self, first: CategoryOfCategories.MorphismType, second: CategoryOfCategories.MorphismType) -> None: ...
        def factors(self) -> tuple[CategoryOfCategories.MorphismType, CategoryOfCategories.MorphismType]: ...
        def retain_cartesian_lifts(self, rule: LiftRule) -> None: ...
        def retain_cocartesian_lifts(self, rule: LiftRule) -> None: ...
        def cartesian_lift(self, morphism: Category.MorphismType, member_object: CategoryOfCategories.ElementType) -> Category.MorphismType: ...
        def cocartesian_lift(self, morphism: Category.MorphismType, member_object: CategoryOfCategories.ElementType) -> Category.MorphismType: ...
        def is_full(self) -> Proposition: ...
        def is_faithful(self) -> Proposition: ...
        def is_fully_faithful(self) -> Proposition: ...
        def is_essentially_surjective(self) -> Proposition: ...
        def is_equivalence(self) -> Proposition: ...
    def __init__(self) -> None: ...
    def morphism_category_type(self) -> type[FunctorsCategory]: ...
    def construct_morphism(self, domain: Category, codomain: Category, on_object: OnObject, on_morphism: OnMorphism) -> Functor: ...
    def construct_identity(self, category: Category) -> Functor: ...
    def composite(self, second: Functor, first: Functor) -> Functor: ...
    def construct_two_morphism(self, source: CategoryOfCategories.ElementType, target: CategoryOfCategories.ElementType, assignment: Assignment) -> NaturalTransformation: ...
    def identity_two_morphism(self, member_object: CategoryOfCategories.ElementType) -> NaturalTransformation: ...
    def compose_two_morphisms(self, second: NaturalTransformation, first: NaturalTransformation) -> NaturalTransformation: ...
    def whisker_left(self, functor: Functor, transformation: NaturalTransformation) -> NaturalTransformation: ...
    def whisker_right(self, transformation: NaturalTransformation, functor: Functor) -> NaturalTransformation: ...
    def horizontal_composite(self, second: NaturalTransformation, first: NaturalTransformation) -> NaturalTransformation: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], CategoryOfCategories.ObjectType]: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], CategoryOfCategories.ObjectType]: ...
    def exponential(self, exponent: Category, base: Category) -> Category: ...
    def postcompose(self, functor: Functor, diagram: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
    def exponential_on_morphism(self, exponent: Category, functor: Functor) -> Functor: ...
    def __call__(self, labels: tuple[Hashable, ...], generators: tuple[tuple[str, Hashable, Hashable], ...], relations: tuple[tuple[tuple[str, ...], tuple[str, ...]], ...]) -> FinitePresentedCategory: ...
    def Initial(self) -> FinitePresentedCategory: ...
    def Terminal(self) -> FinitePresentedCategory: ...
    def Point(self, member: CategoryOfCategories.ElementType) -> PointCategory: ...
    def Simplex(self, dimension: int) -> FinitePresentedCategory: ...
    def Boundary(self, dimension: int) -> FinitePresentedCategory: ...
    def Horn(self, dimension: int, omitted_face: int) -> FinitePresentedCategory: ...
    def WalkingIsomorphism(self) -> FinitePresentedCategory: ...
    def WalkingParallelPair(self) -> FinitePresentedCategory: ...
    def element_from_defining_morphism(self, defining_functor: Functor) -> CategoryOfCategories.ElementType: ...

def bootstrap() -> None: ...
def Cat() -> CategoryOfCategories: ...
