import typing as _typing
from collections.abc import Callable
from collections.abc import Hashable as Hashable
from dataclasses import dataclass
from typing import Literal, overload

from _typeshed import Incomplete

import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
from sage_categories.cat.canonical import FinitePresentedCategory as FinitePresentedCategory
from sage_categories.cat.comma import CommaCategory as CommaCategory
from sage_categories.cat.constructions import LimitApexLift as LimitApexLift
from sage_categories.cat.constructions import LimitMorphismLift as LimitMorphismLift
from sage_categories.cat.constructions import UniversalPresentation as UniversalPresentation
from sage_categories.cat.declarations import CategoryFamily as CategoryFamily
from sage_categories.cat.equality import equality_predicate as equality_predicate
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import FunctorsCategory as FunctorsCategory
from sage_categories.cat.functors import NaturalTransformation as NaturalTransformation
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.points import PointCategory as PointCategory
from sage_categories.cat.predicates import (
    AppliedQuery as AppliedQuery,
)
from sage_categories.cat.predicates import (
    Axiom as Axiom,
)
from sage_categories.cat.predicates import (
    ConstructionFamily as ConstructionFamily,
)
from sage_categories.cat.predicates import (
    Decision as Decision,
)
from sage_categories.cat.predicates import (
    Predicate as Predicate,
)
from sage_categories.cat.predicates import (
    Proposition as Proposition,
)
from sage_categories.cat.predicates import (
    Query as Query,
)
from sage_categories.cat.predicates import (
    Unknown as Unknown,
)
from sage_categories.cat.predicates import (
    UnknownClass as UnknownClass,
)
from sage_categories.cat.predicates import (
    ask as ask,
)
from sage_categories.cat.predicates import (
    register_handler as register_handler,
)
from sage_categories.kernel.refinement import is_placed as is_placed
from sage_categories.kernel.refinement import is_subcategory as is_subcategory
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.retention import category_construction_functors as category_construction_functors
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.roles import prepare_category_subclass as prepare_category_subclass
from sage_categories.kernel.sage_runtime import Integer as Integer
from sage_categories.kernel.sage_runtime import MonoDict as MonoDict
from sage_categories.kernel.sage_runtime import TripleDict as TripleDict
from sage_categories.kernel.sage_runtime import cached_method as cached_method
from sage_categories.kernel.type_aliases import ContainmentInput as ContainmentInput
from sage_categories.kernel.type_aliases import EqualityInput as EqualityInput

__all__ = ["Assignment", "Cat", "Category", "CategoryOfCategories", "OnMorphism", "OnObject", "member"]
type OnObject = Callable[[CategoryOfCategories.ElementType], CategoryOfCategories.ElementType]
type OnMorphism = Callable[["MorphismCategory.ObjectType"], "MorphismCategory.ObjectType"]
type Assignment = Callable[[CategoryOfCategories.ElementType], "MorphismCategory.ObjectType"]
member: Predicate

class CategoryDeclaration[
    **MorphismData,
    **TwoMorphismData,
    _ObjectRole = "CategoryOfCategories.ElementType",
    _ElementRole = "CategoryOfCategories.ElementType",
    _MorphismRole = "MorphismCategory.ObjectType",
](sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
    def __init__(self, data: None = None) -> None: ...
    def is_discrete(self) -> bool: ...
    def construction_owner(self) -> Category: ...
    def subobjects_type(self) -> type: ...
    def __init_subclass__(cls) -> None: ...
    def __mul__(self, other: Category) -> Category: ...
    def __add__(self, other: Category) -> Category: ...
    def __pow__(self, exponent: Category) -> Category: ...
    def op(self) -> Category: ...
    def universe(self) -> CategoryOfCategories: ...
    def ordinal(self) -> int: ...
    def recompile(self) -> None: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def selected_functors(self) -> tuple[Functor, ...]: ...
    def has_ambient(self) -> bool: ...
    def has_full_ambient(self) -> bool: ...
    def ambient(self) -> Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]: ...
    def subcategory_monomorphism(self) -> Functor: ...
    def equality(self) -> Predicate: ...
    def owns_equality(self) -> bool: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __contains__(self, candidate: ContainmentInput) -> bool: ...
    @overload
    def morphism_category(self, level: Literal[0]) -> Category[MorphismData, TwoMorphismData]: ...
    @overload
    def morphism_category(self, level: Literal[1]) -> MorphismCategory[MorphismData, TwoMorphismData]: ...
    @overload
    def morphism_category(self, level: Literal[2]) -> MorphismCategory[TwoMorphismData, []]: ...
    @overload
    def morphism_category(self, level: int | Integer) -> MorphismCategory[[], []]: ...
    def morphism_category_type(self) -> type[MorphismCategory[MorphismData, TwoMorphismData]]: ...
    def base_category(self) -> Category: ...
    def retained_inverse(self, morphism: _MorphismRole) -> _MorphismRole | None: ...
    def retain_inverses(self, forward: _MorphismRole, backward: _MorphismRole) -> None: ...
    def compose_morphisms(self, second: _MorphismRole, first: _MorphismRole) -> _MorphismRole: ...
    def inverse_morphism(self, morphism: _MorphismRole) -> _MorphismRole: ...
    def element_from_defining_morphism(self, defining_morphism: _MorphismRole) -> _ElementRole: ...
    def construct_morphism(self, domain: _ObjectRole, codomain: _ObjectRole, *args: MorphismData.args, **kwargs: MorphismData.kwargs) -> _MorphismRole: ...
    def construct_identity(self, member_object: _ObjectRole) -> _MorphismRole: ...
    def composite(self, second: _MorphismRole, first: _MorphismRole) -> _MorphismRole: ...
    def identity_two_morphism(self, morphism: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    def compose_two_morphisms(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    def construct_two_morphism(
        self, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType, *args: TwoMorphismData.args, **kwargs: TwoMorphismData.kwargs
    ) -> MorphismCategory.ObjectType: ...
    def Terminal(self) -> _ObjectRole: ...
    def point_morphism(self, point: _ElementRole) -> _MorphismRole: ...
    def point_functor(self, member_object: _ObjectRole) -> Functor: ...
    def Point(self) -> Functor: ...
    def arrow_functor(self, morphism: _MorphismRole) -> Functor: ...
    Products: Incomplete
    Coproducts: Incomplete
    Limits: Incomplete
    Colimits: Incomplete
    EssentialImage: Incomplete

    def Pullbacks(self) -> Category: ...
    def Pushouts(self) -> Category: ...
    def Equalizers(self) -> Category: ...
    def Coequalizers(self) -> Category: ...
    def StrictImage(self, functor: Functor) -> Category: ...
    def FullImage(self, functor: Functor) -> Category: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], _ObjectRole]: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], _ObjectRole]: ...
    def presenting_diagrams(self, constructed: _ObjectRole) -> tuple[Functor, ...]: ...
    def SliceOver(self, member_object: _ObjectRole) -> Category: ...
    def CosliceUnder(self, member_object: _ObjectRole) -> Category: ...
    def Subobjects(self, member_object: _ObjectRole) -> Category: ...
    def Superobjects(self, member_object: _ObjectRole) -> Category: ...
    def CoveringObjects(self, member_object: _ObjectRole) -> Category: ...
    def CoveredObjects(self, member_object: _ObjectRole) -> Category: ...
    def Core(self) -> Category: ...
    def object_set(self) -> CategoryOfCategories.ElementType: ...
    def object_at(self, point: CategoryOfCategories.ElementType) -> _ObjectRole: ...
    def object_point(self, member_object: _ObjectRole) -> CategoryOfCategories.ElementType: ...
    def morphism_set(self) -> AppliedQuery: ...
    def morphism_at(self, point: CategoryOfCategories.ElementType) -> _MorphismRole: ...
    def generating_morphisms(self) -> tuple[_MorphismRole, ...] | UnknownClass: ...
    def hom_morphisms(self, source: _ObjectRole, target: _ObjectRole) -> tuple[_MorphismRole, ...] | UnknownClass: ...
    def image_factorization(self, arrow: _MorphismRole) -> tuple[_MorphismRole, _MorphismRole]: ...
    def factor_through_monomorphism(self, mono: _MorphismRole, arrow: _MorphismRole) -> _MorphismRole | Literal[False] | UnknownClass: ...
    def retain_biproduct_operations(self, biproduct: Callable[[object, object], object], zero_morphism: Callable[[object, object], object]) -> None: ...
    def retain_colimit_construction(self, shape: Category, construction: Callable[[Functor], _ObjectRole]) -> None: ...
    def biproduct(self, first: _ObjectRole, second: _ObjectRole) -> _ObjectRole: ...
    def zero_morphism(self, source: _ObjectRole, target: _ObjectRole) -> _MorphismRole: ...
    def exponential(self, exponent: _ObjectRole, base: _ObjectRole) -> _ObjectRole: ...
    def name(self) -> str: ...
    def narrowing_base(self) -> Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]: ...
    def narrowing_roots(self) -> tuple[Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole], ...]: ...
    def intersection(
        self, roots: tuple[Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole], ...]
    ) -> Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]: ...
    def closed_roots(
        self, roots: tuple[Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole], ...]
    ) -> tuple[Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole], ...]: ...
    def property_subcategory(
        self, property_category: Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]
    ) -> Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]: ...
    def retain_intersection(self, roots: tuple[Category, ...], intersection: Category) -> None: ...
    def __getattr__(self, name: str) -> Callable[..., Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]]: ...
    def narrowing_type(self) -> type[Category[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]]: ...

_CategoryDeclaration_MorphismData = _typing.ParamSpec("_CategoryDeclaration_MorphismData")
_CategoryDeclaration_TwoMorphismData = _typing.ParamSpec("_CategoryDeclaration_TwoMorphismData")
_CategoryDeclaration_ObjectRole = _typing.TypeVar("_CategoryDeclaration_ObjectRole", default="CategoryOfCategories.ElementType")
_CategoryDeclaration_ElementRole = _typing.TypeVar("_CategoryDeclaration_ElementRole", default="CategoryOfCategories.ElementType")
_CategoryDeclaration_MorphismRole = _typing.TypeVar("_CategoryDeclaration_MorphismRole", default="MorphismCategory.ObjectType")
Category = CategoryDeclaration[
    _CategoryDeclaration_MorphismData,
    _CategoryDeclaration_TwoMorphismData,
    _CategoryDeclaration_ObjectRole,
    _CategoryDeclaration_ElementRole,
    _CategoryDeclaration_MorphismRole,
]
type LiftRule = Callable[[MorphismCategory.ObjectType, CategoryOfCategories.ElementType], MorphismCategory.ObjectType]

@dataclass(frozen=True, eq=False, slots=True)
class FunctorData:
    on_object: OnObject
    on_morphism: OnMorphism

class _StaticRoles_CategoryOfCategories:
    class ElementType:
        def parent(self) -> CategoryOfCategories.ElementType: ...
        def defining_morphism(self) -> MorphismCategory.ObjectType: ...
        def category(self) -> Category: ...
        def __eq__(self, candidate: EqualityInput) -> Predicate: ...
        def __ne__(self, candidate: EqualityInput) -> Proposition: ...
        def __hash__(self) -> int: ...
        def __mul__(self, other: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
        def __add__(self, other: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
        def __matmul__(self, other: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
        def __pow__(self, exponent: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
        def diagram(self) -> Functor: ...
        def index_category(self) -> Category: ...
        def projection(self, index: CategoryOfCategories.ElementType | int) -> MorphismCategory.ObjectType: ...
        def universal_morphism(self, candidate: NaturalTransformation) -> MorphismCategory.ObjectType: ...

    class MorphismType[
        DomainCategory: "Category[..., ...]" = "Category[..., ...]",
        CodomainCategory: "Category[..., ...]" = "Category[..., ...]",
        DomainObject: "CategoryOfCategories.ElementType" = "CategoryOfCategories.ElementType",
        DomainElement: "CategoryOfCategories.ElementType" = "CategoryOfCategories.ElementType",
        DomainMorphism: "MorphismCategory.ObjectType" = "MorphismCategory.ObjectType",
        CodomainObject: "CategoryOfCategories.ElementType" = "CategoryOfCategories.ElementType",
        CodomainElement: "CategoryOfCategories.ElementType" = "CategoryOfCategories.ElementType",
        CodomainMorphism: "MorphismCategory.ObjectType" = "MorphismCategory.ObjectType",
    ](sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def __init__(self, data: FunctorData) -> None: ...
        def on_object(self, member_object: DomainObject) -> CodomainObject: ...
        def on_morphism(self, morphism: DomainMorphism) -> CodomainMorphism: ...
        def on_element(self, element: DomainElement) -> CodomainElement: ...
        def __call__(self, value: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
        def inverse_image(self, subcategory: Category) -> Category: ...
        def base_change(self, defining_functor: Functor) -> Functor: ...
        def restrict(self, source: Category, target: Category) -> Functor: ...
        def op(self) -> Functor: ...
        def Fiber(self, member_object: CategoryOfCategories.ElementType) -> Category: ...
        def with_limit_lifting(self, shape: Category | Functor, on_apex: LimitApexLift, on_morphism: LimitMorphismLift) -> Functor: ...
        def limit_lifting(self, shape: Category) -> tuple[LimitApexLift, LimitMorphismLift] | None: ...
        def retain_cartesian_lifts(self, rule: LiftRule) -> None: ...
        def retain_cocartesian_lifts(self, rule: LiftRule) -> None: ...
        def cartesian_lift(self, morphism: MorphismCategory.ObjectType, member_object: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
        def cocartesian_lift(self, morphism: MorphismCategory.ObjectType, member_object: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
        def domain(self) -> DomainCategory: ...
        def codomain(self) -> CodomainCategory: ...

class CategoryOfCategories(
    _StaticRoles_CategoryOfCategories,
    CategoryDeclaration[
        [OnObject, OnMorphism], [Assignment], Category[..., ...], _StaticRoles_CategoryOfCategories.ElementType, _StaticRoles_CategoryOfCategories.MorphismType
    ],
):
    ObjectType = CategoryDeclaration[_CategoryDeclaration_MorphismData, _CategoryDeclaration_TwoMorphismData]
    Inhabited: Incomplete
    Empty: Incomplete
    Concrete: Incomplete

    def __init__(self) -> None: ...
    def declare(self, name: str) -> Category: ...
    def declare_family(self, name: str, domain: Category) -> CategoryFamily: ...
    def declarations(self) -> dict[str, Category | CategoryFamily]: ...
    def open_declaration(self, declared: Category | CategoryFamily) -> str | None: ...
    def implementation(self, name: str) -> type[Category] | None: ...
    def implement(self, implementation: type[Category]) -> None: ...
    def morphism_category_type(self) -> type[FunctorsCategory]: ...
    def construct_morphism(
        self, domain: CategoryOfCategories.ObjectType, codomain: CategoryOfCategories.ObjectType, on_object: OnObject, on_morphism: OnMorphism
    ) -> CategoryOfCategories.MorphismType: ...
    def construct_identity(self, category: CategoryOfCategories.ObjectType) -> CategoryOfCategories.MorphismType: ...
    def composite(self, second: CategoryOfCategories.MorphismType, first: CategoryOfCategories.MorphismType) -> CategoryOfCategories.MorphismType: ...
    def construct_two_morphism(
        self,
        source: CategoryOfCategories.ElementType,
        target: CategoryOfCategories.ElementType,
        assignment: Assignment,
        source_functor: Functor | None = None,
        target_functor: Functor | None = None,
    ) -> NaturalTransformation: ...
    def identity_two_morphism(self, member_object: CategoryOfCategories.ElementType) -> NaturalTransformation: ...
    def compose_two_morphisms(self, second: NaturalTransformation, first: NaturalTransformation) -> NaturalTransformation: ...
    def whisker_left(self, functor: Functor, transformation: NaturalTransformation) -> NaturalTransformation: ...
    def whisker_right(self, transformation: NaturalTransformation, functor: Functor) -> NaturalTransformation: ...
    def horizontal_composite(self, second: NaturalTransformation, first: NaturalTransformation) -> NaturalTransformation: ...
    def limit_construction(self, shape: Category) -> Callable[[CategoryOfCategories.MorphismType], CategoryOfCategories.ObjectType]: ...
    def exponential(self, exponent: CategoryOfCategories.ObjectType, base: CategoryOfCategories.ObjectType) -> CategoryOfCategories.ObjectType: ...
    def Comma(self, first: Functor, second: Functor) -> CommaCategory: ...
    def postcompose(self, functor: Functor, diagram: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
    def exponential_on_morphism(self, exponent: Category, functor: Functor) -> Functor: ...
    def __call__(
        self, labels: tuple[Hashable, ...], generators: tuple[tuple[str, Hashable, Hashable], ...], relations: tuple[tuple[tuple[str, ...], tuple[str, ...]], ...]
    ) -> FinitePresentedCategory: ...
    def Initial(self) -> FinitePresentedCategory: ...
    def Terminal(self) -> FinitePresentedCategory: ...
    @overload
    def Point(self) -> CategoryOfCategories.MorphismType: ...
    @overload
    def Point(self, member: CategoryOfCategories.ElementType) -> PointCategory: ...
    def Simplex(self, dimension: int | Integer) -> FinitePresentedCategory: ...
    def Boundary(self, dimension: int | Integer) -> FinitePresentedCategory: ...
    def Horn(self, dimension: int, omitted_face: int) -> FinitePresentedCategory: ...
    def WalkingIsomorphism(self) -> FinitePresentedCategory: ...
    def WalkingSpan(self) -> FinitePresentedCategory: ...
    def WalkingCospan(self) -> FinitePresentedCategory: ...
    def WalkingParallelPair(self) -> FinitePresentedCategory: ...
    def element_from_defining_morphism(self, defining_functor: Functor) -> CategoryOfCategories.ElementType: ...

def Cat() -> CategoryOfCategories: ...

concrete_category: Predicate

def retain_composite_factors(composite: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> None: ...
def composite_factors(composite: MorphismCategory.ObjectType) -> tuple[MorphismCategory.ObjectType, MorphismCategory.ObjectType]: ...
def is_composite(morphism: MorphismCategory.ObjectType) -> bool: ...
def bootstrap() -> None: ...
