from sage_categories.cat.functors import Fun_MorphismType as Fun_MorphismType
from sage_categories.cat.functors import FunctorDeclaration as FunctorDeclaration
import sage_categories.kernel.compiler as compiler
from collections.abc import Callable, Hashable as Hashable
from sage.misc.cachefunc import cached_method
from sage_categories.cat.canonical import FinitePresentedCategory as FinitePresentedCategory
from sage_categories.cat.equality import equality_predicate as equality_predicate
from sage_categories.cat.functors import Functor as Functor, FunctorsCategory as FunctorsCategory, NaturalTransformation as NaturalTransformation
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.points import PointCategory as PointCategory
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass
from sage_categories.kernel.predicates import Predicate as Predicate, Proposition as Proposition, ask as ask
from sage_categories.kernel.refinement import is_placed as is_placed, is_subcategory as is_subcategory, traces_placement as traces_placement
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, Role as Role, role_of as role_of
from typing import Any, Literal, overload

type OnObject = Callable[[ObjectOfCategory], ObjectOfCategory]
type OnMorphism = Callable[[MorphismOfCategory], MorphismOfCategory]
type Assignment = Callable[[ObjectOfCategory], MorphismOfCategory]
member: Predicate

class CategoryDeclaration[**MorphismData, **TwoMorphismData](ObjectOfCategory):
    def __init__(self, data: None = None) -> None: ...
    def __mul__(self, other: Category) -> Category: ...
    def __add__(self, other: Category) -> Category: ...
    def __pow__(self, exponent: Category) -> Category: ...
    def universe(self) -> CategoryOfCategories: ...
    def ordinal(self) -> int: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def separating_family(self) -> tuple[ObjectOfCategory, ...]: ...
    def structural_image(self, value: CategoryPoint) -> CategoryPoint: ...
    def retain_datum[Datum](self, value: CategoryPoint, datum: Datum) -> None: ...
    def retained_datum[Datum](self, value: CategoryPoint) -> Datum: ...
    def local_role_class(self, role: Role) -> type[CategoryPoint]: ...
    def role_class(self, role: Role) -> type[CategoryPoint]: ...
    def role_source(self, role: Role) -> tuple[Category[MorphismData, TwoMorphismData], Role]: ...
    def catalogues(self) -> dict[Role, dict[str, compiler.Entry]]: ...
    def select_functors(self, functors: tuple[Functor, ...]) -> None: ...
    def selected_functors(self) -> tuple[Functor, ...]: ...
    def has_ambient(self) -> bool: ...
    def has_full_ambient(self) -> bool: ...
    def ambient(self) -> Category[MorphismData, TwoMorphismData]: ...
    def hom_inhabited(self, hom_category: Category) -> Decision: ...
    def equality(self) -> Predicate: ...
    def membership_proposition(self, candidate: CategoryPoint) -> Proposition: ...
    def __contains__(self, candidate: Any) -> bool: ...
    @overload
    def morphism_category(self, level: Literal[0]) -> Category[MorphismData, TwoMorphismData]: ...
    @overload
    def morphism_category(self, level: Literal[1]) -> MorphismCategory[MorphismData, TwoMorphismData]: ...
    @overload
    def morphism_category(self, level: Literal[2]) -> MorphismCategory[TwoMorphismData, []]: ...
    @overload
    def morphism_category(self, level: int) -> MorphismCategory[[], []]: ...
    def morphism_category_type(self) -> type[MorphismCategory[MorphismData, TwoMorphismData]]: ...
    def two_morphism_type(self) -> type[MorphismOfCategory]: ...
    def base_category(self) -> Category: ...
    def identity_morphism(self, member_object: ObjectOfCategory) -> MorphismOfCategory: ...
    def retain_inverses(self, forward: MorphismOfCategory, backward: MorphismOfCategory) -> None: ...
    def compose_morphisms(self, second: MorphismOfCategory, first: MorphismOfCategory) -> MorphismOfCategory: ...
    def inverse_morphism(self, morphism: MorphismOfCategory) -> MorphismOfCategory: ...
    def element_from_defining_morphism(self, defining_morphism: MorphismOfCategory) -> CategoryPoint: ...
    def construct_morphism(self, domain: ObjectOfCategory, codomain: ObjectOfCategory, *args: MorphismData.args, **kwargs: MorphismData.kwargs) -> MorphismOfCategory: ...
    def construct_identity(self, member_object: ObjectOfCategory) -> MorphismOfCategory: ...
    def composite(self, second: MorphismOfCategory, first: MorphismOfCategory) -> MorphismOfCategory: ...
    def identity_two_morphism(self, morphism: MorphismOfCategory) -> MorphismOfCategory: ...
    def compose_two_morphisms(self, second: MorphismOfCategory, first: MorphismOfCategory) -> MorphismOfCategory: ...
    def construct_two_morphism(self, first: MorphismOfCategory, second: MorphismOfCategory, *args: TwoMorphismData.args, **kwargs: TwoMorphismData.kwargs) -> MorphismOfCategory: ...
    def point_functor(self, member_object: ObjectOfCategory) -> Functor: ...
    def arrow_functor(self, morphism: MorphismOfCategory) -> Functor: ...
    def represented_functor(self) -> Functor: ...
    @cached_method
    def Products(self) -> Category: ...
    @cached_method
    def Coproducts(self) -> Category: ...
    def Limits(self, shape: Category) -> Category: ...
    def Colimits(self, shape: Category) -> Category: ...
    def Pullbacks(self) -> Category: ...
    def Pushouts(self) -> Category: ...
    def Equalizers(self) -> Category: ...
    def Coequalizers(self) -> Category: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], ObjectOfCategory]: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], ObjectOfCategory]: ...
    def SliceOver(self, member_object: ObjectOfCategory) -> Category: ...
    def CosliceUnder(self, member_object: ObjectOfCategory) -> Category: ...
    @cached_method
    def Subobjects(self) -> Category: ...
    @cached_method
    def Superobjects(self) -> Category: ...
    @cached_method
    def CoveringObjects(self) -> Category: ...
    @cached_method
    def CoveredObjects(self) -> Category: ...
    def WideSubcategory(self, morphism_property: Category) -> Category: ...
    def Core(self) -> Category: ...
    def object_set(self) -> ObjectOfCategory: ...
    def object_at(self, point: ElementOfObject) -> ObjectOfCategory: ...
    def object_point(self, member_object: ObjectOfCategory) -> ElementOfObject: ...
    def morphism_set(self) -> ObjectOfCategory | UnknownClass: ...
    def morphism_at(self, point: ElementOfObject) -> MorphismOfCategory: ...
    def generating_morphisms(self) -> tuple[MorphismOfCategory, ...] | UnknownClass: ...
    def biproduct(self, first: ObjectOfCategory, second: ObjectOfCategory) -> ObjectOfCategory: ...
    def exponential(self, exponent: ObjectOfCategory, base: ObjectOfCategory) -> ObjectOfCategory: ...
    def name(self) -> str: ...
    def narrowing_base(self) -> Category[MorphismData, TwoMorphismData]: ...
    def narrowing_roots(self) -> tuple[Category[MorphismData, TwoMorphismData], ...]: ...
    def intersection(self, roots: tuple[Category[MorphismData, TwoMorphismData], ...]) -> Category[MorphismData, TwoMorphismData]: ...
    def property_subcategory(self, property_category: Category[MorphismData, TwoMorphismData]) -> Category[MorphismData, TwoMorphismData]: ...
    def narrowing_type(self) -> type[Category[MorphismData, TwoMorphismData]]: ...
Category = CategoryDeclaration

class CategoryOfCategories(CategoryDeclaration[[OnObject, OnMorphism], [Assignment]]):
    def __init__(self) -> None: ...
    def local_role_class(self, role: Role) -> type[CategoryPoint]: ...
    def morphism_category_type(self) -> type[FunctorsCategory]: ...
    def two_morphism_type(self) -> type[MorphismOfCategory]: ...
    def construct_morphism(self, domain: Category, codomain: Category, on_object: OnObject, on_morphism: OnMorphism) -> Functor: ...
    def construct_identity(self, category: Category) -> Functor: ...
    def composite(self, second: Functor, first: Functor) -> Functor: ...
    def construct_two_morphism(self, source: CategoryPoint, target: CategoryPoint, assignment: Assignment) -> NaturalTransformation: ...
    def identity_two_morphism(self, member_object: CategoryPoint) -> NaturalTransformation: ...
    def compose_two_morphisms(self, second: NaturalTransformation, first: NaturalTransformation) -> NaturalTransformation: ...
    def whisker_left(self, functor: Functor, transformation: NaturalTransformation) -> NaturalTransformation: ...
    def whisker_right(self, transformation: NaturalTransformation, functor: Functor) -> NaturalTransformation: ...
    def horizontal_composite(self, second: NaturalTransformation, first: NaturalTransformation) -> NaturalTransformation: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], ObjectOfCategory]: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], ObjectOfCategory]: ...
    def exponential(self, exponent: Category, base: Category) -> Category: ...
    def postcompose(self, functor: Functor, diagram: CategoryPoint) -> CategoryPoint: ...
    def exponential_on_morphism(self, exponent: Category, functor: Functor) -> Functor: ...
    def __call__(self, labels: tuple[Hashable, ...], generators: tuple[tuple[str, Hashable, Hashable], ...], relations: tuple[tuple[tuple[str, ...], tuple[str, ...]], ...]) -> FinitePresentedCategory: ...
    def Empty(self) -> FinitePresentedCategory: ...
    def Terminal(self) -> FinitePresentedCategory: ...
    def Point(self, member: CategoryPoint, targets: tuple[Category, ...] = ()) -> PointCategory: ...
    def retained_point(self, member: CategoryPoint) -> PointCategory | None: ...
    def Simplex(self, dimension: int) -> FinitePresentedCategory: ...
    def Boundary(self, dimension: int) -> FinitePresentedCategory: ...
    def Horn(self, dimension: int, omitted_face: int) -> FinitePresentedCategory: ...
    def WalkingIsomorphism(self) -> FinitePresentedCategory: ...
    def WalkingParallelPair(self) -> FinitePresentedCategory: ...
    def separating_family(self) -> tuple[FinitePresentedCategory, ...]: ...
    def element_from_defining_morphism(self, defining_functor: Functor) -> CategoryPoint: ...

def bootstrap() -> None: ...
def Cat() -> CategoryOfCategories: ...
