from dataclasses import dataclass

import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import NaturalTransformation as NaturalTransformation
from sage_categories.cat.morphisms import Mor as Mor
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import ask as ask
from sage_categories.cat.predicates import register_handler as register_handler
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.sage_runtime import cached_function as cached_function
from sage_categories.kernel.sage_runtime import cached_method as cached_method

__all__ = ["CommaCategory", "CommaSpecialization", "comma_objects"]

@dataclass(frozen=True, eq=False)
class CommaObject:
    first: CategoryOfCategories.ElementType
    second: CategoryOfCategories.ElementType
    arrow: MorphismCategory.ObjectType

@dataclass(frozen=True, eq=False)
class CommaMorphism:
    first: MorphismCategory.ObjectType
    second: MorphismCategory.ObjectType

class _StaticRoles_CommaCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def __init__(self, data: CommaObject) -> None: ...
        def first(self) -> CategoryOfCategories.ElementType: ...
        def second(self) -> CategoryOfCategories.ElementType: ...
        def arrow(self) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def __init__(self, data: CommaMorphism) -> None: ...
        def first(self) -> MorphismCategory.ObjectType: ...
        def second(self) -> MorphismCategory.ObjectType: ...
        def domain(self) -> CommaCategory.ObjectType: ...
        def codomain(self) -> CommaCategory.ObjectType: ...

class CommaCategory[
    ObjectRole = _StaticRoles_CommaCategory.ObjectType,
    ElementRole = _StaticRoles_CommaCategory.ElementType,
    MorphismRole = _StaticRoles_CommaCategory.MorphismType,
](_StaticRoles_CommaCategory, Category[[MorphismCategory.ObjectType, MorphismCategory.ObjectType], [], ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, first: Functor, second: Functor) -> None: ...
    def comma_functors(self) -> tuple[Functor, Functor]: ...
    def from_arrow(self, first: CategoryOfCategories.ElementType, second: CategoryOfCategories.ElementType, arrow: MorphismCategory.ObjectType) -> ObjectRole: ...
    def morphism_from_pair(self, source: ObjectRole, target: ObjectRole, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> MorphismRole: ...
    def construct_morphism(self, source: ObjectRole, target: ObjectRole, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> MorphismRole: ...
    def construct_identity(self, value: ObjectRole) -> MorphismRole: ...
    def composite(self, second: MorphismRole, first: MorphismRole) -> MorphismRole: ...
    @cached_method
    def first_projection(self) -> Functor: ...
    @cached_method
    def second_projection(self) -> Functor: ...
    @cached_method
    def defining_transformation(self) -> NaturalTransformation: ...
    @cached_method
    def arrow_projection(self) -> Functor: ...
    @cached_method
    def pair_projection(self) -> Functor: ...

def comma_objects(first: Functor, second: Functor) -> CommaCategory: ...

class _StaticRoles_CommaSpecialization(_StaticRoles_CommaCategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> CommaSpecialization.ObjectType: ...
        def codomain(self) -> CommaSpecialization.ObjectType: ...

class CommaSpecialization[
    ObjectRole = _StaticRoles_CommaSpecialization.ObjectType,
    ElementRole = _StaticRoles_CommaSpecialization.ElementType,
    MorphismRole = _StaticRoles_CommaSpecialization.MorphismType,
](_StaticRoles_CommaSpecialization, CommaCategory[ObjectRole, ElementRole, MorphismRole]):
    def structure_functors(self) -> tuple[Functor, ...]: ...
