from collections.abc import Callable, Hashable

import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.cat.properties
import sage_categories.kernel.roles
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.category import member as member
from sage_categories.cat.cones import ConeCategory as ConeCategory
from sage_categories.cat.cones import LimitConesCategory as LimitConesCategory
from sage_categories.cat.cones import cocone as cocone
from sage_categories.cat.cones import cocone_apex as cocone_apex
from sage_categories.cat.cones import colimit_cocones as colimit_cocones
from sage_categories.cat.cones import cone as cone
from sage_categories.cat.cones import cone_apex as cone_apex
from sage_categories.cat.cones import cones as cones
from sage_categories.cat.cones import limit_cones as limit_cones
from sage_categories.cat.cones import vertex_of as vertex_of
from sage_categories.cat.diagrams import from_sequence as from_sequence
from sage_categories.cat.dual_functor_categories import dual_functor_category_equivalence as dual_functor_category_equivalence
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import NaturalTransformation as NaturalTransformation
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import Unknown as Unknown
from sage_categories.cat.predicates import ask as ask
from sage_categories.cat.properties import PredicateSubcategory as PredicateSubcategory
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.cat.universal_arrows import RightUniversalArrows as RightUniversalArrows
from sage_categories.kernel.refinement import is_placed as is_placed
from sage_categories.kernel.refinement import is_subcategory as is_subcategory
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.refinement import traces_placement as traces_placement
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.sage_runtime import MonoDict as MonoDict
from sage_categories.kernel.sage_runtime import TripleDict as TripleDict
from sage_categories.kernel.sage_runtime import cached_function as cached_function

__all__ = [
    "ApexCategory",
    "ColimitsCategory",
    "CoproductsCategory",
    "LimitApexLift",
    "LimitMorphismLift",
    "LimitsCategory",
    "ProductsCategory",
    "cocone",
    "cocone_apex",
    "cone",
    "cone_apex",
    "lift_limit",
    "presenting_family",
    "vertex_of",
]
type Mediator = Callable[[NaturalTransformation], MorphismCategory.ObjectType]
type Construction = Callable[[Functor], "CategoryOfCategories.ElementType"]
type UniversalPresentation = LimitConesCategory.ObjectType

def presenting_family(constructed: CategoryOfCategories.ElementType) -> Category: ...

class _StaticRoles_ApexCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        ...

        def domain(self) -> ApexCategory.ObjectType: ...
        def codomain(self) -> ApexCategory.ObjectType: ...

class ApexCategory[
    **MorphismData,
    **TwoMorphismData,
    _ObjectRole = _StaticRoles_ApexCategory.ObjectType,
    _ElementRole = _StaticRoles_ApexCategory.ElementType,
    _MorphismRole = _StaticRoles_ApexCategory.MorphismType,
](_StaticRoles_ApexCategory, PropertySubcategory[MorphismData, TwoMorphismData, _ObjectRole, _ElementRole, _MorphismRole]):
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], name: str, full_subcategory_of: tuple[Category, ...]) -> None: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def accepts(self, diagram: Functor, shape: Category) -> None: ...
    def lowered(self, diagram: Functor) -> Functor: ...
    def has_construction(self, diagram: Functor) -> bool: ...
    def chosen_object(self, diagram: Functor) -> CategoryOfCategories.ElementType: ...
    def universal_data(self, diagram: Functor) -> UniversalPresentation: ...
    def presenting_diagrams(self, constructed: CategoryOfCategories.ElementType) -> tuple[Functor, ...]: ...
    def presentation(self, constructed: CategoryOfCategories.ElementType) -> UniversalPresentation: ...
    def chosen(self, diagram: Functor, construction: Construction) -> CategoryOfCategories.ElementType: ...

type LimitApexLift = Callable[[Functor, LimitConesCategory.ObjectType], CategoryOfCategories.ElementType]
type LimitMorphismLift = Callable[[CategoryOfCategories.ElementType, CategoryOfCategories.ElementType, MorphismCategory.ObjectType], MorphismCategory.ObjectType]

def lift_limit(functor: Functor, diagram: Functor, on_apex: LimitApexLift, on_morphism: LimitMorphismLift) -> CategoryOfCategories.ElementType: ...

class _StaticRoles_LimitsCategory(_StaticRoles_ApexCategory):
    class ObjectType(sage_categories.cat.category.CategoryDeclaration): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.MorphismType):
        ...

        def domain(self) -> LimitsCategory.ObjectType: ...
        def codomain(self) -> LimitsCategory.ObjectType: ...

class LimitsCategory(
    _StaticRoles_LimitsCategory,
    ApexCategory[..., ..., _StaticRoles_LimitsCategory.ObjectType, _StaticRoles_LimitsCategory.ElementType, _StaticRoles_LimitsCategory.MorphismType],
):
    def __init__(self, ambient: Category, name: str, full_subcategory_of: tuple[Category, ...], shape: Category) -> None: ...
    def shape(self) -> Category: ...
    def diagrams(self) -> Category: ...
    def __call__(self, diagram: Functor) -> CategoryOfCategories.ElementType: ...
    def with_universal_data(
        self, diagram: Functor, apex: CategoryOfCategories.ElementType, limiting_cone: NaturalTransformation, mediator: Mediator
    ) -> CategoryOfCategories.ElementType: ...
    def with_presentation(self, presentation: LimitConesCategory.ObjectType) -> CategoryOfCategories.ElementType: ...
    def limit_functor(self) -> Functor: ...
    def defining_functor(self) -> Functor: ...
    def factorization(self) -> tuple[Functor, Functor]: ...
    def adjunction(self) -> CategoryOfCategories.ElementType: ...

class _StaticRoles_ProductsCategory(sage_categories.cat.properties._StaticRoles_PredicateSubcategory):
    class ObjectType(sage_categories.cat.category.CategoryDeclaration):
        def product_factors(self) -> Functor: ...
        def cone(self) -> NaturalTransformation: ...
        def product_projection(self, index: CategoryOfCategories.ElementType | Hashable) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.MorphismType):
        ...

        def domain(self) -> ProductsCategory.ObjectType: ...
        def codomain(self) -> ProductsCategory.ObjectType: ...

class ProductsCategory(
    _StaticRoles_ProductsCategory,
    PredicateSubcategory[
        [MorphismCategory.ObjectType], [], _StaticRoles_ProductsCategory.ObjectType, _StaticRoles_ProductsCategory.ElementType, _StaticRoles_ProductsCategory.MorphismType
    ],
):
    def __init__(self, ambient: Category, name: str, full_subcategory_of: tuple[Category, ...]) -> None: ...
    def retain_full_image(self, family: Category) -> None: ...
    def full_images(self) -> tuple[Category, ...]: ...
    def presenting_family(self, apex: CategoryOfCategories.ElementType) -> Category: ...
    def diagrams(self, shape: Category) -> Category: ...
    def __call__(
        self, family: CategoryOfCategories.ElementType | tuple[CategoryOfCategories.ElementType, ...], *factors: CategoryOfCategories.ElementType
    ) -> CategoryOfCategories.ElementType: ...
    def with_universal_data(
        self, diagram: Functor, apex: CategoryOfCategories.ElementType, limiting_cone: NaturalTransformation, mediator: Mediator
    ) -> CategoryOfCategories.ElementType: ...

class _StaticRoles_ColimitsCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def cocone(self) -> NaturalTransformation: ...
        def injection(self, index: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        ...

        def domain(self) -> ColimitsCategory.ObjectType: ...
        def codomain(self) -> ColimitsCategory.ObjectType: ...

class ColimitsCategory(
    _StaticRoles_ColimitsCategory,
    PropertySubcategory[
        [MorphismCategory.ObjectType], [], _StaticRoles_ColimitsCategory.ObjectType, _StaticRoles_ColimitsCategory.ElementType, _StaticRoles_ColimitsCategory.MorphismType
    ],
):
    def __init__(self, ambient: Category, name: str, full_subcategory_of: tuple[Category, ...], shape: Category) -> None: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def shape(self) -> Category: ...
    def diagrams(self) -> Category: ...
    def accepts(self, diagram: Functor) -> None: ...
    def lowered(self, diagram: Functor) -> Functor: ...
    def has_construction(self, diagram: Functor) -> bool: ...
    def chosen_object(self, diagram: Functor) -> CategoryOfCategories.ElementType: ...
    def universal_data(self, diagram: Functor) -> UniversalPresentation: ...
    def presenting_diagrams(self, constructed: CategoryOfCategories.ElementType) -> tuple[Functor, ...]: ...
    def presenting_diagram(self, constructed: CategoryOfCategories.ElementType) -> Functor: ...
    def presentation(self, constructed: CategoryOfCategories.ElementType) -> UniversalPresentation: ...
    def __call__(self, diagram: Functor) -> CategoryOfCategories.ElementType: ...
    def with_universal_data(
        self, diagram: Functor, apex: CategoryOfCategories.ElementType, colimiting_cocone: NaturalTransformation, mediator: Mediator
    ) -> CategoryOfCategories.ElementType: ...
    def colimit_functor(self) -> Functor: ...
    def defining_functor(self) -> Functor: ...

class _StaticRoles_CoproductsCategory(sage_categories.cat.properties._StaticRoles_PredicateSubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def coproduct_summands(self) -> Functor: ...
        def coproduct_injection(self, index: CategoryOfCategories.ElementType | Hashable) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        ...

        def domain(self) -> CoproductsCategory.ObjectType: ...
        def codomain(self) -> CoproductsCategory.ObjectType: ...

class CoproductsCategory(
    _StaticRoles_CoproductsCategory,
    PredicateSubcategory[
        [MorphismCategory.ObjectType], [], _StaticRoles_CoproductsCategory.ObjectType, _StaticRoles_CoproductsCategory.ElementType, _StaticRoles_CoproductsCategory.MorphismType
    ],
):
    def __init__(self, ambient: Category, name: str, full_subcategory_of: tuple[Category, ...]) -> None: ...
    def retain_full_image(self, family: Category) -> None: ...
    def full_images(self) -> tuple[Category, ...]: ...
    def presenting_family(self, apex: CategoryOfCategories.ElementType) -> ColimitsCategory: ...
    def diagrams(self, shape: Category) -> Category: ...
    def __call__(
        self, family: CategoryOfCategories.ElementType | tuple[CategoryOfCategories.ElementType, ...], *summands: CategoryOfCategories.ElementType
    ) -> CategoryOfCategories.ElementType: ...
    def with_universal_data(
        self, diagram: Functor, apex: CategoryOfCategories.ElementType, colimiting_cocone: NaturalTransformation, mediator: Mediator
    ) -> CategoryOfCategories.ElementType: ...

def constructed_data(family: Category, diagram: Functor) -> UniversalPresentation: ...
