from sage_categories.kernel.roles import ElementOfObject as ElementOfObject
from sage_categories.cat.category import Category as Category
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, CategoryPointKernel as CategoryPointKernel, ObjectOfCategory as ObjectOfCategory

class CategoryPointDeclaration(ElementOfObject):
    def __mul__(self, other: ObjectOfCategory) -> ObjectOfCategory: ...
    def __add__(self, other: ObjectOfCategory) -> ObjectOfCategory: ...
    def __matmul__(self, other: ObjectOfCategory) -> ObjectOfCategory: ...
    def __pow__(self, exponent: ObjectOfCategory) -> ObjectOfCategory: ...
