from sage_categories.cat.category import CategoryDeclaration as CategoryDeclaration
from sage_categories.kernel.roles import ElementOfObject as ElementOfObject
from _typeshed import Incomplete
from collections.abc import Callable
from dataclasses import dataclass
from sage_categories.cat.category import Assignment as Assignment, Category as Category, CategoryOfCategories as CategoryOfCategories, OnMorphism as OnMorphism, OnObject as OnObject
from sage_categories.cat.morphisms import FixedEndpointCategory as FixedEndpointCategory, MorphismCategory as MorphismCategory, endpoints as endpoints
from sage_categories.cat.properties import FixedEndpointProperty as FixedEndpointProperty, PropertySubcategory as PropertySubcategory
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, Proposition as Proposition, ask as ask
from sage_categories.kernel.refinement import is_placed as is_placed, is_subcategory as is_subcategory, refine as refine, traces_placement as traces_placement
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, Role as Role, role_of as role_of
from sage_categories.sets.elements import SetElement as SetElement
from sage_categories.sets.objects import SetObject as SetObject

def identity_on_values(value: CategoryPoint) -> CategoryPoint: ...
def diagram_of(value: CategoryPoint) -> Functor: ...
type LiftRule = Callable[[MorphismOfCategory, CategoryPoint], MorphismOfCategory]

@dataclass(frozen=True, eq=False, slots=True)
class FunctorData:
    on_object: OnObject | None
    on_morphism: OnMorphism | None

class FunctorDeclaration(MorphismOfCategory):
    def __init__(self, data: FunctorData) -> None: ...
    def on_object(self, member_object: ObjectOfCategory) -> ObjectOfCategory: ...
    def on_morphism(self, morphism: MorphismOfCategory) -> MorphismOfCategory: ...
    def __call__(self, value: CategoryPoint) -> CategoryPoint: ...
    def retain_factors(self, first: Functor, second: Functor) -> None: ...
    def factors(self) -> tuple[Functor, Functor]: ...
    def retain_cartesian_lifts(self, rule: LiftRule) -> None: ...
    def retain_cocartesian_lifts(self, rule: LiftRule) -> None: ...
    def cartesian_lift(self, morphism: MorphismOfCategory, member_object: CategoryPoint) -> MorphismOfCategory: ...
    def cocartesian_lift(self, morphism: MorphismOfCategory, member_object: CategoryPoint) -> MorphismOfCategory: ...
    def is_full(self) -> AppliedPredicate: ...
    def is_faithful(self) -> AppliedPredicate: ...
    def is_fully_faithful(self) -> AppliedPredicate: ...
    def is_essentially_surjective(self) -> AppliedPredicate: ...
    def is_equivalence(self) -> AppliedPredicate: ...

@dataclass(frozen=True, eq=False, slots=True)
class NaturalTransformationData:
    assignment: Assignment

class NaturalTransformationDeclaration(MorphismOfCategory):
    def __init__(self, data: NaturalTransformationData) -> None: ...
    def source_functor(self) -> Functor: ...
    def target_functor(self) -> Functor: ...
    def component(self, member_object: ObjectOfCategory) -> MorphismOfCategory: ...
    def whisker_left(self, functor: Functor) -> NaturalTransformation: ...
    def whisker_right(self, functor: Functor) -> NaturalTransformation: ...
    def horizontal(self, transformation: NaturalTransformation) -> NaturalTransformation: ...
Functor = FunctorDeclaration
NaturalTransformation = Fun_MorphismType
Cat: Incomplete

class FunctorProperties:
    def Full(self) -> Category: ...
    def Faithful(self) -> Category: ...
    def FullyFaithful(self) -> Category: ...
    def EssentiallySurjective(self) -> Category: ...
    def Equivalences(self) -> Category: ...
    def PreservesLimits(self, shape: Category) -> Category: ...
    def CreatesLimits(self, shape: Category) -> Category: ...
    def Isofibrations(self) -> Category: ...
    def Monomorphisms(self) -> Category: ...

class FunctorProperty(FunctorProperties, FixedEndpointProperty[[OnObject, OnMorphism], [Assignment]]):
    def __call__(self, *args: OnObject | OnMorphism, **kwargs: OnObject | OnMorphism) -> Functor: ...

denotes_diagram: Predicate
denotes_functor: Predicate

class FunctorCategory(FunctorProperties, FixedEndpointCategory[[OnObject, OnMorphism], [Assignment]]):
    def __init__(self, morphisms: MorphismCategory, domain: Category, codomain: Category) -> None: ...
    def membership_proposition(self, candidate: CategoryPoint) -> Proposition: ...
    def diagram(self, value: CategoryPoint) -> Functor: ...
    def construct_morphism(self, source: CategoryPoint, target: CategoryPoint, assignment: Assignment) -> NaturalTransformation: ...
    def evaluation(self, vertex: ObjectOfCategory) -> Functor: ...
    def constant(self, value: ObjectOfCategory) -> Functor: ...
    def has_constant_value(self, diagram: Functor) -> bool: ...
    def constant_value(self, diagram: Functor) -> ObjectOfCategory: ...
    def from_object_rule(self, rule: OnObject) -> Functor: ...
    def PreservesLimits(self, shape: Category) -> Category: ...
    def CreatesLimits(self, shape: Category) -> Category: ...
    def object_set(self) -> SetObject: ...
    def object_at(self, point: SetElement) -> MorphismOfCategory: ...
    def _chosen_morphism_set(self) -> SetObject | UnknownClass: ...
    def morphism_at(self, point: SetElement) -> NaturalTransformation: ...
    def narrowing_type(self) -> type[FunctorProperty]: ...

class FunctorsCategory(MorphismCategory[[OnObject, OnMorphism], [Assignment]]):
    @property
    def ObjectType(self) -> type[FunctorDeclaration]: ...
    @property
    def ElementType(self) -> type[Fun_ElementType]: ...
    @property
    def MorphismType(self) -> type[Fun_MorphismType]: ...
    def __init__(self, base: CategoryOfCategories) -> None: ...
    def fixed_endpoint_type(self) -> type[FunctorCategory]: ...
    def __call__(self, shape: ObjectOfCategory, target: ObjectOfCategory | Functor) -> FunctorCategory | Functor: ...
    def membership_proposition(self, candidate: CategoryPoint) -> Proposition: ...
    def Full(self) -> Category: ...
    def Faithful(self) -> Category: ...
    def FullyFaithful(self) -> Category: ...
    def EssentiallySurjective(self) -> Category: ...
    def Equivalences(self) -> Category: ...
    def PreservesLimits(self, shape: Category) -> Category: ...
    def CreatesLimits(self, shape: Category) -> Category: ...
    def Isofibrations(self) -> Category: ...
    def Monomorphisms(self) -> Category: ...
    def declares_subcategory(self, functor: Functor) -> bool: ...
    def subcategory_monomorphism(self, source: Category, target: Category) -> Functor: ...
    def full_subcategory_monomorphism(self, source: Category, target: Category) -> Functor: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], ObjectOfCategory]: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], ObjectOfCategory]: ...

Fun: FunctorsCategory

class Fun_ElementType(ElementOfObject):
    ...

class Fun_MorphismType(MorphismOfCategory):
    ...

class Fun_Full_ElementType(Fun_ElementType):
    ...

class Fun_Full_MorphismType(Fun_MorphismType):
    ...

class Fun_Full_ObjectType(FunctorDeclaration):
    ...

class Fun_Faithful_ElementType(Fun_ElementType):
    ...

class Fun_Faithful_MorphismType(Fun_MorphismType):
    ...

class Fun_Faithful_ObjectType(FunctorDeclaration):
    ...

class Fun_EssentiallySurjective_ElementType(Fun_ElementType):
    ...

class Fun_EssentiallySurjective_MorphismType(Fun_MorphismType):
    ...

class Fun_EssentiallySurjective_ObjectType(FunctorDeclaration):
    ...

class Fun_FullyFaithful_ElementType(Fun_Faithful_ElementType, Fun_Full_ElementType, Fun_ElementType):
    ...

class Fun_FullyFaithful_MorphismType(Fun_Faithful_MorphismType, Fun_Full_MorphismType, Fun_MorphismType):
    ...

class Fun_FullyFaithful_ObjectType(Fun_Faithful_ObjectType, Fun_Full_ObjectType, FunctorDeclaration):
    ...

class Fun_Equivalences_ElementType(Fun_FullyFaithful_ElementType, Fun_EssentiallySurjective_ElementType, Fun_ElementType):
    ...

class Fun_Equivalences_MorphismType(Fun_FullyFaithful_MorphismType, Fun_EssentiallySurjective_MorphismType, Fun_MorphismType):
    ...

class Fun_Equivalences_ObjectType(Fun_FullyFaithful_ObjectType, Fun_EssentiallySurjective_ObjectType, FunctorDeclaration):
    ...

class Fun_Isofibrations_ElementType(Fun_ElementType):
    ...

class Fun_Isofibrations_MorphismType(Fun_MorphismType):
    ...

class Fun_Isofibrations_ObjectType(FunctorDeclaration):
    ...

class Fun_Monomorphisms_ElementType(Fun_Faithful_ElementType, Fun_ElementType):
    ...

class Fun_Monomorphisms_MorphismType(Fun_Faithful_MorphismType, Fun_MorphismType):
    ...

class Fun_Monomorphisms_ObjectType(Fun_Faithful_ObjectType, FunctorDeclaration):
    ...
