import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.cat.properties
import sage_categories.kernel.roles
import sage_categories.sets.finite
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Predicate as Predicate
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import register_handler as register_handler
from sage_categories.cat.properties import PredicateSubcategory as PredicateSubcategory
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.sage_runtime import MonoDict as MonoDict
from sage_categories.kernel.sage_runtime import cached_function as cached_function
from sage_categories.kernel.sage_runtime import cached_method as cached_method

__all__ = [
    "EssentialImageCategory",
    "FullImageCategory",
    "StrictImageCategory",
    "full_image",
    "register_full_image",
    "retain_morphism_image",
    "retain_object_image",
    "strict_image",
]

class _StaticRoles_ImageMorphismCategory(sage_categories.cat.morphisms._StaticRoles_MorphismCategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> ImageMorphismCategory.ObjectType: ...
        def codomain(self) -> ImageMorphismCategory.ObjectType: ...

class ImageMorphismCategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_ImageMorphismCategory,
    MorphismCategory[
        MorphismData,
        TwoMorphismData,
        _StaticRoles_ImageMorphismCategory.ObjectType,
        _StaticRoles_ImageMorphismCategory.ElementType,
        _StaticRoles_ImageMorphismCategory.MorphismType,
    ],
):
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...

class _StaticRoles_ImageCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> ImageCategory.ObjectType: ...
        def codomain(self) -> ImageCategory.ObjectType: ...

class ImageCategory[
    **MorphismData,
    **TwoMorphismData,
    ObjectRole = _StaticRoles_ImageCategory.ObjectType,
    ElementRole = _StaticRoles_ImageCategory.ElementType,
    MorphismRole = _StaticRoles_ImageCategory.MorphismType,
](_StaticRoles_ImageCategory, Category[MorphismData, TwoMorphismData, ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, defining_functor: Functor) -> None: ...
    def defining_functor(self) -> Functor: ...
    def target(self) -> Category: ...
    def equality(self) -> Predicate: ...
    def morphism_category_type(self) -> type[ImageMorphismCategory[MorphismData, TwoMorphismData]]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def morphism_membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def object_image(self, source: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
    def morphism_image(self, source: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    @cached_method
    def factor_functor(self) -> Functor: ...
    @cached_method
    def inclusion_functor(self) -> Functor: ...
    def factorization(self) -> tuple[Functor, Functor]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def construct_identity(self, member_object: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def composite(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...

class _StaticRoles_StrictImageCategory(_StaticRoles_ImageCategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> StrictImageCategory.ObjectType: ...
        def codomain(self) -> StrictImageCategory.ObjectType: ...

class StrictImageCategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_StrictImageCategory,
    ImageCategory[
        MorphismData, TwoMorphismData, _StaticRoles_StrictImageCategory.ObjectType, _StaticRoles_StrictImageCategory.ElementType, _StaticRoles_StrictImageCategory.MorphismType
    ],
): ...

class _StaticRoles_FullImageCategory(_StaticRoles_ImageCategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> FullImageCategory.ObjectType: ...
        def codomain(self) -> FullImageCategory.ObjectType: ...

class FullImageCategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_FullImageCategory,
    ImageCategory[
        MorphismData, TwoMorphismData, _StaticRoles_FullImageCategory.ObjectType, _StaticRoles_FullImageCategory.ElementType, _StaticRoles_FullImageCategory.MorphismType
    ],
): ...

class _StaticRoles_EssentialImageCategory(sage_categories.cat.properties._StaticRoles_PredicateSubcategory):
    class ObjectType(sage_categories.sets.finite._StaticRoles_SetsCategory.ObjectType): ...
    class ElementType(sage_categories.sets.finite._StaticRoles_SetsCategory.ElementType): ...

    class MorphismType(sage_categories.sets.finite._StaticRoles_SetsCategory.MorphismType):
        def domain(self) -> EssentialImageCategory.ObjectType: ...
        def codomain(self) -> EssentialImageCategory.ObjectType: ...

class EssentialImageCategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_EssentialImageCategory,
    PredicateSubcategory[
        MorphismData,
        TwoMorphismData,
        _StaticRoles_EssentialImageCategory.ObjectType,
        _StaticRoles_EssentialImageCategory.ElementType,
        _StaticRoles_EssentialImageCategory.MorphismType,
    ],
):
    def __init__(self, ambient: Category, name: str, full_subcategory_of: tuple[Category, ...], defining_functor: Functor) -> None: ...
    def defining_functor(self) -> Functor: ...
    def object_image(self, source: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
    def morphism_image(self, source: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    @cached_method
    def factor_functor(self) -> Functor: ...
    def inclusion_functor(self) -> Functor: ...
    def factorization(self) -> tuple[Functor, Functor]: ...

def retain_object_image(defining_functor: Functor, image: CategoryOfCategories.ElementType) -> None: ...
def retain_morphism_image(defining_functor: Functor, image: MorphismCategory.ObjectType) -> None: ...
def strict_image(target: Category, defining_functor: Functor) -> StrictImageCategory: ...
def register_full_image(defining_functor: Functor, image: Category) -> None: ...
def full_image(target: Category, defining_functor: Functor) -> Category: ...
