from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory

class LeafCategory(Category):
    def assemble_object(self, data: object) -> CategoryOfCategories.ElementType: ...
    def assemble_morphism(self, domain: CategoryOfCategories.ElementType, codomain: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...

class MorphismDataCategory(LeafCategory):
    def _morphism_from_data(self, domain: CategoryOfCategories.ElementType, codomain: CategoryOfCategories.ElementType, data: object) -> MorphismCategory.ObjectType: ...
    def _identity_data(self, member_object: CategoryOfCategories.ElementType) -> object: ...
    def _composite_data(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> object: ...
    def construct_identity(self, member_object: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def composite(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...

class FaithfulStructureCategory(MorphismDataCategory):
    def _morphism_data_functor(self) -> Functor: ...
    def _identity_data(self, member_object: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def _composite_data(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...

class ContravariantFaithfulStructureCategory(FaithfulStructureCategory): ...
class ParameterizedThinCategory(MorphismDataCategory):
    def __init__(self, *parameters: object) -> None: ...
    def parameter(self, position: int) -> object: ...
    def _admits_morphism(self, domain: CategoryOfCategories.ElementType, codomain: CategoryOfCategories.ElementType) -> bool: ...
