from collections.abc import Callable
from typing import NamedTuple

import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
from sage_categories.cat.calculus import binary_product_data as binary_product_data
from sage_categories.cat.calculus import natural_isomorphism as natural_isomorphism
from sage_categories.cat.calculus import pair_maps as pair_maps
from sage_categories.cat.calculus import product_functor as product_functor
from sage_categories.cat.calculus import terminal_map as terminal_map
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import NaturalTransformation as NaturalTransformation
from sage_categories.cat.morphisms import Mor as Mor
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.engines.diagrams import DiagramBox as DiagramBox
from sage_categories.engines.diagrams import NonstrictMonoidalModel as NonstrictMonoidalModel
from sage_categories.engines.diagrams import evaluate_path as evaluate_path
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.sage_runtime import cached_function as cached_function

__all__ = [
    "Actions",
    "ActionsCategory",
    "Cartesian",
    "Composition",
    "MonoidalStructures",
    "MonoidalStructuresCategory",
    "Reversed",
    "SelfAction",
    "TrivialAction",
    "register_cartesian_comparisons",
]
type CartesianComparisonHandler = Callable[..., MorphismCategory.ObjectType]

def register_cartesian_comparisons(category_type: type[Category], handler: CartesianComparisonHandler) -> None: ...

class _MonoidalData(NamedTuple):
    tensor: Functor
    unit: CategoryOfCategories.ElementType
    associator: NaturalTransformation
    left_unitor: NaturalTransformation
    right_unitor: NaturalTransformation

class _StaticRoles_MonoidalStructuresCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def __init__(self, data: _MonoidalData) -> None: ...
        def underlying_category(self) -> Category: ...
        def tensor(self) -> Functor: ...
        def unit(self) -> CategoryOfCategories.ElementType: ...
        def associator(self) -> NaturalTransformation: ...
        def left_unitor(self) -> NaturalTransformation: ...
        def right_unitor(self) -> NaturalTransformation: ...
        def diagram_wire(self, value: CategoryOfCategories.ElementType): ...
        def diagram_box(
            self, name: str, domain: tuple[CategoryOfCategories.ElementType, ...], codomain: tuple[CategoryOfCategories.ElementType, ...], arrow: MorphismCategory.ObjectType
        ) -> DiagramBox: ...
        def interpret(self, diagram) -> MorphismCategory.ObjectType: ...
        def pentagon(
            self, w: CategoryOfCategories.ElementType, x: CategoryOfCategories.ElementType, y: CategoryOfCategories.ElementType, z: CategoryOfCategories.ElementType
        ) -> Proposition: ...
        def triangle(self, x: CategoryOfCategories.ElementType, y: CategoryOfCategories.ElementType) -> Proposition: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        ...

        def domain(self) -> MonoidalStructuresCategory.ObjectType: ...
        def codomain(self) -> MonoidalStructuresCategory.ObjectType: ...

class MonoidalStructuresCategory(
    _StaticRoles_MonoidalStructuresCategory,
    Category[
        [], [], _StaticRoles_MonoidalStructuresCategory.ObjectType, _StaticRoles_MonoidalStructuresCategory.ElementType, _StaticRoles_MonoidalStructuresCategory.MorphismType
    ],
):
    def __init__(self, base: Category) -> None: ...
    def __call__(
        self,
        tensor: Functor,
        unit: CategoryOfCategories.ElementType,
        associator: NaturalTransformation,
        left_unitor: NaturalTransformation,
        right_unitor: NaturalTransformation,
    ) -> MonoidalStructuresCategory.ObjectType: ...
    def construct_morphism(self, source: MonoidalStructuresCategory.ObjectType, target: MonoidalStructuresCategory.ObjectType) -> MonoidalStructuresCategory.MorphismType: ...

def MonoidalStructures(base: Category) -> MonoidalStructuresCategory: ...
def Cartesian(base: Category) -> MonoidalStructuresCategory.ObjectType: ...
def Reversed(monoidal: MonoidalStructuresCategory.ObjectType) -> MonoidalStructuresCategory.ObjectType: ...
def Composition(base: Category) -> MonoidalStructuresCategory.ObjectType: ...

class _ActionData(NamedTuple):
    action: Functor
    associator: NaturalTransformation
    unitor: NaturalTransformation

class _StaticRoles_ActionsCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def __init__(self, data: _ActionData) -> None: ...
        def monoidal_structure(self) -> MonoidalStructuresCategory.ObjectType: ...
        def underlying_category(self) -> Category: ...
        def action(self) -> Functor: ...
        def associator(self) -> NaturalTransformation: ...
        def unitor(self) -> NaturalTransformation: ...
        def pentagon(
            self, m: CategoryOfCategories.ElementType, n: CategoryOfCategories.ElementType, p: CategoryOfCategories.ElementType, x: CategoryOfCategories.ElementType
        ) -> Proposition: ...
        def triangle(self, m: CategoryOfCategories.ElementType, x: CategoryOfCategories.ElementType) -> Proposition: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        ...

        def domain(self) -> ActionsCategory.ObjectType: ...
        def codomain(self) -> ActionsCategory.ObjectType: ...

class ActionsCategory(
    _StaticRoles_ActionsCategory, Category[[], [], _StaticRoles_ActionsCategory.ObjectType, _StaticRoles_ActionsCategory.ElementType, _StaticRoles_ActionsCategory.MorphismType]
):
    def __init__(self, monoidal: MonoidalStructuresCategory.ObjectType, base: Category) -> None: ...
    def __call__(self, action: Functor, associator: NaturalTransformation, unitor: NaturalTransformation) -> ActionsCategory.ObjectType: ...
    def construct_morphism(self, source: ActionsCategory.ObjectType, target: ActionsCategory.ObjectType) -> ActionsCategory.MorphismType: ...

def Actions(monoidal: MonoidalStructuresCategory.ObjectType, base: Category) -> ActionsCategory: ...
def SelfAction(monoidal: MonoidalStructuresCategory.ObjectType) -> ActionsCategory.ObjectType: ...
def TrivialAction(monoidal: MonoidalStructuresCategory.ObjectType, base: Category) -> ActionsCategory.ObjectType: ...
def tensor_object(tensor: Functor, first: CategoryOfCategories.ElementType, second: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
def tensor_morphism(tensor: Functor, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
def tensor_parentheses(tensor: Functor) -> tuple[Functor, Functor]: ...
def tensor_units(tensor: Functor, unit: CategoryOfCategories.ElementType) -> tuple[Functor, Functor]: ...
