from typing import Literal, overload

from _typeshed import Incomplete

import sage_categories.cat.category as _category
import sage_categories.cat.functors
import sage_categories.cat.properties
import sage_categories.kernel.roles
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.category import composite_factors as composite_factors
from sage_categories.cat.category import is_composite as is_composite
from sage_categories.cat.category import (
    retain_composite_factors as retain_composite_factors,
)
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.predicates import Axiom as Axiom
from sage_categories.cat.predicates import Decision as Decision
from sage_categories.cat.predicates import Predicate as Predicate
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import decide as decide
from sage_categories.cat.predicates import property_predicate as property_predicate
from sage_categories.cat.predicates import register_handler as register_handler
from sage_categories.cat.properties import (
    FixedEndpointProperty as FixedEndpointProperty,
)
from sage_categories.cat.properties import FullSubcategory as FullSubcategory
from sage_categories.cat.properties import PredicateSubcategory as PredicateSubcategory
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.kernel.refinement import common_ancestor as common_ancestor
from sage_categories.kernel.refinement import is_placed as is_placed
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.roles import Role as Role
from sage_categories.kernel.sage_runtime import Integer as Integer
from sage_categories.kernel.sage_runtime import Unknown as Unknown
from sage_categories.kernel.sage_runtime import cached_method as cached_method
from sage_categories.kernel.type_aliases import EqualityInput as EqualityInput

__all__ = ["EndomorphismsCategory", "FixedEndpointCategory", "IsomorphismsCategory", "Mor", "MorphismCategory", "endpoints", "endpoints_in", "hom_inhabitation"]

@overload
def Mor[**M, **T, ObjectRole, ElementRole, MorphismRole](
    category: _category.CategoryDeclaration[M, T, ObjectRole, ElementRole, MorphismRole],
) -> MorphismCategory[M, T, MorphismRole]: ...
@overload
def Mor[**M, **T, ObjectRole, ElementRole, MorphismRole](
    level: Literal[0], category: _category.CategoryDeclaration[M, T, ObjectRole, ElementRole, MorphismRole]
) -> _category.CategoryDeclaration[M, T, ObjectRole, ElementRole, MorphismRole]: ...
@overload
def Mor[**M, **T, ObjectRole, ElementRole, MorphismRole](
    level: Literal[1], category: _category.CategoryDeclaration[M, T, ObjectRole, ElementRole, MorphismRole]
) -> MorphismCategory[M, T, MorphismRole]: ...
@overload
def Mor[**M, **T, ObjectRole, ElementRole, MorphismRole](
    level: Literal[2], category: _category.CategoryDeclaration[M, T, ObjectRole, ElementRole, MorphismRole]
) -> MorphismCategory[T, []]: ...
@overload
def Mor[**M, **T, ObjectRole, ElementRole, MorphismRole](
    level: int | Integer, category: _category.CategoryDeclaration[M, T, ObjectRole, ElementRole, MorphismRole]
) -> _category.CategoryDeclaration: ...

endpoints: Incomplete
endpoints_in: Incomplete

def hom_inhabitation(hom_category: Category) -> Decision: ...

class _StaticRoles_MorphismCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.MorphismOfCategory):
        def domain(self) -> CategoryOfCategories.ElementType: ...
        def codomain(self) -> CategoryOfCategories.ElementType: ...
        def cell_dimension(self) -> int: ...
        def boundary(self, side: Literal["source", "target"], depth: int = 0) -> CategoryOfCategories.ElementType: ...
        def typecheck_cell(self) -> None: ...
        def base_category(self) -> Category: ...
        def retain_factors(self, first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> None: ...
        def is_composite(self) -> bool: ...
        def word(self) -> tuple[MorphismCategory.ObjectType, ...]: ...
        def factors(self) -> tuple[MorphismCategory.ObjectType, MorphismCategory.ObjectType]: ...
        def op(self) -> MorphismCategory.ObjectType: ...
        def __mul__(self, first: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
        def __eq__(self, candidate: EqualityInput) -> Predicate: ...
        def __ne__(self, candidate: EqualityInput) -> Proposition: ...
        def __hash__(self) -> int: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(_StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> MorphismCategory.ObjectType: ...
        def codomain(self) -> MorphismCategory.ObjectType: ...

class MorphismCategory[
    **MorphismData,
    **TwoMorphismData,
    ObjectRole = _StaticRoles_MorphismCategory.ObjectType,
    ElementRole = _StaticRoles_MorphismCategory.ElementType,
    MorphismRole = _StaticRoles_MorphismCategory.MorphismType,
](_StaticRoles_MorphismCategory, Category[TwoMorphismData, [], ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, base: Category[MorphismData, TwoMorphismData]) -> None: ...
    def base_category(self) -> Category[MorphismData, TwoMorphismData]: ...
    def subcategory_monomorphism(self) -> Functor: ...
    def has_ambient(self) -> bool: ...
    def has_full_ambient(self) -> bool: ...
    def ambient(self) -> Category: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def role_source(self, role: Role) -> tuple[Category, Role]: ...
    def equality(self) -> Predicate: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__[DomainType, CodomainType](
        self, domain: DomainType, codomain: CodomainType
    ) -> FixedEndpointCategory[MorphismData, TwoMorphismData, DomainType, CodomainType, ObjectRole, ElementRole, MorphismRole]: ...
    def fixed_endpoint_type(self) -> type[FixedEndpointCategory[MorphismData, TwoMorphismData]]: ...
    def construct_identity(self, morphism: ObjectRole) -> ObjectRole: ...
    def composite(self, second: ObjectRole, first: ObjectRole) -> ObjectRole: ...
    def construct_morphism(self, source: ObjectRole, target: ObjectRole, *args: TwoMorphismData.args, **kwargs: TwoMorphismData.kwargs) -> ObjectRole: ...
    Monomorphisms: Incomplete
    Epimorphisms: Incomplete
    Isomorphisms: Incomplete
    Endomorphisms: Incomplete
    Identity: Incomplete

    def Automorphisms(self) -> Category: ...

class _StaticRoles_IsomorphismsCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(sage_categories.cat.properties._StaticRoles_PropertySubcategory.ObjectType):
        def inverse(self) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.properties._StaticRoles_PropertySubcategory.ElementType): ...

    class MorphismType(sage_categories.cat.properties._StaticRoles_PropertySubcategory.MorphismType):
        def domain(self) -> IsomorphismsCategory.ObjectType: ...
        def codomain(self) -> IsomorphismsCategory.ObjectType: ...

class IsomorphismsCategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_IsomorphismsCategory,
    PropertySubcategory[
        MorphismData,
        TwoMorphismData,
        _StaticRoles_IsomorphismsCategory.ObjectType,
        _StaticRoles_IsomorphismsCategory.ElementType,
        _StaticRoles_IsomorphismsCategory.MorphismType,
    ],
): ...

class _StaticRoles_EndomorphismsCategory(sage_categories.cat.properties._StaticRoles_PredicateSubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.MorphismType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.functors._StaticRoles_FunctorsCategory.ElementType): ...

    class MorphismType(sage_categories.cat.functors._StaticRoles_FunctorsCategory.MorphismType):
        def domain(self) -> EndomorphismsCategory.ObjectType: ...
        def codomain(self) -> EndomorphismsCategory.ObjectType: ...

class EndomorphismsCategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_EndomorphismsCategory,
    PredicateSubcategory[
        MorphismData,
        TwoMorphismData,
        _StaticRoles_EndomorphismsCategory.ObjectType,
        _StaticRoles_EndomorphismsCategory.ElementType,
        _StaticRoles_EndomorphismsCategory.MorphismType,
    ],
): ...

class _StaticRoles_FixedEndpointCategory(sage_categories.cat.properties._StaticRoles_FullSubcategory):
    class ObjectType(sage_categories.cat.functors._StaticRoles_FunctorCategory.MorphismType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(_StaticRoles_MorphismCategory.ElementType): ...

    class MorphismType(_StaticRoles_MorphismCategory.MorphismType):
        def domain(self) -> FixedEndpointCategory.ObjectType: ...
        def codomain(self) -> FixedEndpointCategory.ObjectType: ...

class FixedEndpointCategory[
    **MorphismData,
    **TwoMorphismData,
    DomainType = sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType,
    CodomainType = sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType,
    ObjectRole = _StaticRoles_MorphismCategory.ObjectType,
    ElementRole = _StaticRoles_MorphismCategory.ElementType,
    MorphismRole = _StaticRoles_MorphismCategory.MorphismType,
](_StaticRoles_FixedEndpointCategory, FullSubcategory[TwoMorphismData, [], ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, morphisms: MorphismCategory[MorphismData, TwoMorphismData], domain: DomainType, codomain: CodomainType) -> None: ...
    def domain(self) -> DomainType: ...
    def codomain(self) -> CodomainType: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self, *args: MorphismData.args, **kwargs: MorphismData.kwargs) -> ObjectRole: ...
    def one(self) -> ObjectRole: ...
    def compose(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> ObjectRole: ...
    def narrowing_type(self) -> type[FixedEndpointProperty[MorphismData, TwoMorphismData]]: ...

def _morphism_equality_decision(first: MorphismCategory.ObjectType, second: MorphismCategory.ObjectType) -> bool | None: ...
