from _typeshed import Incomplete
from sage.misc.cachefunc import cached_method
from sage_categories.cat.category import Category as Category, member as member
from sage_categories.cat.properties import FixedEndpointProperty as FixedEndpointProperty, FullSubcategory as FullSubcategory, PropertySubcategory as PropertySubcategory
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, decision_and as decision_and
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, Proposition as Proposition, ask as ask
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, Role as Role
from typing import Literal, overload

@overload
def Mor[**M, **T](category: Category[M, T]) -> MorphismCategory[M, T]: ...
@overload
def Mor[**M, **T](level: Literal[0], category: Category[M, T]) -> Category[M, T]: ...
@overload
def Mor[**M, **T](level: Literal[1], category: Category[M, T]) -> MorphismCategory[M, T]: ...
@overload
def Mor[**M, **T](level: Literal[2], category: Category[M, T]) -> MorphismCategory[T, []]: ...
@overload
def Mor(level: int, category: Category) -> MorphismCategory[[], []]: ...

class IdentityTwoCell(MorphismOfCategory):
    def __init__(self, category: Category, morphism: MorphismOfCategory) -> None: ...

endpoints: Incomplete
endpoints_in: Incomplete
inhabited: Incomplete

class MorphismCategory[**MorphismData, **TwoMorphismData](Category[TwoMorphismData, []]):
    @property
    def ObjectType(self) -> type[ObjectOfCategory]: ...
    @property
    def ElementType(self) -> type[ElementOfObject]: ...
    @property
    def MorphismType(self) -> type[MorphismOfCategory]: ...
    def __init__(self, base: Category[MorphismData, TwoMorphismData]) -> None: ...
    def base_category(self) -> Category[MorphismData, TwoMorphismData]: ...
    def has_ambient(self) -> bool: ...
    def ambient(self) -> Category: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def role_source(self, role: Role) -> tuple[Category, Role]: ...
    def local_role_class(self, role: Role) -> type[CategoryPoint]: ...
    def equality(self) -> Predicate: ...
    def membership_proposition(self, candidate: CategoryPoint) -> Proposition: ...
    def __call__(self, domain: ObjectOfCategory, codomain: ObjectOfCategory) -> FixedEndpointCategory[MorphismData, TwoMorphismData]: ...
    def fixed_endpoint_type(self) -> type[FixedEndpointCategory[MorphismData, TwoMorphismData]]: ...
    def construct_identity(self, morphism: MorphismOfCategory) -> MorphismOfCategory: ...
    def composite(self, second: MorphismOfCategory, first: MorphismOfCategory) -> MorphismOfCategory: ...
    def construct_morphism(self, source: MorphismOfCategory, target: MorphismOfCategory, *args: TwoMorphismData.args, **kwargs: TwoMorphismData.kwargs) -> MorphismOfCategory: ...
    @cached_method
    def Monomorphisms(self) -> Category: ...
    @cached_method
    def Epimorphisms(self) -> Category: ...
    @cached_method
    def Isomorphisms(self) -> Category: ...
    @cached_method
    def Endomorphisms(self) -> Category: ...
    def Automorphisms(self) -> Category: ...

class FixedEndpointCategory[**MorphismData, **TwoMorphismData](FullSubcategory[TwoMorphismData, []]):
    @property
    def ObjectType(self) -> type[ObjectOfCategory]: ...
    @property
    def ElementType(self) -> type[ElementOfObject]: ...
    @property
    def MorphismType(self) -> type[MorphismOfCategory]: ...
    def __init__(self, morphisms: MorphismCategory[MorphismData, TwoMorphismData], domain: ObjectOfCategory, codomain: ObjectOfCategory) -> None: ...
    def domain(self) -> ObjectOfCategory: ...
    def codomain(self) -> ObjectOfCategory: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def membership_proposition(self, candidate: CategoryPoint) -> Proposition: ...
    def is_inhabited(self) -> AppliedPredicate: ...
    def is_empty(self) -> Proposition: ...
    def __call__(self, *args: MorphismData.args, **kwargs: MorphismData.kwargs) -> MorphismOfCategory: ...
    def identity(self) -> MorphismOfCategory: ...
    def compose(self, second: MorphismOfCategory, first: MorphismOfCategory) -> MorphismOfCategory: ...
    def Monomorphisms(self) -> Category: ...
    def Epimorphisms(self) -> Category: ...
    def Isomorphisms(self) -> Category: ...
    def narrowing_type(self) -> type[FixedEndpointProperty[MorphismData, TwoMorphismData]]: ...
