from collections.abc import Callable
from dataclasses import dataclass

import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import NaturalTransformation as NaturalTransformation
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import UnknownClass as UnknownClass
from sage_categories.kernel.refinement import is_placed as is_placed
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.retention import deferred_category as deferred_category
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.retention import retained_involution as retained_involution
from sage_categories.kernel.roles import Role as Role
from sage_categories.kernel.sage_runtime import cached_function as cached_function

__all__ = ["Op", "OppositeCategory", "op_squared_isomorphism", "opposite_category", "opposite_functor", "opposite_morphism", "opposite_transformation"]

@dataclass(frozen=True, eq=False, slots=True)
class _OppositeMorphismData:
    original: MorphismCategory.ObjectType

class _StaticRoles_OppositeCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def __init__(self, data: _OppositeMorphismData) -> None: ...
        def original(self) -> MorphismCategory.ObjectType: ...
        def domain(self) -> OppositeCategory.ObjectType: ...
        def codomain(self) -> OppositeCategory.ObjectType: ...

class OppositeCategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_OppositeCategory,
    Category[
        [MorphismCategory.ObjectType], [], _StaticRoles_OppositeCategory.ObjectType, _StaticRoles_OppositeCategory.ElementType, _StaticRoles_OppositeCategory.MorphismType
    ],
):
    def __init__(self, original: Category[MorphismData, TwoMorphismData]) -> None: ...
    def original(self) -> Category[MorphismData, TwoMorphismData]: ...
    def is_discrete(self) -> bool: ...
    def role_source(self, role: Role) -> tuple[Category, Role]: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self, value: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
    def object_set(self) -> CategoryOfCategories.ElementType: ...
    def object_at(self, point: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
    def object_point(self, member_object: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
    def generating_morphisms(self) -> tuple[MorphismCategory.ObjectType, ...] | UnknownClass: ...
    def construct_morphism(
        self, domain: CategoryOfCategories.ElementType, codomain: CategoryOfCategories.ElementType, original: MorphismCategory.ObjectType
    ) -> MorphismCategory.ObjectType: ...
    def construct_identity(self, member_object: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def composite(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], CategoryOfCategories.ElementType]: ...

def opposite_category(category: Category) -> Category: ...
def opposite_morphism(morphism: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...

Op: Functor

def opposite_functor(functor: Functor) -> Functor: ...
@retained_involution
def opposite_transformation(transformation: NaturalTransformation) -> NaturalTransformation: ...
def op_squared_isomorphism() -> NaturalTransformation: ...
