import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Predicate as Predicate
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import register_handler as register_handler

__all__ = ["PointCategory", "PointMorphismCategory"]

class _StaticRoles_PointMorphismCategory(sage_categories.cat.morphisms._StaticRoles_MorphismCategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> PointMorphismCategory.ObjectType: ...
        def codomain(self) -> PointMorphismCategory.ObjectType: ...

class PointMorphismCategory(
    _StaticRoles_PointMorphismCategory,
    MorphismCategory[_StaticRoles_PointMorphismCategory.ObjectType, _StaticRoles_PointMorphismCategory.ElementType, _StaticRoles_PointMorphismCategory.MorphismType],
):
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...

class _StaticRoles_PointCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> PointCategory.ObjectType: ...
        def codomain(self) -> PointCategory.ObjectType: ...

class PointCategory(
    _StaticRoles_PointCategory, Category[[], [], _StaticRoles_PointCategory.ObjectType, _StaticRoles_PointCategory.ElementType, _StaticRoles_PointCategory.MorphismType]
):
    def __init__(self, member: CategoryOfCategories.ElementType) -> None: ...
    def member(self) -> CategoryOfCategories.ElementType: ...
    def morphism_category_type(self) -> type[PointMorphismCategory]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self) -> CategoryOfCategories.ElementType: ...
    def construct_morphism(self, domain: CategoryOfCategories.ElementType, codomain: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def construct_identity(self, member_object: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def composite(self, second: MorphismCategory.ObjectType, first: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    def inverse_morphism(self, morphism: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
