from collections.abc import Callable, Iterable

from sympy.logic.boolalg import Boolean

from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.kernel.predicates import (
    AppliedPredicate as AppliedPredicate,
)
from sage_categories.kernel.predicates import (
    OwnedPredicate as Predicate,
)
from sage_categories.kernel.predicates import (
    ask_query as ask_query,
)
from sage_categories.kernel.predicates import (
    assume_property as assume_property,
)
from sage_categories.kernel.predicates import (
    axiom_layer as axiom_layer,
)
from sage_categories.kernel.predicates import (
    bind_property_predicate as bind_property_predicate,
)
from sage_categories.kernel.predicates import (
    owned_predicate as owned_predicate,
)
from sage_categories.kernel.predicates import (
    register_declared_case as register_declared_case,
)
from sage_categories.kernel.predicates import (
    register_predicate_handler as register_predicate_handler,
)
from sage_categories.kernel.predicates import (
    register_query_handler as register_query_handler,
)
from sage_categories.kernel.sage_runtime import Unknown as Unknown
from sage_categories.kernel.sage_runtime import UnknownClass as UnknownClass
from sage_categories.kernel.sage_runtime import uncamelcase as uncamelcase
from sage_categories.kernel.type_aliases import EqualityInput as EqualityInput

__all__ = [
    "Answer",
    "Axiom",
    "AppliedPredicate",
    "AppliedQuery",
    "Argument",
    "ConstructionFamily",
    "Decision",
    "DecidingProposition",
    "Predicate",
    "PredicateHandler",
    "Proposition",
    "Query",
    "QueryAnswer",
    "QueryHandler",
    "Unknown",
    "UnknownClass",
    "ask",
    "assume",
    "conjunction",
    "decide",
    "declared_axiom",
    "disjunction",
    "established",
    "implication",
    "negation",
    "property_predicate",
    "register_handler",
    "retract",
    "unconditional",
]
type Argument = CategoryOfCategories.ElementType | AppliedQuery | int
type Decision = bool | UnknownClass
type PredicateDecision = bool | None
type QueryAnswer = CategoryOfCategories.ElementType | UnknownClass
type Answer = Decision | CategoryOfCategories.ElementType
type PredicateHandler = Callable[..., PredicateDecision]
type QueryHandler = Callable[..., QueryAnswer]
type Proposition = Boolean
type DecidingProposition = Callable[[Category, CategoryOfCategories.ElementType], Proposition]

def property_predicate(name: str, category: Category) -> Predicate: ...
def register_handler(owner: Predicate, handler: PredicateHandler) -> None: ...

class Query:
    def __init__(self, name: str, arity: int, result_category: Category) -> None: ...
    def name(self) -> str: ...
    def register_handler(self, handler: QueryHandler) -> None: ...
    def result_category(self) -> Category: ...
    def __call__(self, *arguments: Argument) -> AppliedQuery: ...

class AppliedQuery:
    def __init__(self, query: Query, arguments: tuple[Argument, ...]) -> None: ...
    def query(self) -> Query: ...
    def arguments(self) -> tuple[Argument, ...]: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: EqualityInput) -> Proposition: ...
    def __ne__(self, other: EqualityInput) -> Proposition: ...
    def __lt__(self, other: CategoryOfCategories.ElementType) -> Proposition: ...
    def __le__(self, other: CategoryOfCategories.ElementType) -> Proposition: ...
    def __gt__(self, other: CategoryOfCategories.ElementType) -> Proposition: ...
    def __ge__(self, other: CategoryOfCategories.ElementType) -> Proposition: ...

def conjunction(parts: Iterable[bool | Proposition]) -> Proposition: ...
def disjunction(parts: Iterable[bool | Proposition]) -> Proposition: ...
def negation(proposition: bool | Proposition) -> Proposition: ...
def implication(antecedent: bool | Proposition, consequent: bool | Proposition) -> Proposition: ...
def decide(proposition: Decision | Proposition, assumptions: Proposition = True) -> bool | None: ...
def unconditional(assumptions: Proposition) -> bool: ...
def ask(application: Decision | Proposition | AppliedQuery) -> Answer: ...
def established(application: Decision | Proposition) -> bool: ...
def assume(proposition: Proposition) -> None: ...
def retract(proposition: Proposition) -> None: ...

class Axiom:
    def __init__(self, deciding: DecidingProposition | None = None, *, full_subcategory_of: tuple[Axiom, ...] = ()) -> None: ...
    def __set_name__(self, declaring_class: type[Category], name: str) -> None: ...
    def application_name(self) -> str: ...
    def application_owner(self) -> type[CategoryOfCategories.ElementType] | None: ...
    def __get__(self, category: Category | None, owner: type[Category]) -> Axiom | Callable[[], Category]: ...
    def name(self) -> str: ...
    def implemented_by(self, implementation: type[PropertySubcategory]) -> None: ...
    def subcategory(self, category: Category, *parameters: CategoryOfCategories.ElementType) -> Category: ...
    def is_constructed(self, category: Category, *parameters: CategoryOfCategories.ElementType) -> bool: ...
    def inverse_image(self, along: Callable[[Category], Functor]) -> Axiom: ...

class ConstructionFamily(Axiom): ...

def declared_axiom(category: Category, name: str) -> Axiom | None: ...
