from typing import ClassVar

from sage_categories.cat.category import Category, CategoryOfCategories
from sage_categories.cat.functors import Functor
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.cat.predicates import Decision, Predicate, Proposition

class FullSubcategory[**MorphismData, **TwoMorphismData](Category[MorphismData, TwoMorphismData]):
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData]) -> None: ...
    def has_ambient(self) -> bool: ...
    def ambient(self) -> Category[MorphismData, TwoMorphismData]: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def element_from_defining_morphism(self, defining_morphism: MorphismCategory.ObjectType) -> CategoryOfCategories.ElementType: ...

class InverseImageSubcategory[**MorphismData, **TwoMorphismData](FullSubcategory[MorphismData, TwoMorphismData]):
    def __init__(self, functor: Functor, target_subcategory: Category) -> None: ...
    def defining_functor(self) -> Functor: ...
    def target_subcategory(self) -> Category: ...
    def subcategory_monomorphism(self) -> Functor: ...
    def target_projection(self) -> Functor: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self, value: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...

def inverse_image(functor: Functor, target_subcategory: Category) -> Category: ...

class PropertySubcategory[**MorphismData, **TwoMorphismData](FullSubcategory[MorphismData, TwoMorphismData]):
    _base_category_class_and_axiom: ClassVar[tuple[type[Category], str]]
    def __init_subclass__(cls) -> None: ...
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], name: str, full_subcategory_of: tuple[Category, ...]) -> None: ...
    def name(self) -> str: ...
    def predicate(self) -> Predicate: ...
    def full_subcategory_of(self) -> tuple[Category, ...]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self, *arguments: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...

class PredicateSubcategory[**MorphismData, **TwoMorphismData](PropertySubcategory[MorphismData, TwoMorphismData]):
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], name: str, full_subcategory_of: tuple[Category, ...]) -> None: ...
    def _predicate(self, candidate: CategoryOfCategories.ElementType, assumptions: Proposition) -> bool | None: ...

class NarrowedProperty[**MorphismData, **TwoMorphismData](FullSubcategory[MorphismData, TwoMorphismData]):
    @property
    def ObjectType(self) -> type[CategoryOfCategories.ElementType]: ...
    @property
    def ElementType(self) -> type[CategoryOfCategories.ElementType]: ...
    @property
    def MorphismType(self) -> type[MorphismCategory.ObjectType]: ...
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], roots: tuple[FullSubcategory, ...]) -> None: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def predicate(self) -> Predicate: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self, value: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...

class FixedEndpointProperty[**MorphismData, **TwoMorphismData](NarrowedProperty[TwoMorphismData, []]):
    def domain(self) -> CategoryOfCategories.ElementType: ...
    def codomain(self) -> CategoryOfCategories.ElementType: ...
    def _chosen_inhabitation(self) -> Decision: ...
    def __call__(self, *args: MorphismData.args, **kwargs: MorphismData.kwargs) -> MorphismCategory.ObjectType: ...
    def one(self) -> MorphismCategory.ObjectType: ...
