from collections.abc import Callable
from typing import Literal

import sage_categories.cat.category
import sage_categories.cat.constructions
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
import sage_categories.sets.finite
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import FunctorsCategory as FunctorsCategory
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Axiom as Axiom
from sage_categories.cat.predicates import Decision as Decision
from sage_categories.cat.predicates import Predicate as Predicate
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import Unknown as Unknown
from sage_categories.cat.predicates import UnknownClass as UnknownClass
from sage_categories.cat.predicates import ask as ask
from sage_categories.cat.predicates import property_predicate as property_predicate
from sage_categories.cat.predicates import register_handler as register_handler
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.sage_runtime import cached_method as cached_method

__all__ = [
    "FixedEndpointProperty",
    "FullSubcategory",
    "InverseImageSubcategory",
    "NarrowedProperty",
    "PredicateSubcategory",
    "PropertySubcategory",
    "inverse_image",
    "retain_inverse_image",
]

class _StaticRoles_FullSubcategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> FullSubcategory.ObjectType: ...
        def codomain(self) -> FullSubcategory.ObjectType: ...

class FullSubcategory[
    **MorphismData,
    **TwoMorphismData,
    ObjectRole = _StaticRoles_FullSubcategory.ObjectType,
    ElementRole = _StaticRoles_FullSubcategory.ElementType,
    MorphismRole = _StaticRoles_FullSubcategory.MorphismType,
](_StaticRoles_FullSubcategory, Category[MorphismData, TwoMorphismData, ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData]) -> None: ...
    def has_ambient(self) -> bool: ...
    def ambient(self) -> Category[MorphismData, TwoMorphismData]: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def element_from_defining_morphism(self, defining_morphism: MorphismCategory.ObjectType) -> CategoryOfCategories.ElementType: ...
    def point_morphism(self, point: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], CategoryOfCategories.ElementType]: ...
    def colimit_construction(self, shape: Category) -> Callable[[Functor], CategoryOfCategories.ElementType]: ...
    def Terminal(self) -> CategoryOfCategories.ElementType: ...
    def image_factorization(self, arrow: MorphismCategory.ObjectType) -> tuple[MorphismCategory.ObjectType, MorphismCategory.ObjectType]: ...
    def factor_through_monomorphism(
        self, mono: MorphismCategory.ObjectType, arrow: MorphismCategory.ObjectType
    ) -> MorphismCategory.ObjectType | Literal[False] | UnknownClass: ...
    def hom_morphisms(self, source: CategoryOfCategories.ElementType, target: CategoryOfCategories.ElementType) -> tuple[MorphismCategory.ObjectType, ...] | UnknownClass: ...
    def restrict_morphism(self, morphism: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...

class _StaticRoles_InverseImageSubcategory(_StaticRoles_FullSubcategory):
    class ObjectType(sage_categories.sets.finite._StaticRoles_SetsCategory.ObjectType, sage_categories.cat.constructions._StaticRoles_LimitsCategory.ElementType): ...
    class ElementType(sage_categories.sets.finite._StaticRoles_SetsCategory.ElementType): ...

    class MorphismType(sage_categories.sets.finite._StaticRoles_SetsCategory.MorphismType):
        def domain(self) -> InverseImageSubcategory.ObjectType: ...
        def codomain(self) -> InverseImageSubcategory.ObjectType: ...

class InverseImageSubcategory[**MorphismData, **TwoMorphismData](
    _StaticRoles_InverseImageSubcategory,
    FullSubcategory[
        MorphismData,
        TwoMorphismData,
        _StaticRoles_InverseImageSubcategory.ObjectType,
        _StaticRoles_InverseImageSubcategory.ElementType,
        _StaticRoles_InverseImageSubcategory.MorphismType,
    ],
):
    def __init__(self, functor: Functor, target_subcategory: Category) -> None: ...
    def defining_functor(self) -> Functor: ...
    def target_subcategory(self) -> Category: ...
    def subcategory_monomorphism(self) -> Functor: ...
    @cached_method
    def target_projection(self) -> Functor: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__[Datum](self, *construction_data: Datum, **keywords: Datum) -> CategoryOfCategories.ElementType: ...

def inverse_image(functor: Functor, target_subcategory: Category) -> Category: ...
def retain_inverse_image(functor: Functor, target_subcategory: Category, realization: Category, source_projection: Functor, target_projection: Functor) -> None: ...

class _StaticRoles_PropertySubcategory(_StaticRoles_FullSubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> PropertySubcategory.ObjectType: ...
        def codomain(self) -> PropertySubcategory.ObjectType: ...

class PropertySubcategory[
    **MorphismData,
    **TwoMorphismData,
    ObjectRole = _StaticRoles_PropertySubcategory.ObjectType,
    ElementRole = _StaticRoles_PropertySubcategory.ElementType,
    MorphismRole = _StaticRoles_PropertySubcategory.MorphismType,
](_StaticRoles_PropertySubcategory, FullSubcategory[MorphismData, TwoMorphismData, ObjectRole, ElementRole, MorphismRole]):
    def __init_subclass__(cls) -> None: ...
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], name: str, full_subcategory_of: tuple[Category, ...]) -> None: ...
    def name(self) -> str: ...
    def predicate(self) -> Predicate: ...
    def full_subcategory_of(self) -> tuple[Category, ...]: ...
    def intersection(
        self, other: PropertySubcategory[MorphismData, TwoMorphismData] | tuple[Category[MorphismData, TwoMorphismData], ...]
    ) -> Category[MorphismData, TwoMorphismData]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__[Datum](self, *construction_data: Datum, **keywords: Datum) -> CategoryOfCategories.ElementType | Category[MorphismData, TwoMorphismData]: ...

class _StaticRoles_PredicateSubcategory(_StaticRoles_PropertySubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> PredicateSubcategory.ObjectType: ...
        def codomain(self) -> PredicateSubcategory.ObjectType: ...

class PredicateSubcategory[
    **MorphismData,
    **TwoMorphismData,
    ObjectRole = _StaticRoles_PredicateSubcategory.ObjectType,
    ElementRole = _StaticRoles_PredicateSubcategory.ElementType,
    MorphismRole = _StaticRoles_PredicateSubcategory.MorphismType,
](_StaticRoles_PredicateSubcategory, PropertySubcategory[MorphismData, TwoMorphismData, ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], name: str, full_subcategory_of: tuple[Category, ...]) -> None: ...

class _StaticRoles_NarrowedProperty(_StaticRoles_FullSubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> NarrowedProperty.ObjectType: ...
        def codomain(self) -> NarrowedProperty.ObjectType: ...

class NarrowedProperty[
    **MorphismData,
    **TwoMorphismData,
    ObjectRole = _StaticRoles_NarrowedProperty.ObjectType,
    ElementRole = _StaticRoles_NarrowedProperty.ElementType,
    MorphismRole = _StaticRoles_NarrowedProperty.MorphismType,
](_StaticRoles_NarrowedProperty, FullSubcategory[MorphismData, TwoMorphismData, ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], roots: tuple[FullSubcategory, ...]) -> None: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def predicate(self) -> Predicate: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__[Datum](self, *construction_data: Datum, **keywords: Datum) -> CategoryOfCategories.ElementType: ...

class _StaticRoles_FixedEndpointProperty(_StaticRoles_NarrowedProperty):
    class ObjectType(
        _StaticRoles_NarrowedProperty.ObjectType,
        sage_categories.cat.morphisms._StaticRoles_IsomorphismsCategory.ObjectType,
        sage_categories.cat.morphisms._StaticRoles_FixedEndpointCategory.ObjectType,
        sage_categories.cat.constructions._StaticRoles_LimitsCategory.ElementType,
    ): ...
    class ElementType(
        _StaticRoles_NarrowedProperty.ElementType,
        sage_categories.cat.morphisms._StaticRoles_IsomorphismsCategory.ElementType,
        sage_categories.cat.morphisms._StaticRoles_FixedEndpointCategory.ElementType,
    ): ...

    class MorphismType(
        _StaticRoles_NarrowedProperty.MorphismType,
        sage_categories.cat.morphisms._StaticRoles_IsomorphismsCategory.MorphismType,
        sage_categories.cat.morphisms._StaticRoles_FixedEndpointCategory.MorphismType,
    ):
        def domain(self) -> FixedEndpointProperty.ObjectType: ...
        def codomain(self) -> FixedEndpointProperty.ObjectType: ...

class FixedEndpointProperty[
    **MorphismData,
    **TwoMorphismData,
    ObjectRole = _StaticRoles_FixedEndpointProperty.ObjectType,
    ElementRole = _StaticRoles_FixedEndpointProperty.ElementType,
    MorphismRole = _StaticRoles_FixedEndpointProperty.MorphismType,
](_StaticRoles_FixedEndpointProperty, NarrowedProperty[TwoMorphismData, [], ObjectRole, ElementRole, MorphismRole]):
    def domain(self) -> CategoryOfCategories.ElementType: ...
    def codomain(self) -> CategoryOfCategories.ElementType: ...
    def one(self) -> MorphismCategory.ObjectType: ...
