from sage_categories.kernel.roles import ElementOfObject as ElementOfObject
from sage_categories.kernel.roles import ObjectOfCategory as ObjectOfCategory
from sage_categories.posets.category import Posets_TotallyOrdered_Finite_ElementType as Posets_TotallyOrdered_Finite_ElementType
from sage_categories.posets.category import Posets_TotallyOrdered_Finite_MorphismType as Posets_TotallyOrdered_Finite_MorphismType
from sage_categories.posets.category import Posets_TotallyOrdered_Finite_ObjectType as Posets_TotallyOrdered_Finite_ObjectType
from sage_categories.cat.category import Category as Category, member as member
from sage_categories.cat.functors import Functor as Functor, FunctorsCategory as FunctorsCategory
from sage_categories.kernel.compiler import empty_local_role as empty_local_role
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, PropertyPredicate as PropertyPredicate, Proposition as Proposition
from sage_categories.kernel.refinement import is_subcategory as is_subcategory, refine as refine
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, MorphismOfCategory as MorphismOfCategory, Role as Role

class FullSubcategory[**MorphismData, **TwoMorphismData](Category[MorphismData, TwoMorphismData]):
    @property
    def ObjectType(self) -> type[ObjectOfCategory]: ...
    @property
    def ElementType(self) -> type[ElementOfObject]: ...
    @property
    def MorphismType(self) -> type[MorphismOfCategory]: ...
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData]) -> None: ...
    def has_ambient(self) -> bool: ...
    def ambient(self) -> Category[MorphismData, TwoMorphismData]: ...
    def narrowing_base(self) -> Category: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def local_role_class(self, role: Role) -> type[CategoryPoint]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def classical_stages(self) -> tuple[CategoryPoint, ...]: ...
    def element_from_defining_morphism(self, defining_morphism: MorphismOfCategory) -> CategoryPoint: ...

class PropertySubcategory[**MorphismData, **TwoMorphismData](FullSubcategory[MorphismData, TwoMorphismData]):
    @property
    def ObjectType(self) -> type[ObjectOfCategory]: ...
    @property
    def ElementType(self) -> type[ElementOfObject]: ...
    @property
    def MorphismType(self) -> type[MorphismOfCategory]: ...
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], name: str, roles: dict[Role, type[CategoryPoint]], implications: tuple[Category, ...]) -> None: ...
    def name(self) -> str: ...
    def predicate(self) -> PropertyPredicate: ...
    def implications(self) -> tuple[Category, ...]: ...
    def local_role_class(self, role: Role) -> type[CategoryPoint]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def __call__(self, *arguments: CategoryPoint) -> CategoryPoint: ...

class NarrowedProperty[**MorphismData, **TwoMorphismData](FullSubcategory[MorphismData, TwoMorphismData]):
    @property
    def ObjectType(self) -> type[Posets_TotallyOrdered_Finite_ObjectType]: ...
    @property
    def ElementType(self) -> type[Posets_TotallyOrdered_Finite_ElementType]: ...
    @property
    def MorphismType(self) -> type[Posets_TotallyOrdered_Finite_MorphismType]: ...
    def __init__(self, ambient: Category[MorphismData, TwoMorphismData], roots: tuple[FullSubcategory, ...]) -> None: ...
    def narrowing_roots(self) -> tuple[Category, ...]: ...
    def predicate(self) -> PropertyPredicate: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def membership_proposition(self, candidate: CategoryPoint) -> Proposition: ...
    def __call__(self, value: CategoryPoint) -> CategoryPoint: ...

class FixedEndpointProperty[**MorphismData, **TwoMorphismData](NarrowedProperty[TwoMorphismData, []]):
    @property
    def ObjectType(self) -> type[ObjectOfCategory]: ...
    @property
    def ElementType(self) -> type[ElementOfObject]: ...
    @property
    def MorphismType(self) -> type[MorphismOfCategory]: ...
    def domain(self) -> CategoryPoint: ...
    def codomain(self) -> CategoryPoint: ...
    def is_inhabited(self) -> AppliedPredicate: ...
    def is_empty(self) -> Proposition: ...
    def __call__(self, *args: MorphismData.args, **kwargs: MorphismData.kwargs) -> MorphismOfCategory: ...
    def identity(self) -> MorphismOfCategory: ...

class IsomorphismRole(MorphismOfCategory):
    def inverse(self) -> MorphismOfCategory: ...
