from collections.abc import Hashable

import sage_categories.cat.category
import sage_categories.cat.comma
import sage_categories.cat.morphisms
import sage_categories.cat.properties
import sage_categories.kernel.roles
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.category import member as member
from sage_categories.cat.comma import CommaCategory as CommaCategory
from sage_categories.cat.comma import CommaSpecialization as CommaSpecialization
from sage_categories.cat.comma import comma_objects as comma_objects
from sage_categories.cat.cones import cone as cone
from sage_categories.cat.diagrams import cospan_diagram as cospan_diagram
from sage_categories.cat.diagrams import sequence_position as sequence_position
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import NaturalTransformation as NaturalTransformation
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Predicate as Predicate
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import ask as ask
from sage_categories.cat.predicates import register_handler as register_handler
from sage_categories.cat.properties import FullSubcategory as FullSubcategory
from sage_categories.kernel.refinement import is_placed as is_placed
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.sage_runtime import cached_method as cached_method

__all__ = ["CommaCategory", "SliceLikeCategory", "SliceProperty", "SubobjectsOfProduct", "comma_category", "coslice_under", "slice_over"]

class _StaticRoles_SliceLikeCategory(sage_categories.cat.comma._StaticRoles_CommaSpecialization):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> SliceLikeCategory.ObjectType: ...
        def codomain(self) -> SliceLikeCategory.ObjectType: ...

class SliceLikeCategory(
    _StaticRoles_SliceLikeCategory,
    CommaSpecialization[_StaticRoles_SliceLikeCategory.ObjectType, _StaticRoles_SliceLikeCategory.ElementType, _StaticRoles_SliceLikeCategory.MorphismType],
):
    def __init__(self, base: Category, fixed: CategoryOfCategories.ElementType, fixed_label: int) -> None: ...
    def arrows(self) -> Category: ...
    def fixed_evaluation(self) -> Functor: ...
    @cached_method
    def defining_arrow(self) -> Functor: ...
    @cached_method
    def fixed_projection(self) -> Functor: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def retain_lifts(self) -> None: ...
    def base_of_slice(self) -> Category: ...
    def fixed_object(self) -> CategoryOfCategories.ElementType: ...
    def fixed_end(self, morphism: MorphismCategory.ObjectType) -> CategoryOfCategories.ElementType: ...
    def varying_end(self, morphism: MorphismCategory.ObjectType) -> CategoryOfCategories.ElementType: ...
    def defining_arrow_of(self, candidate: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def property_type(self, property_category: Category) -> type[SliceProperty]: ...
    def Monomorphisms(self) -> Category: ...
    def Epimorphisms(self) -> Category: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self, value: CategoryOfCategories.ElementType) -> SliceLikeCategory.ObjectType: ...
    def construct_morphism(
        self, domain: SliceLikeCategory.ObjectType, codomain: SliceLikeCategory.ObjectType, varying: MorphismCategory.ObjectType
    ) -> SliceLikeCategory.MorphismType: ...
    def varying_component(self, square: NaturalTransformation) -> MorphismCategory.ObjectType: ...

def slice_over(base: Category, fixed: CategoryOfCategories.ElementType) -> SliceLikeCategory: ...
def coslice_under(base: Category, fixed: CategoryOfCategories.ElementType) -> SliceLikeCategory: ...
def comma_category(first: Functor, second: Functor) -> CommaCategory: ...

class _StaticRoles_SliceProperty(sage_categories.cat.properties._StaticRoles_FullSubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> SliceProperty.ObjectType: ...
        def codomain(self) -> SliceProperty.ObjectType: ...

class SliceProperty[ObjectRole, ElementRole, MorphismRole](
    _StaticRoles_SliceProperty, FullSubcategory[[MorphismCategory.ObjectType], [], ObjectRole, ElementRole, MorphismRole]
):
    def __init__(self, ambient: SliceLikeCategory | SliceProperty, property_category: Category) -> None: ...
    def property_category(self) -> Category: ...
    def base_of_slice(self) -> Category: ...
    def subcategory_monomorphism(self) -> Functor: ...
    @cached_method
    def defining_arrow(self) -> Functor: ...
    def defining_arrow_of(self, candidate: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
    def membership_proposition(self, candidate: CategoryOfCategories.ElementType) -> Proposition: ...
    def __call__(self, value: CategoryOfCategories.ElementType) -> SliceLikeCategory.ObjectType: ...

class _StaticRoles_SubobjectsOfProduct(_StaticRoles_SliceProperty):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def product_projection(self, index: CategoryOfCategories.ElementType | Hashable) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> SubobjectsOfProduct.ObjectType: ...
        def codomain(self) -> SubobjectsOfProduct.ObjectType: ...

class SubobjectsOfProduct(
    _StaticRoles_SubobjectsOfProduct,
    SliceProperty[_StaticRoles_SubobjectsOfProduct.ObjectType, _StaticRoles_SubobjectsOfProduct.ElementType, _StaticRoles_SubobjectsOfProduct.MorphismType],
): ...

def _star() -> CategoryOfCategories.ElementType: ...
def _is_slice_over(category: SliceLikeCategory) -> bool: ...
def _pair_functor(first: Functor, second: Functor) -> Functor: ...
def _endpoint_functor(base: Category) -> Functor: ...
def _construct_comma_category(first: Functor, second: Functor, category_type: type[CommaCategory] = ...) -> CommaCategory: ...
