from collections.abc import Callable
from functools import partial

from _typeshed import Incomplete

import sage_categories.cat.cat_constructions
import sage_categories.cat.category
import sage_categories.cat.constructions
import sage_categories.cat.morphisms
import sage_categories.cat.properties
import sage_categories.kernel.roles
import sage_categories.sets.finite
from sage_categories.cat.calculus import binary_product_data as binary_product_data
from sage_categories.cat.calculus import pair_maps as pair_maps
from sage_categories.cat.calculus import product_functor as product_functor
from sage_categories.cat.calculus import terminal_map as terminal_map
from sage_categories.cat.cat_constructions import FamilyObjectData as FamilyObjectData
from sage_categories.cat.cat_constructions import LimitSubcategory as LimitSubcategory
from sage_categories.cat.cat_constructions import (
    limit_of_categories as limit_of_categories,
)
from sage_categories.cat.category import Cat as Cat
from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.comma import comma_objects as comma_objects
from sage_categories.cat.cones import LimitConesCategory as LimitConesCategory
from sage_categories.cat.cones import cone as cone
from sage_categories.cat.cones import cones as cones
from sage_categories.cat.declarations import Sets as Sets
from sage_categories.cat.diagrams import cospan_diagram as cospan_diagram
from sage_categories.cat.diagrams import from_sequence as from_sequence
from sage_categories.cat.diagrams import sequence_position as sequence_position
from sage_categories.cat.functors import Fun as Fun
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.functors import NaturalTransformation as NaturalTransformation
from sage_categories.cat.monoidal import Cartesian as Cartesian
from sage_categories.cat.monoidal import (
    MonoidalStructuresCategory as MonoidalStructuresCategory,
)
from sage_categories.cat.monoidal import tensor_parentheses as tensor_parentheses
from sage_categories.cat.monoidal import tensor_units as tensor_units
from sage_categories.cat.morphisms import Mor as Mor
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.predicates import Axiom as Axiom
from sage_categories.cat.predicates import Predicate as Predicate
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import ask as ask
from sage_categories.cat.properties import FullSubcategory as FullSubcategory
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.cat.shapes import Discrete as Discrete
from sage_categories.engines.presented_modules import tensor_morphism as tensor_morphism
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.retention import (
    complete_constructions as complete_constructions,
)
from sage_categories.kernel.retention import identity_key as identity_key
from sage_categories.kernel.sage_runtime import cached_function as cached_function
from sage_categories.kernel.sage_runtime import cached_method as cached_method

__all__ = [
    "AdditiveGroups",
    "AdditiveGroupsCategory",
    "AdditiveMagmas",
    "AdditiveMagmasCategory",
    "AdditiveMonoids",
    "AdditiveMonoidsCategory",
    "EilenbergMoore",
    "EndofunctorAlgebras",
    "Equifier",
    "EquifierCategory",
    "Groups",
    "GroupsCategory",
    "Inserter",
    "InserterCategory",
    "MagmaCategory",
    "Magmas",
    "MonoidCategory",
    "MonoidPairsCategory",
    "Monoids",
    "MultiplicativeMagmas",
    "MultiplicativeMagmasCategory",
    "MultiplicativeMonoids",
    "MultiplicativeMonoidsCategory",
    "PointedMagmas",
    "RingCategory",
    "Rings",
    "SemiringCategory",
    "Semirings",
]

class _StaticRoles_InserterCategory(sage_categories.cat.cat_constructions._StaticRoles_LimitSubcategory):
    class ObjectType(_StaticRoles_MagmaCategory.ObjectType):
        def carrier(self) -> CategoryOfCategories.ElementType: ...
        def structure(self) -> MorphismCategory.ObjectType: ...

    class ElementType(_StaticRoles_MagmaCategory.ElementType): ...

    class MorphismType(_StaticRoles_MagmaCategory.MorphismType):
        def underlying_morphism(self) -> MorphismCategory.ObjectType: ...
        def domain(self) -> InserterCategory.ObjectType: ...
        def codomain(self) -> InserterCategory.ObjectType: ...

class InserterCategory[
    ObjectRole = _StaticRoles_InserterCategory.ObjectType,
    ElementRole = _StaticRoles_InserterCategory.ElementType,
    MorphismRole = _StaticRoles_InserterCategory.MorphismType,
](_StaticRoles_InserterCategory, LimitSubcategory[ObjectRole, ElementRole, MorphismRole]):
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def algebra(self, carrier: CategoryOfCategories.ElementType, structure: MorphismCategory.ObjectType) -> ObjectRole: ...
    def homomorphism(self, source: CategoryOfCategories.ElementType, target: CategoryOfCategories.ElementType, arrow: MorphismCategory.ObjectType) -> MorphismRole: ...
    @cached_method
    def forgetful(self) -> Functor: ...
    @cached_method
    def defining_transformation(self) -> NaturalTransformation: ...

def Inserter(first: Functor, second: Functor, category_type: type[InserterCategory] | partial[InserterCategory] = ...) -> InserterCategory: ...

class _StaticRoles_EquifierCategory(sage_categories.cat.properties._StaticRoles_FullSubcategory):
    class ObjectType(
        sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ObjectType,
        sage_categories.sets.finite._StaticRoles_SetsCategory.ObjectType,
        sage_categories.cat.constructions._StaticRoles_LimitsCategory.ElementType,
    ): ...
    class ElementType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ElementType, sage_categories.sets.finite._StaticRoles_SetsCategory.ElementType): ...

    class MorphismType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.MorphismType, sage_categories.sets.finite._StaticRoles_SetsCategory.MorphismType):
        def domain(self) -> EquifierCategory.ObjectType: ...
        def codomain(self) -> EquifierCategory.ObjectType: ...

class EquifierCategory[
    ObjectRole = _StaticRoles_EquifierCategory.ObjectType,
    ElementRole = _StaticRoles_EquifierCategory.ElementType,
    MorphismRole = _StaticRoles_EquifierCategory.MorphismType,
](_StaticRoles_EquifierCategory, FullSubcategory[..., ..., ObjectRole, ElementRole, MorphismRole]):
    def __init__(self, first: NaturalTransformation, second: NaturalTransformation) -> None: ...
    def __call__(self, value: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...

def Equifier(first: NaturalTransformation, second: NaturalTransformation) -> EquifierCategory: ...
def EndofunctorAlgebras(endofunctor: Functor) -> InserterCategory: ...

class _StaticRoles_MagmaCategory(_StaticRoles_InserterCategory):
    class ObjectType(
        sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ObjectType,
        sage_categories.sets.finite._StaticRoles_SetsCategory.ObjectType,
        sage_categories.cat.constructions._StaticRoles_LimitsCategory.ElementType,
    ):
        def carrier(self) -> CategoryOfCategories.ElementType: ...
        def structure(self) -> MorphismCategory.ObjectType: ...
        def operation(self) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ElementType, sage_categories.sets.finite._StaticRoles_SetsCategory.ElementType): ...

    class MorphismType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.MorphismType, sage_categories.sets.finite._StaticRoles_SetsCategory.MorphismType):
        def underlying_morphism(self) -> MorphismCategory.ObjectType: ...
        def domain(self) -> MagmaCategory.ObjectType: ...
        def codomain(self) -> MagmaCategory.ObjectType: ...

class MagmaCategory(
    _StaticRoles_MagmaCategory, InserterCategory[_StaticRoles_MagmaCategory.ObjectType, _StaticRoles_MagmaCategory.ElementType, _StaticRoles_MagmaCategory.MorphismType]
):
    def __init__(self, diagram: Functor, tensor: Functor) -> None: ...
    def tensor(self) -> Functor: ...
    Commutative: Incomplete

def Magmas(structure: Functor | MonoidalStructuresCategory.ObjectType) -> MagmaCategory: ...
def PointedMagmas(tensor: Functor, unit: CategoryOfCategories.ElementType) -> InserterCategory: ...

class _StaticRoles_MonoidCategory(_StaticRoles_EquifierCategory):
    class ObjectType(_StaticRoles_EquifierCategory.ObjectType, _StaticRoles_InserterCategory.ObjectType):
        def operation(self) -> MorphismCategory.ObjectType: ...
        def unit_morphism(self) -> MorphismCategory.ObjectType: ...

    class ElementType(_StaticRoles_EquifierCategory.ElementType, _StaticRoles_InserterCategory.ElementType): ...

    class MorphismType(_StaticRoles_EquifierCategory.MorphismType, _StaticRoles_InserterCategory.MorphismType):
        def domain(self) -> MonoidCategory.ObjectType: ...
        def codomain(self) -> MonoidCategory.ObjectType: ...

class MonoidCategory(
    _StaticRoles_MonoidCategory, EquifierCategory[_StaticRoles_MonoidCategory.ObjectType, _StaticRoles_MonoidCategory.ElementType, _StaticRoles_MonoidCategory.MorphismType]
):
    def __init__(self, first: NaturalTransformation, second: NaturalTransformation, monoidal: MonoidalStructuresCategory.ObjectType) -> None: ...
    def monoidal_structure(self) -> MonoidalStructuresCategory.ObjectType: ...
    Group: Incomplete

    def homomorphism(self, source: MonoidCategory.ObjectType, target: MonoidCategory.ObjectType, arrow: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
    def __call__(self, operation: MorphismCategory.ObjectType, unit: MorphismCategory.ObjectType) -> MonoidCategory.ObjectType: ...
    @cached_method
    def to_magmas(self) -> Functor: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...

def Monoids(structure: Category | MonoidalStructuresCategory.ObjectType) -> MonoidCategory: ...

class _StaticRoles_GroupsCategory(sage_categories.cat.properties._StaticRoles_PropertySubcategory):
    class ObjectType(_StaticRoles_MonoidCategory.ObjectType):
        @cached_method
        def inversion(self) -> MorphismCategory.ObjectType: ...

    class ElementType(_StaticRoles_MonoidCategory.ElementType): ...

    class MorphismType(_StaticRoles_MonoidCategory.MorphismType):
        def domain(self) -> GroupsCategory.ObjectType: ...
        def codomain(self) -> GroupsCategory.ObjectType: ...

class GroupsCategory(
    _StaticRoles_GroupsCategory,
    PropertySubcategory[..., ..., _StaticRoles_GroupsCategory.ObjectType, _StaticRoles_GroupsCategory.ElementType, _StaticRoles_GroupsCategory.MorphismType],
): ...

def Groups(structure: Category | MonoidalStructuresCategory.ObjectType) -> GroupsCategory: ...

class _StaticRoles_NamedOperationCategory(sage_categories.cat.cat_constructions._StaticRoles_LimitSubcategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> NamedOperationCategory.ObjectType: ...
        def codomain(self) -> NamedOperationCategory.ObjectType: ...

class NamedOperationCategory[
    ObjectRole = _StaticRoles_NamedOperationCategory.ObjectType,
    ElementRole = _StaticRoles_NamedOperationCategory.ElementType,
    MorphismRole = _StaticRoles_NamedOperationCategory.MorphismType,
](_StaticRoles_NamedOperationCategory, LimitSubcategory[ObjectRole, ElementRole, MorphismRole]):
    Commutative: Incomplete

    def neutral_category(self) -> Category: ...
    def symbol_category(self) -> Category: ...
    def symbol(self) -> CategoryOfCategories.ElementType: ...
    def renamed(self, neutral_object: CategoryOfCategories.ElementType) -> ObjectRole: ...
    def homomorphism(self, source: ObjectRole, target: ObjectRole, arrow: MorphismCategory.ObjectType) -> MorphismRole: ...
    @cached_method
    def to_carrier(self) -> Functor: ...
    @cached_method
    def to_named_magmas(self) -> Functor: ...
    def named_magmas(self) -> NamedOperationCategory: ...
    @cached_method
    def to_named_monoids(self) -> Functor: ...
    def named_monoids(self) -> NamedOperationCategory: ...

class _StaticRoles_AdditiveMagmasCategory(_StaticRoles_NamedOperationCategory):
    class ObjectType(
        sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ObjectType,
        sage_categories.sets.finite._StaticRoles_SetsCategory.ObjectType,
        sage_categories.cat.constructions._StaticRoles_LimitsCategory.ElementType,
        sage_categories.cat.constructions._StaticRoles_ProductsCategory.ElementType,
    ):
        def __init__(self, data: FamilyObjectData) -> None: ...
        def addition(self) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ElementType, sage_categories.sets.finite._StaticRoles_SetsCategory.ElementType):
        def __add__(self, other: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...

    class MorphismType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.MorphismType, sage_categories.sets.finite._StaticRoles_SetsCategory.MorphismType):
        def domain(self) -> AdditiveMagmasCategory.ObjectType: ...
        def codomain(self) -> AdditiveMagmasCategory.ObjectType: ...

class AdditiveMagmasCategory(
    _StaticRoles_AdditiveMagmasCategory,
    NamedOperationCategory[_StaticRoles_AdditiveMagmasCategory.ObjectType, _StaticRoles_AdditiveMagmasCategory.ElementType, _StaticRoles_AdditiveMagmasCategory.MorphismType],
):
    def structure_functors(self) -> tuple[Functor, ...]: ...

class _StaticRoles_MultiplicativeMagmasCategory(_StaticRoles_NamedOperationCategory):
    class ObjectType(
        sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ObjectType,
        sage_categories.sets.finite._StaticRoles_SetsCategory.ObjectType,
        sage_categories.cat.constructions._StaticRoles_LimitsCategory.ElementType,
        sage_categories.cat.constructions._StaticRoles_ProductsCategory.ElementType,
    ):
        def __init__(self, data: FamilyObjectData) -> None: ...
        def multiplication(self) -> MorphismCategory.ObjectType: ...

    class ElementType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.ElementType, sage_categories.sets.finite._StaticRoles_SetsCategory.ElementType):
        def __mul__(self, other: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...

    class MorphismType(sage_categories.cat.cat_constructions._StaticRoles_LimitCategory.MorphismType, sage_categories.sets.finite._StaticRoles_SetsCategory.MorphismType):
        def domain(self) -> MultiplicativeMagmasCategory.ObjectType: ...
        def codomain(self) -> MultiplicativeMagmasCategory.ObjectType: ...

class MultiplicativeMagmasCategory(
    _StaticRoles_MultiplicativeMagmasCategory,
    NamedOperationCategory[
        _StaticRoles_MultiplicativeMagmasCategory.ObjectType, _StaticRoles_MultiplicativeMagmasCategory.ElementType, _StaticRoles_MultiplicativeMagmasCategory.MorphismType
    ],
):
    def structure_functors(self) -> tuple[Functor, ...]: ...

class _StaticRoles_NamedMonoidsCategory(_StaticRoles_NamedOperationCategory):
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory): ...
    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> NamedMonoidsCategory.ObjectType: ...
        def codomain(self) -> NamedMonoidsCategory.ObjectType: ...

class NamedMonoidsCategory[
    ObjectRole = _StaticRoles_NamedMonoidsCategory.ObjectType,
    ElementRole = _StaticRoles_NamedMonoidsCategory.ElementType,
    MorphismRole = _StaticRoles_NamedMonoidsCategory.MorphismType,
](_StaticRoles_NamedMonoidsCategory, NamedOperationCategory[ObjectRole, ElementRole, MorphismRole]):
    Group: Incomplete

class _StaticRoles_AdditiveMonoidsCategory(_StaticRoles_NamedMonoidsCategory):
    class ObjectType(_StaticRoles_AdditiveMagmasCategory.ObjectType):
        def __init__(self, data: FamilyObjectData) -> None: ...
        def zero(self) -> CategoryOfCategories.ElementType: ...

    class ElementType(_StaticRoles_AdditiveMagmasCategory.ElementType): ...

    class MorphismType(_StaticRoles_AdditiveMagmasCategory.MorphismType):
        def domain(self) -> AdditiveMonoidsCategory.ObjectType: ...
        def codomain(self) -> AdditiveMonoidsCategory.ObjectType: ...

class AdditiveMonoidsCategory(
    _StaticRoles_AdditiveMonoidsCategory,
    NamedMonoidsCategory[_StaticRoles_AdditiveMonoidsCategory.ObjectType, _StaticRoles_AdditiveMonoidsCategory.ElementType, _StaticRoles_AdditiveMonoidsCategory.MorphismType],
):
    def named_magmas(self) -> AdditiveMagmasCategory: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...

class _StaticRoles_MultiplicativeMonoidsCategory(_StaticRoles_NamedMonoidsCategory):
    class ObjectType(_StaticRoles_MultiplicativeMagmasCategory.ObjectType):
        def __init__(self, data: FamilyObjectData) -> None: ...
        def one(self) -> CategoryOfCategories.ElementType: ...

    class ElementType(_StaticRoles_MultiplicativeMagmasCategory.ElementType): ...

    class MorphismType(_StaticRoles_MultiplicativeMagmasCategory.MorphismType):
        def domain(self) -> MultiplicativeMonoidsCategory.ObjectType: ...
        def codomain(self) -> MultiplicativeMonoidsCategory.ObjectType: ...

class MultiplicativeMonoidsCategory(
    _StaticRoles_MultiplicativeMonoidsCategory,
    NamedMonoidsCategory[
        _StaticRoles_MultiplicativeMonoidsCategory.ObjectType, _StaticRoles_MultiplicativeMonoidsCategory.ElementType, _StaticRoles_MultiplicativeMonoidsCategory.MorphismType
    ],
):
    def named_magmas(self) -> MultiplicativeMagmasCategory: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...

class _StaticRoles_AdditiveGroupsCategory(_StaticRoles_NamedOperationCategory):
    class ObjectType(_StaticRoles_AdditiveMonoidsCategory.ObjectType):
        def __init__(self, data: FamilyObjectData) -> None: ...
        def negation(self) -> MorphismCategory.ObjectType: ...

    class ElementType(_StaticRoles_AdditiveMonoidsCategory.ElementType):
        def __neg__(self) -> CategoryOfCategories.ElementType: ...
        def __sub__(self, other: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...

    class MorphismType(_StaticRoles_AdditiveMonoidsCategory.MorphismType):
        def domain(self) -> AdditiveGroupsCategory.ObjectType: ...
        def codomain(self) -> AdditiveGroupsCategory.ObjectType: ...

class AdditiveGroupsCategory(
    _StaticRoles_AdditiveGroupsCategory,
    NamedOperationCategory[_StaticRoles_AdditiveGroupsCategory.ObjectType, _StaticRoles_AdditiveGroupsCategory.ElementType, _StaticRoles_AdditiveGroupsCategory.MorphismType],
):
    def named_monoids(self) -> AdditiveMonoidsCategory: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...

def AdditiveGroups(structure: Category | MonoidalStructuresCategory.ObjectType) -> AdditiveGroupsCategory: ...
def AdditiveMagmas(structure: Functor | MonoidalStructuresCategory.ObjectType) -> AdditiveMagmasCategory: ...
def MultiplicativeMagmas(structure: Functor | MonoidalStructuresCategory.ObjectType) -> MultiplicativeMagmasCategory: ...
def AdditiveMonoids(structure: Category | MonoidalStructuresCategory.ObjectType) -> AdditiveMonoidsCategory: ...
def MultiplicativeMonoids(structure: Category | MonoidalStructuresCategory.ObjectType) -> MultiplicativeMonoidsCategory: ...

class _StaticRoles_MonoidPairsCategory(sage_categories.cat.cat_constructions._StaticRoles_LimitSubcategory):
    class ObjectType(
        sage_categories.cat.properties._StaticRoles_InverseImageSubcategory.ObjectType,
        _StaticRoles_MultiplicativeMonoidsCategory.ObjectType,
        _StaticRoles_AdditiveMonoidsCategory.ObjectType,
    ): ...
    class ElementType(
        sage_categories.cat.properties._StaticRoles_InverseImageSubcategory.ElementType,
        _StaticRoles_MultiplicativeMonoidsCategory.ElementType,
        _StaticRoles_AdditiveMonoidsCategory.ElementType,
    ): ...

    class MorphismType(
        sage_categories.cat.properties._StaticRoles_InverseImageSubcategory.MorphismType,
        _StaticRoles_MultiplicativeMonoidsCategory.MorphismType,
        _StaticRoles_AdditiveMonoidsCategory.MorphismType,
    ):
        def domain(self) -> MonoidPairsCategory.ObjectType: ...
        def codomain(self) -> MonoidPairsCategory.ObjectType: ...

class MonoidPairsCategory(
    _StaticRoles_MonoidPairsCategory,
    LimitSubcategory[_StaticRoles_MonoidPairsCategory.ObjectType, _StaticRoles_MonoidPairsCategory.ElementType, _StaticRoles_MonoidPairsCategory.MorphismType],
):
    @cached_method
    def to_additive(self) -> Functor: ...
    @cached_method
    def to_multiplicative(self) -> Functor: ...
    @cached_method
    def to_carrier(self) -> Functor: ...
    def homomorphism(
        self, source: MonoidPairsCategory.ObjectType, target: MonoidPairsCategory.ObjectType, arrow: MorphismCategory.ObjectType
    ) -> MonoidPairsCategory.MorphismType: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...

class _StaticRoles_SemiringCategory(_StaticRoles_EquifierCategory):
    class ObjectType(_StaticRoles_EquifierCategory.ObjectType, _StaticRoles_MonoidPairsCategory.ObjectType): ...
    class ElementType(_StaticRoles_EquifierCategory.ElementType, _StaticRoles_MonoidPairsCategory.ElementType): ...

    class MorphismType(_StaticRoles_EquifierCategory.MorphismType, _StaticRoles_MonoidPairsCategory.MorphismType):
        def domain(self) -> SemiringCategory.ObjectType: ...
        def codomain(self) -> SemiringCategory.ObjectType: ...

class SemiringCategory(
    _StaticRoles_SemiringCategory,
    EquifierCategory[_StaticRoles_SemiringCategory.ObjectType, _StaticRoles_SemiringCategory.ElementType, _StaticRoles_SemiringCategory.MorphismType],
):
    def __init__(self, first: NaturalTransformation, second: NaturalTransformation, monoidal: MonoidalStructuresCategory.ObjectType, pairs: MonoidPairsCategory) -> None: ...
    def monoidal_structure(self) -> MonoidalStructuresCategory.ObjectType: ...
    @cached_method
    def to_additive(self) -> Functor: ...
    @cached_method
    def to_multiplicative(self) -> Functor: ...
    @cached_method
    def to_carrier(self) -> Functor: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def homomorphism(self, source: SemiringCategory.ObjectType, target: SemiringCategory.ObjectType, arrow: MorphismCategory.ObjectType) -> SemiringCategory.MorphismType: ...
    def __call__(
        self, addition: MorphismCategory.ObjectType, zero: MorphismCategory.ObjectType, multiplication: MorphismCategory.ObjectType, one: MorphismCategory.ObjectType
    ) -> SemiringCategory.ObjectType: ...

def Semirings(base: Category) -> SemiringCategory: ...

class _StaticRoles_RingCategory(sage_categories.cat.cat_constructions._StaticRoles_LimitSubcategory):
    class ObjectType(_StaticRoles_SemiringCategory.ObjectType, _StaticRoles_AdditiveGroupsCategory.ObjectType): ...
    class ElementType(_StaticRoles_SemiringCategory.ElementType, _StaticRoles_AdditiveGroupsCategory.ElementType): ...

    class MorphismType(_StaticRoles_SemiringCategory.MorphismType, _StaticRoles_AdditiveGroupsCategory.MorphismType):
        def domain(self) -> RingCategory.ObjectType: ...
        def codomain(self) -> RingCategory.ObjectType: ...

class RingCategory(
    _StaticRoles_RingCategory, LimitSubcategory[_StaticRoles_RingCategory.ObjectType, _StaticRoles_RingCategory.ElementType, _StaticRoles_RingCategory.MorphismType]
):
    def __init__(self, diagram: Functor, monoidal: MonoidalStructuresCategory.ObjectType) -> None: ...
    def monoidal_structure(self) -> MonoidalStructuresCategory.ObjectType: ...
    @cached_method
    def to_semiring(self) -> Functor: ...
    @cached_method
    def to_additive_group(self) -> Functor: ...
    @cached_method
    def forgetful(self) -> Functor: ...
    def limit_construction(self, shape: Category) -> Callable[[Functor], CategoryOfCategories.ElementType]: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def __call__(
        self, addition: MorphismCategory.ObjectType, zero: MorphismCategory.ObjectType, multiplication: MorphismCategory.ObjectType, one: MorphismCategory.ObjectType
    ) -> RingCategory.ObjectType: ...
    def homomorphism(self, source: RingCategory.ObjectType, target: RingCategory.ObjectType, arrow: MorphismCategory.ObjectType) -> RingCategory.MorphismType: ...
    def opposite_ring(self, ring: RingCategory.ObjectType) -> RingCategory.ObjectType: ...
    @cached_method
    def opposite_functor(self) -> Functor: ...

def Rings(base: Category) -> RingCategory: ...
def EilenbergMoore(endofunctor: Functor, unit: NaturalTransformation, multiplication: NaturalTransformation) -> EquifierCategory: ...
def _shear(monoid: MonoidCategory.ObjectType) -> MorphismCategory.ObjectType: ...
