from collections.abc import Callable
from fractions import Fraction

from sage_categories.algebra.local_fields import (
    ExactLocalFieldPresentation,
    ExactLocalValue,
)
from sage_categories.cat.category import CategoryOfCategories
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.geometry.spaces import TopologicalSpacesCategory
from sage_categories.geometry.topological_rings import TopologicalRingsCategory

type IntegralityCertificate = Callable[[int], bool]
type LocalComponentRule = Callable[[int], ExactLocalValue]
type LocalCondition = Callable[[ExactLocalValue], bool | None]

class AdeleValue:
    real: ExactLocalValue
    exceptional_primes: frozenset[int]
    def finite_component(self, prime: int) -> ExactLocalValue: ...
    def component(self, place: str | int) -> ExactLocalValue: ...
    def certifies_integral_at(self, prime: int) -> bool: ...

class AdeleOpen:
    kind: str
    @property
    def exceptional_primes(self) -> frozenset[int]: ...
    def uses_integral_condition(self, prime: int) -> bool: ...
    def contains(self, value: AdeleValue) -> bool | None: ...

class AdelePresentation:
    ring: CategoryOfCategories.ElementType
    space: TopologicalSpacesCategory.ObjectType
    topological_ring: TopologicalRingsCategory.ObjectType
    rational_field: ExactLocalFieldPresentation
    real_field: ExactLocalFieldPresentation
    primes: CategoryOfCategories.ElementType
    empty_open: AdeleOpen
    whole_open: AdeleOpen
    def local_field(self, prime: int) -> ExactLocalFieldPresentation: ...
    def point(self, value: AdeleValue) -> CategoryOfCategories.ElementType: ...
    def value(self, real: ExactLocalValue, finite_components: LocalComponentRule, exceptional_primes: frozenset[int], integrality_certificate: IntegralityCertificate) -> AdeleValue: ...
    def zero_value(self) -> AdeleValue: ...
    def one_value(self) -> AdeleValue: ...
    def diagonal_value(self, value: Fraction | int) -> AdeleValue: ...
    def component_map(self, place: str | int) -> MorphismCategory.ObjectType: ...
    def diagonal_map(self) -> MorphismCategory.ObjectType: ...
    def basic_open(self, real_condition: LocalCondition, finite_conditions: dict[int, LocalCondition]) -> AdeleOpen: ...
    def open_object(self, open_set: AdeleOpen) -> CategoryOfCategories.ElementType: ...

def adeles_of_rationals() -> AdelePresentation: ...
