from sage_categories.cat.cat_constructions import LimitSubcategory
from sage_categories.cat.functors import Functor
from sage_categories.cat.modules import ModuleCategory
from sage_categories.cat.monoidal import ActionsCategory, MonoidalStructuresCategory
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.cat.structured_objects import MonoidCategory

__all__ = ["AlgebraCategory", "Algebras", "select_module_monoidal_structure"]

class AlgebraCategory(LimitSubcategory):
    class ObjectType: ...
    class ElementType: ...
    class MorphismType: ...

    def monoid_category(self) -> MonoidCategory: ...
    def monoidal_structure(self) -> MonoidalStructuresCategory.ObjectType: ...
    def base(self) -> MonoidCategory.ObjectType: ...
    def module_category(self) -> ModuleCategory: ...
    def monoid_presentation(self) -> Functor: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def from_monoid(
        self, monoid: MonoidCategory.ObjectType
    ) -> AlgebraCategory.ObjectType: ...
    def algebra(
        self,
        multiplication: MorphismCategory.ObjectType,
        unit: MorphismCategory.ObjectType,
    ) -> AlgebraCategory.ObjectType: ...
    def homomorphism(
        self,
        source: AlgebraCategory.ObjectType,
        target: AlgebraCategory.ObjectType,
        arrow: MorphismCategory.ObjectType,
    ) -> AlgebraCategory.MorphismType: ...
    def to_modules(self) -> Functor: ...
    def U_R(self) -> Functor: ...
    def to_sets(self) -> Functor: ...

def select_module_monoidal_structure(
    modules: ModuleCategory, monoidal: MonoidalStructuresCategory.ObjectType
) -> None: ...
def Algebras(
    base: MonoidCategory.ObjectType,
    context: ActionsCategory.ObjectType | MonoidalStructuresCategory.ObjectType,
) -> AlgebraCategory: ...
