"""OSCAR-backed polynomial, quotient, and localization constructions in owned commutative rings.

The mathematical layer retains only owned construction data.  Conversion to and from
OSCAR lives in ``algebra._firewall.commutative_rings``.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import cache

from sage_categories.algebra._firewall import commutative_rings as _backend
from sage_categories.cat.category import CategoryOfCategories
from sage_categories.cat.morphisms import MorphismCategory

__all__ = [
    "PrimeIdeal",
    "induced_stalk_map",
    "induced_stalk_map_to",
    "integer_ring",
    "inverse_unit",
    "localization_extension",
    "localize_at_prime",
    "polynomial_ring",
    "presented_ring_homomorphism",
    "prime_contains",
    "prime_field",
    "prime_generators",
    "prime_ideal",
    "prime_ideal_equal",
    "prime_ideal_extension",
    "prime_ideal_preimage",
    "principal_localization",
    "quotient_ring",
]


@dataclass(frozen=True, eq=False, slots=True)
class _IntegerRingConstruction:
    pass


@dataclass(frozen=True, eq=False, slots=True)
class _PrimeFieldConstruction:
    characteristic: int


@dataclass(frozen=True, eq=False, slots=True)
class _PolynomialConstruction:
    base: CategoryOfCategories.ElementType
    names: tuple[str, ...]


@dataclass(frozen=True, eq=False, slots=True)
class _QuotientConstruction:
    source: CategoryOfCategories.ElementType
    relations: tuple[CategoryOfCategories.ElementType, ...]


@dataclass(frozen=True, eq=False, slots=True)
class _LocalizationConstruction:
    source: CategoryOfCategories.ElementType
    element: CategoryOfCategories.ElementType


@dataclass(frozen=True, eq=False, slots=True)
class PrimeIdeal:
    """An owned prime ideal of one commutative ring."""

    ring: CategoryOfCategories.ElementType
    generators: tuple[CategoryOfCategories.ElementType, ...]


@dataclass(frozen=True, eq=False, slots=True)
class _PrimeLocalizationConstruction:
    source: CategoryOfCategories.ElementType
    prime: PrimeIdeal


def _construction(ring: CategoryOfCategories.ElementType) -> object:
    return _backend.construction(ring)


@cache
def integer_ring() -> CategoryOfCategories.ElementType:
    """The integer ring ``ZZ`` as the owned commutative ring underlying ``Spec(ZZ)``."""
    return _backend.integer_ring(_IntegerRingConstruction())


def prime_field(characteristic: int) -> CategoryOfCategories.ElementType:
    """The prime field ``F_p`` as an owned commutative ring."""
    assert characteristic > 1
    return _backend.prime_field(characteristic, _PrimeFieldConstruction(characteristic))


def polynomial_ring(
    base: CategoryOfCategories.ElementType,
    names: tuple[str, ...],
) -> tuple[CategoryOfCategories.ElementType, tuple[CategoryOfCategories.ElementType, ...]]:
    """The polynomial ring ``base[names]`` and its ordered owned generator points."""
    assert names and len(set(names)) == len(names)
    return _backend.polynomial_ring(base, names, _PolynomialConstruction(base, names))


def quotient_ring(
    source: CategoryOfCategories.ElementType,
    relations: tuple[CategoryOfCategories.ElementType, ...],
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]:
    """The presented quotient ``source/(relations)`` and its canonical projection."""
    assert relations and all(relation.parent() is source for relation in relations)
    return _backend.quotient_ring(source, relations, _QuotientConstruction(source, relations))


def principal_localization(
    source: CategoryOfCategories.ElementType,
    element: CategoryOfCategories.ElementType,
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]:
    """The principal localization ``source[element^-1]`` and its canonical map."""
    assert element.parent() is source
    return _backend.principal_localization(source, element, _LocalizationConstruction(source, element))


def prime_ideal(
    ring: CategoryOfCategories.ElementType,
    generators: tuple[CategoryOfCategories.ElementType, ...],
) -> PrimeIdeal:
    """The checked prime ideal generated by the supplied owned ring elements."""
    assert generators and all(generator.parent() is ring for generator in generators)
    result = PrimeIdeal(ring, generators)
    _backend.retain_prime_ideal(result, ring, generators)
    return result


def prime_ideal_preimage(
    mapping: MorphismCategory.ObjectType,
    target_prime: PrimeIdeal,
) -> PrimeIdeal:
    """The inverse-image prime under an owned commutative-ring map."""
    assert mapping.codomain() is target_prime.ring
    result = PrimeIdeal(mapping.domain(), ())
    _backend.retain_prime_ideal_preimage(result, mapping, target_prime)
    return result


def prime_ideal_extension(
    mapping: MorphismCategory.ObjectType,
    source_prime: PrimeIdeal,
) -> PrimeIdeal:
    """Extend a prime ideal through a map when its generated image is prime."""
    assert mapping.domain() is source_prime.ring
    result = PrimeIdeal(mapping.codomain(), ())
    _backend.retain_prime_ideal_extension(result, mapping, source_prime)
    return result


def prime_generators(
    prime: PrimeIdeal,
) -> tuple[CategoryOfCategories.ElementType, ...]:
    """The exact owned generator family of a retained OSCAR prime ideal."""
    return _backend.prime_ideal_generators(prime)


def prime_contains(
    prime: PrimeIdeal,
    element: CategoryOfCategories.ElementType,
) -> bool:
    """Decide whether ``element`` belongs to the retained prime ideal."""
    assert element.parent() is prime.ring
    return _backend.prime_ideal_contains(prime, element)


def prime_ideal_equal(first: PrimeIdeal, second: PrimeIdeal) -> bool:
    """Decide equality of two retained prime ideals by mutual generator containment."""
    match first.ring is second.ring:
        case False:
            return False
        case True:
            pass
    return all(prime_contains(second, generator) for generator in prime_generators(first)) and all(
        prime_contains(first, generator) for generator in prime_generators(second)
    )


def localize_at_prime(
    prime: PrimeIdeal,
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]:
    """The local ring at ``prime`` and its canonical localization map."""
    return _backend.localization_at_prime(
        prime.ring,
        prime,
        _PrimeLocalizationConstruction(prime.ring, prime),
    )


def induced_stalk_map(
    mapping: MorphismCategory.ObjectType,
    target_prime: PrimeIdeal,
) -> tuple[PrimeIdeal, CategoryOfCategories.ElementType, CategoryOfCategories.ElementType, MorphismCategory.ObjectType]:
    """The induced local map at a target prime of ``mapping.domain() -> mapping.codomain()``."""
    source_prime = prime_ideal_preimage(mapping, target_prime)
    source_local, _ = localize_at_prime(source_prime)
    target_local, target_localization = localize_at_prime(target_prime)
    arrow = _backend.stalk_map(mapping, source_local, target_local, target_localization)
    return source_prime, source_local, target_local, arrow


def induced_stalk_map_to(
    mapping: MorphismCategory.ObjectType,
    target_prime: PrimeIdeal,
    target_local: CategoryOfCategories.ElementType,
    target_localization: MorphismCategory.ObjectType,
) -> tuple[PrimeIdeal, CategoryOfCategories.ElementType, MorphismCategory.ObjectType, MorphismCategory.ObjectType]:
    """The stalk map landing in an already retained target local ring."""
    assert target_localization.domain() is target_prime.ring
    assert target_localization.codomain() is target_local
    target_construction = _construction(target_local)
    assert isinstance(target_construction, _PrimeLocalizationConstruction)
    assert target_construction.prime is target_prime
    source_prime = prime_ideal_preimage(mapping, target_prime)
    source_local, source_localization = localize_at_prime(source_prime)
    return (
        source_prime,
        source_local,
        source_localization,
        _backend.stalk_map(mapping, source_local, target_local, target_localization),
    )


def _principal_localization_from_native(
    source: CategoryOfCategories.ElementType,
    element: CategoryOfCategories.ElementType,
    native_localized: object,
    native_map: object,
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]:
    """Reconstruct a principal localization supplied by another private firewall."""
    assert element.parent() is source
    return _backend.principal_localization_from_native(
        source,
        element,
        native_localized,
        native_map,
        _LocalizationConstruction(source, element),
    )


def presented_ring_homomorphism(
    source: CategoryOfCategories.ElementType,
    target: CategoryOfCategories.ElementType,
    generator_images: tuple[CategoryOfCategories.ElementType, ...],
) -> MorphismCategory.ObjectType:
    """The checked map from a polynomial/quotient presentation with these generator images."""
    construction = _construction(source)
    assert isinstance(construction, (_PolynomialConstruction, _QuotientConstruction))
    assert all(image.parent() is target for image in generator_images)
    return _backend.presented_ring_homomorphism(source, target, generator_images)


def localization_extension(
    localized: CategoryOfCategories.ElementType,
    target: CategoryOfCategories.ElementType,
    base_map: MorphismCategory.ObjectType,
) -> MorphismCategory.ObjectType:
    """Extend a base map uniquely across a retained principal localization."""
    return _backend.localization_extension(localized, target, base_map)


def inverse_unit(element: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType:
    """The multiplicative inverse of a unit in an OSCAR-backed commutative ring."""
    return _backend.inverse_unit(element)
