from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from sage_categories.cat.category import CategoryOfCategories
from sage_categories.cat.modules import ModuleCategory
from sage_categories.cat.morphisms import MorphismCategory
from sage_categories.cat.structured_objects import MonoidCategory

type Word = tuple[int, ...]

@dataclass(frozen=True, eq=False, slots=True)
class IntegerFreeAssociativeConstruction:
    names: tuple[str, ...]
    word_module: CategoryOfCategories.ElementType

def integer_free_associative_algebra(names: Sequence[str] = ...) -> MonoidCategory.ObjectType: ...
def free_associative_underlying_module(algebra: MonoidCategory.ObjectType) -> ModuleCategory.ObjectType: ...
def free_associative_element(algebra: MonoidCategory.ObjectType, terms: Mapping[Word, int]) -> CategoryOfCategories.ElementType: ...
def free_associative_generator(algebra: MonoidCategory.ObjectType, position: int) -> CategoryOfCategories.ElementType: ...
def free_associative_coefficients(algebra: MonoidCategory.ObjectType, element: CategoryOfCategories.ElementType) -> dict[Word, int]: ...
def free_associative_product(algebra: MonoidCategory.ObjectType, left: CategoryOfCategories.ElementType, right: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
def free_associative_substitution(algebra: MonoidCategory.ObjectType, images: Sequence[CategoryOfCategories.ElementType]) -> MorphismCategory.ObjectType: ...
def free_associative_underlying_morphism(algebra_morphism: MorphismCategory.ObjectType) -> MorphismCategory.ObjectType: ...
