from collections.abc import Hashable, Mapping

from sage_categories.cat.category import CategoryOfCategories
from sage_categories.cat.modules import ModuleCategory

def integer_scalar_monoid() -> CategoryOfCategories.ElementType: ...
def integer_regular_module() -> ModuleCategory.ObjectType: ...
def indexed_free_integer_module(index_set: CategoryOfCategories.ElementType) -> ModuleCategory.ObjectType: ...
def indexed_free_integer_element(module: ModuleCategory.ObjectType, terms: Mapping[Hashable, int]) -> CategoryOfCategories.ElementType: ...
def indexed_free_integer_support(module: ModuleCategory.ObjectType, element: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
