from fractions import Fraction

from sage_categories.cat.category import CategoryOfCategories
from sage_categories.cat.morphisms import MorphismCategory

class ExactLocalValue:
    place: str | int
    @staticmethod
    def rational(place: str | int, value: Fraction | int) -> ExactLocalValue: ...
    @staticmethod
    def atom(place: str | int, name: object, valuation: int | None = None) -> ExactLocalValue: ...
    def rational_value(self) -> Fraction | None: ...
    def valuation(self) -> int | float | None: ...
    def is_integral(self) -> bool | None: ...

class ExactLocalFieldPresentation:
    place: str | int
    ring: CategoryOfCategories.ElementType
    integers: CategoryOfCategories.ElementType | None
    def value(self, datum: Fraction | int) -> CategoryOfCategories.ElementType: ...
    def embed_rational(self, rational_ring: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...

def exact_rational_field() -> ExactLocalFieldPresentation: ...
def exact_real_field() -> ExactLocalFieldPresentation: ...
def exact_padic_field(prime: int) -> ExactLocalFieldPresentation: ...
def prime_indices() -> CategoryOfCategories.ElementType: ...
