from collections.abc import Callable, Iterator
from contextlib import contextmanager
from functools import partial

from sage_categories.cat.category import Category as Category
from sage_categories.cat.functors import Functor as Functor
from sage_categories.kernel.sage_runtime import cached_function as cached_function

__all__ = ["category_construction_functors", "complete_constructions", "deferred_category", "identity_key", "retained_involution"]

def identity_key[Value](*values: Value) -> tuple[tuple[int, Value], ...]: ...
@contextmanager
def complete_constructions() -> Iterator[None]: ...
def category_construction_functors(category: Category) -> tuple[Functor, ...]: ...
def deferred_category[Value: Category, Parameter](constructor: type[Value] | partial[Value], parameter: Parameter) -> Value: ...
def retained_involution[Value](construct: Callable[[Value], Value]) -> Callable[[Value], Value]: ...
