#!/bin/sh
# SAGE_BIN adapter for a conda-forge Sage installation.
#
# conda-forge's `sage` entry point is `sage.cli`, which lacks the classic launcher modes
# that scripts/run_sage_test_case.sh and the ai-review-ci Sage justfile call:
# `sage -python ...` and `sage --preparse FILE.sage` (writing FILE.sage.py).
# This adapter supplies those two modes from the same installation and forwards every
# other invocation to the conda `sage` unchanged.
#
# Usage: SAGE_PREFIX=/path/to/conda/env SAGE_BIN=scripts/sage_conda_launcher.sh ...
set -eu
prefix=${SAGE_PREFIX:?SAGE_PREFIX must name the conda environment holding Sage}

case "${1:-}" in
    -python)
        shift
        exec "$prefix/bin/python" "$@"
        ;;
    --preparse)
        shift
        for source in "$@"; do
            # Same output as the classic sage-preparse script: its header followed by
            # sage.repl.preparse.preparse_file of the source.
            "$prefix/bin/python" - "$source" <<'EOF'
import os
import sys

from sage.repl.preparse import preparse_file

source = sys.argv[1]
with open(source) as handle:
    body = preparse_file(handle.read())
with open(source + ".py", "w") as handle:
    handle.write(
        f"# This file was *autogenerated* from the file {os.path.basename(source)}.\n"
        "from sage.all_cmdline import *   # import sage library\n\n"
        + body
    )
EOF
        done
        ;;
    *)
        exec "$prefix/bin/sage" "$@"
        ;;
esac
