from collections.abc import Callable, Iterable
from typing import Protocol

from sage_categories.theories.posets import PosetElement

type PartialOrder = Callable[[PosetElement, PosetElement], bool]


class ExternalFinitePoset(Protocol):
    def covers(self, lower: PosetElement, upper: PosetElement) -> bool: ...
    def lower_covers(self, member: PosetElement) -> Iterable[PosetElement]: ...
    def upper_covers(self, member: PosetElement) -> Iterable[PosetElement]: ...
    def common_lower_covers(
        self,
        members: Iterable[PosetElement],
    ) -> Iterable[PosetElement]: ...
    def common_upper_covers(
        self,
        members: Iterable[PosetElement],
    ) -> Iterable[PosetElement]: ...
    def open_interval(
        self,
        lower: PosetElement,
        upper: PosetElement,
    ) -> Iterable[PosetElement]: ...
    def closed_interval(
        self,
        lower: PosetElement,
        upper: PosetElement,
    ) -> Iterable[PosetElement]: ...
    def order_ideal(
        self,
        members: Iterable[PosetElement],
    ) -> Iterable[PosetElement]: ...
    def order_filter(
        self,
        members: Iterable[PosetElement],
    ) -> Iterable[PosetElement]: ...
    def minimal_elements(self) -> Iterable[PosetElement]: ...
    def maximal_elements(self) -> Iterable[PosetElement]: ...
    def has_bottom(self) -> bool: ...
    def bottom(self) -> PosetElement: ...
    def has_top(self) -> bool: ...
    def top(self) -> PosetElement: ...
    def is_bounded(self) -> bool: ...
    def height(self) -> int: ...
    def width(self) -> int: ...
    def rank(self, member: PosetElement | None = None) -> int: ...
    def level_sets(self) -> Iterable[Iterable[PosetElement]]: ...
    def is_ranked(self) -> bool: ...
    def is_graded(self) -> bool: ...
    def is_chain(self) -> bool: ...
    def is_chain_of_poset(self, members: Iterable[PosetElement]) -> bool: ...
    def is_antichain_of_poset(
        self,
        members: Iterable[PosetElement],
    ) -> bool: ...


class ExternalPosetConstructor(Protocol):
    def __call__(
        self,
        presentation: tuple[tuple[PosetElement, ...], PartialOrder],
        *,
        facade: bool,
    ) -> ExternalFinitePoset: ...
