from collections.abc import Callable, Iterable
from typing import Literal, Protocol

from sage_categories.theories.sets import SetElement

type PartialOrder = Callable[[SetElement, SetElement], bool]


class ExternalFinitePoset(Protocol):
    def covers(self, lower: SetElement, upper: SetElement) -> bool: ...
    def lower_covers(self, member: SetElement) -> Iterable[SetElement]: ...
    def upper_covers(self, member: SetElement) -> Iterable[SetElement]: ...
    def common_lower_covers(
        self,
        members: Iterable[SetElement],
    ) -> Iterable[SetElement]: ...
    def common_upper_covers(
        self,
        members: Iterable[SetElement],
    ) -> Iterable[SetElement]: ...
    def open_interval(
        self,
        lower: SetElement,
        upper: SetElement,
    ) -> Iterable[SetElement]: ...
    def closed_interval(
        self,
        lower: SetElement,
        upper: SetElement,
    ) -> Iterable[SetElement]: ...
    def order_ideal(
        self,
        members: Iterable[SetElement],
    ) -> Iterable[SetElement]: ...
    def order_filter(
        self,
        members: Iterable[SetElement],
    ) -> Iterable[SetElement]: ...
    def minimal_elements(self) -> Iterable[SetElement]: ...
    def maximal_elements(self) -> Iterable[SetElement]: ...
    def has_bottom(self) -> bool: ...
    def bottom(self) -> SetElement: ...
    def has_top(self) -> bool: ...
    def top(self) -> SetElement: ...
    def is_bounded(self) -> bool: ...
    def height(self) -> int: ...
    def width(self) -> int: ...
    def rank(self, member: SetElement | None = None) -> int: ...
    def level_sets(self) -> Iterable[Iterable[SetElement]]: ...
    def is_ranked(self) -> bool: ...
    def is_graded(self) -> bool: ...
    def is_chain(self) -> bool: ...
    def is_chain_of_poset(self, members: Iterable[SetElement]) -> bool: ...
    def is_antichain_of_poset(
        self,
        members: Iterable[SetElement],
    ) -> bool: ...
    def linear_extension(self) -> Iterable[SetElement]: ...


class ExternalPosetConstructor(Protocol):
    def __call__(
        self,
        presentation: tuple[tuple[SetElement, ...], PartialOrder],
        *,
        facade: Literal[True],
    ) -> ExternalFinitePoset: ...
