from sage_categories.kernel.compiler import install_method_result_projection_reader as install_method_result_projection_reader

def method_result_projections() -> dict[str, tuple[str, tuple[tuple[int, int], ...]]]: ...
def install() -> None: ...
