import sage_categories.cat.category
import sage_categories.cat.morphisms
import sage_categories.kernel.roles
from sage_categories.cat.category import Category as Category
from sage_categories.cat.predicates import Proposition as Proposition
from sage_categories.cat.predicates import register_handler as register_handler

__all__ = ["Cardinal", "CardinalCategory"]

class _StaticRoles_CardinalCategory:
    class ObjectType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ObjectOfCategory):
        def __init__(self, value: int) -> None: ...
        def value(self) -> int: ...
        def __int__(self) -> int: ...
        def __index__(self) -> int: ...

    class ElementType(sage_categories.cat.category._StaticRoles_CategoryOfCategories.ElementType, sage_categories.kernel.roles.ElementOfObject): ...

    class MorphismType(sage_categories.cat.morphisms._StaticRoles_MorphismCategory.ObjectType):
        def domain(self) -> CardinalCategory.ObjectType: ...
        def codomain(self) -> CardinalCategory.ObjectType: ...

class CardinalCategory(
    _StaticRoles_CardinalCategory,
    Category[..., ..., _StaticRoles_CardinalCategory.ObjectType, _StaticRoles_CardinalCategory.ElementType, _StaticRoles_CardinalCategory.MorphismType],
):
    def __call__(self, value: int) -> CardinalCategory.ObjectType: ...
    def zero(self) -> CardinalCategory.ObjectType: ...

def Cardinal() -> CardinalCategory: ...
