from sage_categories.cat.category import CategoryDeclaration as CategoryDeclaration
from sage_categories.cat.functors import FunctorDeclaration as FunctorDeclaration
from sage_categories.ordinals.category import OrdinalObjectDeclaration as OrdinalObjectDeclaration
from sage_categories.sets.elements import SetElementDeclaration as SetElementDeclaration
from sage_categories.sets.maps import SetMapDeclaration as SetMapDeclaration
from sage_categories.sets.objects import SetObjectDeclaration as SetObjectDeclaration
from _typeshed import Incomplete
from dataclasses import dataclass
from sage_categories.cat.category import Category as Category
from sage_categories.cat.functors import Fun as Fun, Functor as Functor
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.kernel.construction import MorphismConstructionInput as MorphismConstructionInput, ObjectConstructionInput as ObjectConstructionInput, retained_morphism_input as retained_morphism_input, retained_object_input as retained_object_input
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, ask as ask, conjunction as conjunction, disjunction as disjunction, negation as negation
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, role_of as role_of
from sage_categories.ordinals.category import OrdinalObject as OrdinalObject, Ordinals as Ordinals, bind_cardinals as bind_cardinals
from sage_categories.sets.category import SetMap as SetMap
from sage_categories.sets.elements import Datum as Datum
from sage_categories.sets.maps import SetMorphismData as SetMorphismData
from sage_categories.sets.objects import SetObject as SetObject, SetObjectData as SetObjectData

type Key = tuple[str | int | Key, ...]
@dataclass(frozen=True, eq=False, slots=True)
class CardinalObjectData:
    key: Key
    terms: tuple[CardinalObject, ...]

@dataclass(frozen=True, eq=False, slots=True)
class CardinalMorphismData:
    set_map: SetMap

class CardinalObjectDeclaration(SetObjectDeclaration):
    def __init__(self, data: CardinalObjectData) -> None: ...
    def aleph_index(self) -> OrdinalObject: ...
    def initial_ordinal(self) -> OrdinalObject: ...
    def cardinality(self) -> CardinalObject: ...
    def is_finite(self) -> AppliedPredicate: ...
    def is_infinite(self) -> AppliedPredicate: ...
    def is_countable(self) -> AppliedPredicate: ...
    def is_uncountable(self) -> AppliedPredicate: ...
    def __add__(self, other: CardinalObject | int) -> CardinalObject: ...
    def __radd__(self, other: int) -> CardinalObject: ...
    def __mul__(self, other: CardinalObject | int) -> CardinalObject: ...
    def __rmul__(self, other: int) -> CardinalObject: ...
    def __pow__(self, exponent: CardinalObject | int) -> CardinalObject: ...
    def __rpow__(self, base: int) -> CardinalObject: ...
    def __le__(self, other: CardinalObject | int) -> AppliedPredicate: ...
    def __lt__(self, other: CardinalObject | int) -> AppliedPredicate: ...
    def __ge__(self, other: CardinalObject | int) -> AppliedPredicate: ...
    def __gt__(self, other: CardinalObject | int) -> AppliedPredicate: ...
    def __hash__(self) -> int: ...

class CardinalMorphismDeclaration(SetMapDeclaration):
    def __init__(self, data: CardinalMorphismData) -> None: ...

less_than: Predicate

class CardinalCategory(CategoryDeclaration[[MorphismOfCategory], []]):
    @property
    def ObjectType(self) -> type[CardinalObjectDeclaration]: ...
    @property
    def ElementType(self) -> type[CardinalCategory.DeclaredElementType]: ...
    @property
    def MorphismType(self) -> type[CardinalMorphismDeclaration]: ...
    DeclaredObjectType = CardinalObjectDeclaration
    DeclaredMorphismType = CardinalMorphismDeclaration
    class DeclaredElementType(SetElementDeclaration):
        ...
    def __init__(self) -> None: ...
    def Finite(self) -> Category: ...
    def Infinite(self) -> Category: ...
    def Countable(self) -> Category: ...
    def Uncountable(self) -> Category: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    def representative_functor(self) -> Functor: ...
    def representative(self, cardinal: CardinalObject) -> SetObject: ...
    def __call__(self, value: CardinalObject | int) -> CardinalObject: ...
    def aleph(self, index: OrdinalObject | int) -> CardinalObject: ...
    def zero(self) -> CardinalObject: ...
    def one(self) -> CardinalObject: ...
    def supremum(self, *cardinals: CardinalObject) -> CardinalObject: ...
    def sum(self, first: CardinalObject, second: CardinalObject) -> CardinalObject: ...
    def product(self, first: CardinalObject, second: CardinalObject) -> CardinalObject: ...
    def power(self, base: CardinalObject, exponent: CardinalObject) -> CardinalObject: ...
    def construct_morphism(self, domain: CardinalObject, codomain: CardinalObject, set_map: SetMap) -> CardinalityMorphism: ...
    def construct_identity(self, cardinal: CardinalObject) -> CardinalityMorphism: ...
    def composite(self, second: CardinalityMorphism, first: CardinalityMorphism) -> CardinalityMorphism: ...
    def inverse_morphism(self, morphism: CardinalityMorphism) -> CardinalityMorphism: ...
    def hom_inhabited(self, hom_category: Category) -> Decision: ...

CardinalObject = CardinalObjectDeclaration
CardinalElement = CardinalCategory.DeclaredElementType
CardinalityMorphism = CardinalMorphismDeclaration

def Cardinal() -> CardinalCategory: ...
def __getattr__(name: str) -> CardinalObject: ...

aleph0: CardinalObject
continuum: CardinalObject

def representative_bijection(member_object: SetObject) -> SetMap: ...
def cardinality_functor() -> Functor: ...

class Cardinal_Countable_ElementType(CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Countable_MorphismType(CardinalMorphismDeclaration):
    ...

class Cardinal_Countable_ObjectType(CardinalObjectDeclaration):
    ...

class Cardinal_Infinite_ElementType(CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Infinite_MorphismType(CardinalMorphismDeclaration):
    ...

class Cardinal_Infinite_ObjectType(CardinalObjectDeclaration):
    ...

class Cardinal_Finite_ElementType(Cardinal_Countable_ElementType, CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Finite_MorphismType(Cardinal_Countable_MorphismType, CardinalMorphismDeclaration):
    ...

class Cardinal_Finite_ObjectType(Cardinal_Countable_ObjectType, CardinalObjectDeclaration):
    ...

class Cardinal_Uncountable_ElementType(Cardinal_Infinite_ElementType, CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Uncountable_MorphismType(Cardinal_Infinite_MorphismType, CardinalMorphismDeclaration):
    ...

class Cardinal_Uncountable_ObjectType(Cardinal_Infinite_ObjectType, CardinalObjectDeclaration):
    ...
