from sage_categories.cat.category import CategoryDeclaration as CategoryDeclaration
from sage_categories.cat.functors import FunctorDeclaration as FunctorDeclaration
from sage_categories.ordinals.category import OrdinalObjectDeclaration as OrdinalObjectDeclaration
from sage_categories.sets.elements import SetElementDeclaration as SetElementDeclaration
from sage_categories.sets.maps import SetMapDeclaration as SetMapDeclaration
from sage_categories.sets.objects import SetObjectDeclaration as SetObjectDeclaration
from _typeshed import Incomplete
from dataclasses import dataclass
from sage.misc.cachefunc import cached_method
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.element_wrapper import ElementWrapper
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage_categories.cat.category import Category as Category
from sage_categories.cat.functors import Fun as Fun, Functor as Functor
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.kernel.construction import MorphismConstructionInput as MorphismConstructionInput, ObjectConstructionInput as ObjectConstructionInput, retained_morphism_input as retained_morphism_input, retained_object_input as retained_object_input
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, ask as ask, assume as assume, conjunction as conjunction, disjunction as disjunction, established as established, negation as negation
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ElementOfObject as ElementOfObject, MorphismOfCategory as MorphismOfCategory, ObjectOfCategory as ObjectOfCategory, role_of as role_of
from sage_categories.ordinals.category import OrdinalObject as OrdinalObject, Ordinals as Ordinals, bind_cardinals as bind_cardinals, is_natural_number as is_natural_number
from sage_categories.sets.category import SetMap as SetMap
from sage_categories.sets.elements import Datum as Datum
from sage_categories.sets.maps import SetMorphismData as SetMorphismData
from sage_categories.sets.objects import SetObject as SetObject, SetObjectData as SetObjectData
from typing import Any

type Key = tuple[str | int | Key, ...]
generalized_continuum_hypothesis: Predicate

class AlephElement(ElementWrapper): ...

class AlephSemiring(UniqueRepresentation, Parent):
    Element = AlephElement
    def __init__(self) -> None: ...
    @cached_method
    def zero(self) -> AlephElement: ...
    one = zero
    def le(self, first: AlephElement, second: AlephElement) -> Decision: ...
    def maximum(self, first: AlephElement, second: AlephElement) -> AlephElement: ...

@dataclass(frozen=True, eq=False, slots=True)
class Power:
    base: CardinalValue
    exponent: CardinalValue

@dataclass(frozen=True, eq=False, slots=True)
class Join:
    terms: tuple[CardinalValue, ...]

class CardinalValue(Element):
    def __init__(self, parent: CardinalSemiring, key: Key, value: Integer | AlephElement | Power | Join) -> None: ...
    def __pow__(self, exponent: CardinalValue | int) -> CardinalValue: ...
    def aleph_index(self) -> OrdinalObject: ...
    def finite_value(self) -> int: ...
    def __reduce__(self) -> tuple[Any, tuple[Key]]: ...
    def __hash__(self) -> int: ...

class CardinalSemiring(UniqueRepresentation, Parent):
    Element = CardinalValue
    def __init__(self) -> None: ...
    def retained(self, key: Key) -> CardinalValue: ...
    def finite(self, value: int) -> CardinalValue: ...
    def aleph(self, index: OrdinalObject | int) -> CardinalValue: ...
    @cached_method
    def zero(self) -> CardinalValue: ...
    @cached_method
    def one(self) -> CardinalValue: ...
    def some_elements(self) -> list[CardinalValue]: ...
    def is_finite(self, cardinal: CardinalValue) -> Decision: ...
    def is_countable(self, cardinal: CardinalValue) -> Decision: ...
    def le(self, first: CardinalValue, second: CardinalValue) -> Decision: ...
    def add(self, first: CardinalValue, second: CardinalValue) -> CardinalValue: ...
    def multiply(self, first: CardinalValue, second: CardinalValue) -> CardinalValue: ...
    def power(self, base: CardinalValue, exponent: CardinalValue) -> CardinalValue: ...
    def join(self, *cardinals: CardinalValue) -> CardinalValue: ...

@dataclass(frozen=True, eq=False, slots=True)
class CardinalObjectData:
    value: CardinalValue

@dataclass(frozen=True, eq=False, slots=True)
class CardinalMorphismData:
    set_map: SetMap

class CardinalObjectDeclaration(SetObjectDeclaration):
    def __init__(self, data: CardinalObjectData) -> None: ...
    def aleph_index(self) -> OrdinalObject: ...
    def initial_ordinal(self) -> OrdinalObject: ...
    def cardinality(self) -> CardinalObject: ...
    def is_finite(self) -> AppliedPredicate: ...
    def is_infinite(self) -> AppliedPredicate: ...
    def is_countable(self) -> AppliedPredicate: ...
    def is_uncountable(self) -> AppliedPredicate: ...
    def __add__(self, other: CardinalObject | int) -> CardinalObject: ...
    def __radd__(self, other: int) -> CardinalObject: ...
    def __mul__(self, other: CardinalObject | int) -> CardinalObject: ...
    def __rmul__(self, other: int) -> CardinalObject: ...
    def __pow__(self, exponent: CardinalObject | int) -> CardinalObject: ...
    def __rpow__(self, base: int) -> CardinalObject: ...
    def __le__(self, other: CardinalObject | int) -> AppliedPredicate: ...
    def __lt__(self, other: CardinalObject | int) -> AppliedPredicate: ...
    def __ge__(self, other: CardinalObject | int) -> AppliedPredicate: ...
    def __gt__(self, other: CardinalObject | int) -> AppliedPredicate: ...

class CardinalMorphismDeclaration(SetMapDeclaration):
    def __init__(self, data: CardinalMorphismData) -> None: ...

less_than: Predicate

class CardinalCategory(CategoryDeclaration[[MorphismOfCategory], []]):
    @property
    def ObjectType(self) -> type[CardinalObjectDeclaration]: ...
    @property
    def ElementType(self) -> type[CardinalCategory.DeclaredElementType]: ...
    @property
    def MorphismType(self) -> type[CardinalMorphismDeclaration]: ...
    DeclaredObjectType = CardinalObjectDeclaration
    DeclaredMorphismType = CardinalMorphismDeclaration
    class DeclaredElementType(SetElementDeclaration):
        ...
    def __init__(self) -> None: ...
    def Finite(self) -> Category: ...
    def Infinite(self) -> Category: ...
    def Countable(self) -> Category: ...
    def Uncountable(self) -> Category: ...
    def structure_functors(self) -> tuple[Functor, ...]: ...
    @cached_method
    def representative_functor(self) -> Functor: ...
    def representative(self, cardinal: CardinalObject) -> SetObject: ...
    def __call__(self, value: CardinalObject | int) -> CardinalObject: ...
    def aleph(self, index: OrdinalObject | int) -> CardinalObject: ...
    def zero(self) -> CardinalObject: ...
    def one(self) -> CardinalObject: ...
    def supremum(self, *cardinals: CardinalObject) -> CardinalObject: ...
    def sum(self, first: CardinalObject, second: CardinalObject) -> CardinalObject: ...
    def product(self, first: CardinalObject, second: CardinalObject) -> CardinalObject: ...
    def power(self, base: CardinalObject, exponent: CardinalObject) -> CardinalObject: ...
    def construct_morphism(self, domain: CardinalObject, codomain: CardinalObject, set_map: SetMap) -> CardinalityMorphism: ...
    def construct_identity(self, cardinal: CardinalObject) -> CardinalityMorphism: ...
    def composite(self, second: CardinalityMorphism, first: CardinalityMorphism) -> CardinalityMorphism: ...
    def inverse_morphism(self, morphism: CardinalityMorphism) -> CardinalityMorphism: ...
    def hom_inhabited(self, hom_category: Category) -> Decision: ...

CardinalObject = CardinalObjectDeclaration
CardinalElement = CardinalCategory.DeclaredElementType
CardinalityMorphism = CardinalMorphismDeclaration

def Cardinal() -> CardinalCategory: ...
def __getattr__(name: str) -> CardinalObject: ...

aleph0: CardinalObject
continuum: CardinalObject

def representative_bijection(member_object: SetObject) -> SetMap: ...
def cardinality_functor() -> Functor: ...

class Cardinal_Countable_ElementType(CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Countable_MorphismType(CardinalMorphismDeclaration):
    ...

class Cardinal_Countable_ObjectType(CardinalObjectDeclaration):
    ...

class Cardinal_Infinite_ElementType(CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Infinite_MorphismType(CardinalMorphismDeclaration):
    ...

class Cardinal_Infinite_ObjectType(CardinalObjectDeclaration):
    ...

class Cardinal_Finite_ElementType(Cardinal_Countable_ElementType, CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Finite_MorphismType(Cardinal_Countable_MorphismType, CardinalMorphismDeclaration):
    ...

class Cardinal_Finite_ObjectType(Cardinal_Countable_ObjectType, CardinalObjectDeclaration):
    ...

class Cardinal_Uncountable_ElementType(Cardinal_Infinite_ElementType, CardinalCategory.DeclaredElementType):
    ...

class Cardinal_Uncountable_MorphismType(Cardinal_Infinite_MorphismType, CardinalMorphismDeclaration):
    ...

class Cardinal_Uncountable_ObjectType(Cardinal_Infinite_ObjectType, CardinalObjectDeclaration):
    ...
