from sage_categories.sets.category import Sets_FiniteSubsets_ElementType as Sets_FiniteSubsets_ElementType
from sage_categories.sets.category import Sets_FiniteSubsets_MorphismType as Sets_FiniteSubsets_MorphismType
from sage_categories.sets.category import Sets_FinitelySupportedFunctions_ElementType as Sets_FinitelySupportedFunctions_ElementType
from sage_categories.sets.category import Sets_FinitelySupportedFunctions_MorphismType as Sets_FinitelySupportedFunctions_MorphismType
from sage_categories.cat.category import Category as Category
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass, decision_and as decision_and
from sage_categories.kernel.predicates import ask as ask
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.roles import ObjectOfCategory as ObjectOfCategory, Role as Role
from sage_categories.sets.cardinals import Cardinal as Cardinal, CardinalObject as CardinalObject
from sage_categories.sets.elements import Datum as Datum, SetPoint as SetPoint
from sage_categories.sets.exponentials import Function as Function
from sage_categories.sets.maps import Rule as Rule
from sage_categories.sets.objects import SetObject as SetObject

class FiniteSubsetsRole(SetObject):
    def base_set(self) -> SetObject: ...
    def subset_at(self, point: SetPoint) -> SetObject: ...
    def point_of(self, subset: SetObject) -> SetPoint: ...
    def index(self, subset: SetObject) -> CardinalObject: ...
    def __getitem__(self, position: CardinalObject | int) -> SetObject: ...

class SizedSubsetsRole(ObjectOfCategory):
    def subset_cardinality(self) -> CardinalObject: ...

class SizedSubsetsCategory(PropertySubcategory[[Rule], []]):
    def __init__(self, ambient: Category[[Rule], []], size: int) -> None: ...
    def size(self) -> CardinalObject: ...
    def __call__(self, base_set: SetObject) -> SetObject: ...

class FiniteSubsetsCategory(PropertySubcategory[[Rule], []]):
    @property
    def ObjectType(self) -> type[FiniteSubsetsRole]: ...
    @property
    def ElementType(self) -> type[Sets_FiniteSubsets_ElementType]: ...
    @property
    def MorphismType(self) -> type[Sets_FiniteSubsets_MorphismType]: ...
    def __init__(self, ambient: Category[[Rule], []]) -> None: ...
    def __call__(self, base_set: SetObject) -> SetObject: ...
    def of_size(self, size: int, base_set: SetObject) -> SetObject: ...
    def retained_base_set(self, subsets: SetObject) -> SetObject: ...
    def retained_size(self, subsets: SetObject) -> CardinalObject: ...
    def subset_at(self, subsets: SetObject, point: SetPoint) -> SetObject: ...
    def point_of(self, subsets: SetObject, subset: SetObject) -> SetPoint: ...
    def index(self, subsets: SetObject, subset: SetObject) -> CardinalObject: ...
    def subset_at_position(self, subsets: SetObject, position: CardinalObject | int) -> SetObject: ...

class FinitelySupportedFunctionsRole(SetObject):
    def index_set(self) -> SetObject: ...
    def value_set(self) -> SetObject: ...
    def basepoint(self) -> SetPoint: ...

class FinitelySupportedFunctionsCategory(PropertySubcategory[[Rule], []]):
    @property
    def ObjectType(self) -> type[FinitelySupportedFunctionsRole]: ...
    @property
    def ElementType(self) -> type[Sets_FinitelySupportedFunctions_ElementType]: ...
    @property
    def MorphismType(self) -> type[Sets_FinitelySupportedFunctions_MorphismType]: ...
    def __init__(self, ambient: Category[[Rule], []]) -> None: ...
    def __call__(self, index_set: SetObject, basepoint: SetPoint) -> SetObject: ...
    def retained_index_set(self, functions: SetObject) -> SetObject: ...
    def retained_basepoint(self, functions: SetObject) -> SetPoint: ...
