"""``Sets()`` limits and colimits over every shape: compatible families and quotients (POL-SET-014; ``specs/sets.md``, "General limits and colimits" and "Equality").

The limit of ``D: I -> Sets()`` is the subset of the product
``prod_{i in Ob(I)} D(i)`` cut out by compatibility: a family ``(x_i)`` is a member
when ``ask(D(u)(x_i) == x_j) is True`` for every generating morphism ``u: i -> j``
of ``I`` (Mathlib ``CategoryTheory.Limits.Types.limitCone``, whose apex is the
type of sections, the families with ``F.map f (s j) = s j'``; inspected
2026-08-27).  Membership decides when ``I`` declares a finite generating family
and every generating equality decides, and is ``Unknown`` otherwise.  The limit
is the chosen subset ``product.subset_from(compatible)``: ``Sets().ChosenSubsets()``
owns it and its inclusion, and the same object is refined into ``Sets().Limits(I)``
with its universal data; the projections are the product projections after the
inclusion; the mediating map of a cone is its map into the product.

The colimit of ``D`` is the quotient of the coproduct ``coprod_i D(i)`` by the
equivalence relation generated by ``(i, x) ~ (j, D(u)(x))`` (Mathlib
``CategoryTheory.Functor.ColimitTypeRel`` and ``ColimitType = Quot
F.ColimitTypeRel``; the generated equivalence is ``Relation.EqvGen``, the least
equivalence relation containing the relation, ``EqvGen.eqvGen_le``; inspected
2026-08-27).  It is the chosen quotient of the coproduct: ``Sets().ChosenQuotients()``
owns it and its quotient map, and the same object is refined into
``Sets().Colimits(I)``; its injections are the coproduct injections followed by
the quotient map, and its element equality is
an owned predicate whose exact routes are: two representatives with one index and
equal values; for ``I = omega``, agreement at the larger of the two stages under
the transition maps, else ``Unknown``; for a finitely generated shape whose
coproduct is finite and enumerated, the connected components of the generating
relation (a union-find over the finite coproduct, Sage ``DisjointSet``), which
decide ``True`` and ``False`` exactly; every other case is ``Unknown``.

Cardinality is exact when the finite enumerated case decides it, in which case
the apex is constructed through ``Sets().Finite()`` with its enumeration, and
``Unknown`` otherwise (``specs/sets.md``, "Exact cardinality or Unknown").  The
objects of a shape are read through its ``object_set()``, ``object_at()``,
``object_point()`` and ``generating_morphisms()``; no rule-defined shape is
enumerated.
"""

from __future__ import annotations

from typing import Any

from sage.sets.disjoint_set import DisjointSet
from sage.structure.coerce_dict import MonoDict

import sage_categories.sets.category as _sets
from sage_categories.cat.constructions import cocone, cocone_apex, cone, cone_apex
from sage_categories.cat.functors import Fun, Functor, NaturalTransformation
from sage_categories.cat.shapes import Discrete, omega
from sage_categories.kernel.decisions import Decision, Unknown, UnknownClass, decision_and
from sage_categories.kernel.predicates import ask
from sage_categories.kernel.roles import ObjectOfCategory
from sage_categories.sets.elements import Datum
from sage_categories.sets.maps import SetMap
from sage_categories.sets.objects import SetObject

__all__ = ["Representative", "colimit_of_sets", "limit_of_sets"]


# -- limits --------------------------------------------------------------------------------------


def limit_of_sets(diagram: Functor) -> SetObject:
    """``Sets().Limits(I)(diagram)``: the compatible families in the product over the objects of ``I``."""
    sets = _sets.Sets()
    shape = diagram.domain()
    objects = shape.object_set()
    index_shape = Discrete(objects)
    product = sets.Products()(Fun(index_shape, sets).from_object_rule(lambda vertex: diagram.on_object(shape.object_at(vertex.point()))))
    generators = shape.generating_morphisms()

    def vertex(member_object: ObjectOfCategory) -> ObjectOfCategory:
        return index_shape(shape.object_point(member_object))

    def compatible(datum: Datum) -> Decision:
        if generators is Unknown:
            return Unknown
        family = product.point(datum)
        return decision_and(
            *(
                ask(diagram.on_morphism(generator)(product.product_projection(vertex(generator.domain()))(family)) == product.product_projection(vertex(generator.codomain()))(family))
                for generator in generators
            )
        )

    apex = product.subset_from(compatible)
    inclusion = apex.inclusion()
    projections: MonoDict = MonoDict()

    def projection(member_object: ObjectOfCategory) -> SetMap:
        if member_object not in projections:
            projections[member_object] = product.product_projection(vertex(member_object)) * inclusion
        return projections[member_object]

    def mediator(candidate_cone: NaturalTransformation) -> SetMap:
        """The map into the product; a candidate whose components decidedly fail a cone equation is rejected."""
        source = cone_apex(candidate_cone)
        if generators is not Unknown:
            for generator in generators:
                assert ask(diagram.on_morphism(generator) * candidate_cone.component(generator.domain()) == candidate_cone.component(generator.codomain())) is not False, (
                    f"{candidate_cone!r} is not a cone: its components do not commute with {generator!r}"
                )
        into_product = product.universal_morphism(cone(product.diagram(), source, lambda index_vertex: candidate_cone.component(shape.object_at(index_vertex.point()))))
        return sets.construct_morphism(source, apex, into_product._set_morphism_data.rule)

    family = sets.Limits(shape)
    lowered = family.lowered(diagram)
    return family.with_universal_data(lowered, apex, cone(lowered, apex, projection), mediator)


# -- colimits -------------------------------------------------------------------------------------


class Representative:
    """The private datum of a point of a colimit: a tagged point ``(i, x)`` of the coproduct, up to the generated equivalence.

    This is private computation data, not an owned value (``specs/sets.md``,
    "Equality", governs owned values).  Two representatives of one colimit compare
    through the quotient's exact routes; when the finite partition decides, the
    hash is the hash of the class root so equal representatives hash equal, and
    otherwise the hash is by identity.
    """

    def __init__(self, quotient: Quotient, tagged: tuple[Datum, Datum]) -> None:
        self._quotient = quotient
        self._tagged = tagged

    def quotient(self) -> Quotient:
        return self._quotient

    def tagged(self) -> tuple[Datum, Datum]:
        return self._tagged

    def __eq__(self, other: Any) -> Decision:
        if other is self:
            return True
        match other:
            case Representative():
                if other.quotient() is not self._quotient:
                    return False
                return self._quotient.equivalent(self, other)
            case _:
                return False

    def __hash__(self) -> int:
        return self._quotient.hash_of(self)

    def __repr__(self) -> str:
        return f"[{self._tagged!r}]"


class Quotient:
    """The private computation data of a colimit: the diagram, its coproduct, and the exact equivalence routes."""

    def __init__(self, diagram: Functor, coproduct: SetObject) -> None:
        self._diagram = diagram
        self._shape = diagram.domain()
        self._objects = self._shape.object_set()
        self._coproduct = coproduct
        self._partition: MonoDict = MonoDict()

    def index_datum(self, member_object: ObjectOfCategory) -> Datum:
        return self._shape.object_point(member_object)._classical_datum_()

    def object_at(self, index_datum: Datum) -> ObjectOfCategory:
        return self._shape.object_at(self._objects.point(index_datum))

    def transition(self, source: Datum, target: Datum) -> SetMap:
        """``D(u)`` for the comparison ``u: source -> target`` of a thin shape."""
        comparison = self._shape.morphism_category(1)(self.object_at(source), self.object_at(target))()
        return self._diagram.on_morphism(comparison)

    def partition(self) -> DisjointSet | UnknownClass:
        """The connected components of the generating relation on the finite enumerated coproduct, computed once."""
        finite = _sets.Sets().Finite()
        generators = self._shape.generating_morphisms()
        if generators is Unknown or not finite.has_chosen_enumeration(self._coproduct):
            return Unknown
        if self._coproduct not in self._partition:
            components = DisjointSet(list(finite.chosen_enumeration(self._coproduct)))
            for generator in generators:
                source, target = self.index_datum(generator.domain()), self.index_datum(generator.codomain())
                transition = self._diagram.on_morphism(generator)
                for value in finite.chosen_enumeration(transition.domain()):
                    components.union((source, value), (target, transition._set_morphism_data.rule(value)))
            self._partition[self._coproduct] = components
        return self._partition[self._coproduct]

    def equivalent(self, first: Representative, second: Representative) -> Decision:
        left, right = first.tagged(), second.tagged()
        if left[0] == right[0] and (left[1] == right[1]) is True:
            return True
        partition = self.partition()
        if partition is not Unknown:
            return partition.find(left) == partition.find(right)
        if self._shape is omega():
            lower, upper = (left, right) if left[0] <= right[0] else (right, left)
            transported = self.transition(lower[0], upper[0])._set_morphism_data.rule(lower[1])
            if (transported == upper[1]) is True:
                return True
        return Unknown

    def hash_of(self, representative: Representative) -> int:
        partition = self.partition()
        if partition is Unknown:
            return object.__hash__(representative)
        return hash(partition.find(representative.tagged()))

    def classes(self) -> tuple[Representative, ...]:
        """One representative per class of the finite partition."""
        partition = self.partition()
        assert partition is not Unknown
        return tuple(Representative(self, root) for root in partition.root_to_elements_dict())


def colimit_of_sets(diagram: Functor) -> SetObject:
    """``Sets().Colimits(I)(diagram)``: the quotient of the coproduct over the objects of ``I`` by the generated equivalence."""
    sets = _sets.Sets()
    shape = diagram.domain()
    objects = shape.object_set()
    index_shape = Discrete(objects)
    coproduct = sets.Coproducts()(Fun(index_shape, sets).from_object_rule(lambda vertex: diagram.on_object(shape.object_at(vertex.point()))))
    quotient = Quotient(diagram, coproduct)
    coproduct_rule = coproduct._set_object_data.membership_rule

    def membership_rule(datum: Datum) -> Decision:
        match datum:
            case Representative() if datum.quotient() is quotient:
                return coproduct_rule(datum.tagged())
            case _:
                return False

    apex = sets.ChosenQuotients()(coproduct, lambda tagged: Representative(quotient, tagged), membership_rule)
    quotient_map = apex.quotient_map()

    def vertex(member_object: ObjectOfCategory) -> ObjectOfCategory:
        return index_shape(shape.object_point(member_object))

    injections: MonoDict = MonoDict()

    def injection(member_object: ObjectOfCategory) -> SetMap:
        if member_object not in injections:
            injections[member_object] = quotient_map * coproduct.coproduct_injection(vertex(member_object))
        return injections[member_object]

    def mediator(candidate_cocone: NaturalTransformation) -> SetMap:
        """The map out of the quotient; a candidate whose components decidedly fail a cocone equation is rejected."""
        target = cocone_apex(candidate_cocone)
        generators = shape.generating_morphisms()
        if generators is not Unknown:
            for generator in generators:
                assert ask(candidate_cocone.component(generator.codomain()) * diagram.on_morphism(generator) == candidate_cocone.component(generator.domain())) is not False, (
                    f"{candidate_cocone!r} is not a cocone: its components do not commute with {generator!r}"
                )
        return sets.construct_morphism(
            apex,
            target,
            lambda representative: candidate_cocone.component(
                quotient.object_at(representative.tagged()[0])
            )._set_morphism_data.rule(representative.tagged()[1]),
        )

    family = sets.Colimits(shape)
    lowered = family.lowered(diagram)
    return family.with_universal_data(lowered, apex, cocone(lowered, apex, injection), mediator)
