from collections.abc import Callable
from sage_categories.cat.category import Category as Category
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, decision_and as decision_and, decision_not as decision_not, decision_or as decision_or
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, MorphismOfCategory as MorphismOfCategory
from sage_categories.sets.elements import Datum as Datum, SetPoint as SetPoint
from sage_categories.sets.objects import SetObject as SetObject
from typing import Any

type Rule = Callable[[Datum], Datum]
class SetMap(MorphismOfCategory):
    def __init__(self, category: Category, domain: SetObject, codomain: SetObject, rule: Rule) -> None: ...
    def __call__(self, element: SetPoint) -> SetPoint: ...
    def image(self) -> SetObject: ...

def maps_equal(first: CategoryPoint, candidate: Any) -> Decision: ...
def injective_on_finite_domain(morphism: MorphismOfCategory) -> Decision: ...
def surjective_on_finite_domain(morphism: MorphismOfCategory) -> Decision: ...
def bijective_on_finite_domain(morphism: MorphismOfCategory) -> Decision: ...
