from sage_categories.sets.category import Sets_Countable_ObjectType as Sets_Countable_ObjectType
from _typeshed import Incomplete
from collections.abc import Callable, Iterator
from sage_categories.cat.category import Category as Category
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, ask as ask
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ObjectOfCategory as ObjectOfCategory, Role as Role, role_of as role_of
from sage_categories.sets.cardinals import Cardinal as Cardinal, CardinalObject as CardinalObject
from sage_categories.sets.elements import Datum as Datum, SetPoint as SetPoint
from typing import Any

logger: Incomplete
type MembershipRule = Callable[[Datum], Decision]
element_of: Incomplete

class SetObject(ObjectOfCategory):
    def __init__(self, category: Category, membership_rule: MembershipRule, cardinality: CardinalObject | UnknownClass) -> None: ...
    def membership_proposition(self, candidate: CategoryPoint) -> AppliedPredicate: ...
    def __contains__(self, candidate: Any) -> bool: ...
    def point(self, datum: Datum) -> SetPoint: ...
    def rule_point(self, datum: Datum) -> SetPoint: ...
    def cardinality(self) -> CardinalObject | UnknownClass: ...
    def subset_from(self, predicate: MembershipRule) -> SetObject: ...
    def is_finite(self) -> AppliedPredicate: ...
    def is_infinite(self) -> AppliedPredicate: ...
    def is_countable(self) -> AppliedPredicate: ...
    def is_uncountable(self) -> AppliedPredicate: ...

class FiniteSetRole(Sets_Countable_ObjectType, SetObject):
    def __init__(self, category: Category, members: tuple[Datum, ...]) -> None: ...
    def __iter__(self) -> Iterator[SetPoint]: ...
