from sage_categories.sets.category import Sets_PowerObjects_ElementType as Sets_PowerObjects_ElementType
from sage_categories.sets.category import Sets_PowerObjects_MorphismType as Sets_PowerObjects_MorphismType
from sage_categories.cat.category import Category as Category
from sage_categories.cat.properties import PropertySubcategory as PropertySubcategory
from sage_categories.kernel.decisions import Decision as Decision
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.roles import ObjectOfCategory as ObjectOfCategory, Role as Role
from sage_categories.sets.elements import Datum as Datum, SetPoint as SetPoint
from sage_categories.sets.exponentials import Function as Function, function_set as function_set
from sage_categories.sets.maps import Rule as Rule, SetMap as SetMap
from sage_categories.sets.objects import MembershipRule as MembershipRule, SetObject as SetObject

class PowerObjectRole(SetObject):
    def base_set(self) -> SetObject: ...
    def from_predicate(self, predicate: MembershipRule) -> SetObject: ...
    def from_characteristic_morphism(self, characteristic: SetMap) -> SetObject: ...
    def subset_named_by(self, point: SetPoint) -> SetObject: ...
    def top(self) -> SetObject: ...
    def bottom(self) -> SetObject: ...
    def inverse_image_morphism(self, set_map: SetMap) -> SetMap: ...
    def direct_image_morphism(self, set_map: SetMap) -> SetMap: ...

class PowerObjectsCategory(PropertySubcategory[[Rule], []]):
    @property
    def ObjectType(self) -> type[PowerObjectRole]: ...
    @property
    def ElementType(self) -> type[Sets_PowerObjects_ElementType]: ...
    @property
    def MorphismType(self) -> type[Sets_PowerObjects_MorphismType]: ...
    def __init__(self, ambient: Category[[Rule], []]) -> None: ...
    def __call__(self, base_set: SetObject) -> SetObject: ...
    def retained_base_set(self, power: SetObject) -> SetObject: ...
    def subset_of_characteristic_morphism(self, power: SetObject, characteristic: SetMap) -> SetObject: ...
    def extreme_subset(self, power: SetObject, whole: bool) -> SetObject: ...
    def inverse_image_morphism(self, power: SetObject, set_map: SetMap) -> SetMap: ...
    def direct_image_morphism(self, power: SetObject, set_map: SetMap) -> SetMap: ...
