from sage_categories.cat.category import CategoryDeclaration as CategoryDeclaration
from sage_categories.sets.cardinals import CardinalObjectDeclaration as CardinalObjectDeclaration
from sage_categories.sets.category import Sets_ChosenQuotients_ElementType as Sets_ChosenQuotients_ElementType
from sage_categories.sets.category import Sets_ChosenQuotients_MorphismType as Sets_ChosenQuotients_MorphismType
from sage_categories.sets.category import Sets_ChosenSubsets_ElementType as Sets_ChosenSubsets_ElementType
from sage_categories.sets.category import Sets_ChosenSubsets_MorphismType as Sets_ChosenSubsets_MorphismType
from sage_categories.sets.objects import SetObjectDeclaration as SetObjectDeclaration
from collections.abc import Callable
from sage_categories.cat.category import Category as Category
from sage_categories.cat.properties import FullSubcategory as FullSubcategory
from sage_categories.kernel.caches import retained_method as retained_method
from sage_categories.kernel.decisions import Decision as Decision, Unknown as Unknown, UnknownClass as UnknownClass
from sage_categories.kernel.predicates import AppliedPredicate as AppliedPredicate, Predicate as Predicate, ask as ask, conjunction as conjunction, disjunction as disjunction, established as established, negation as negation
from sage_categories.kernel.refinement import refine as refine
from sage_categories.kernel.roles import CategoryPoint as CategoryPoint, ObjectOfCategory as ObjectOfCategory, Role as Role
from sage_categories.sets.cardinals import CardinalObject as CardinalObject
from sage_categories.sets.category import SetMap as SetMap
from sage_categories.sets.elements import Datum as Datum
from sage_categories.sets.maps import Rule as Rule
from sage_categories.sets.objects import MembershipRule as MembershipRule, SetObject as SetObject

subset_of: Predicate

class ChosenSubsetRole(SetObjectDeclaration):
    def monomorphism(self) -> SetMap: ...
    def underlying_set(self) -> SetObject: ...
    def characteristic_morphism(self) -> SetMap: ...
    def __le__(self, other: SetObject) -> AppliedPredicate: ...
    def union(self, other: SetObject) -> SetObject: ...
    def intersection(self, other: SetObject) -> SetObject: ...
    def difference(self, other: SetObject) -> SetObject: ...
    def symmetric_difference(self, other: SetObject) -> SetObject: ...
    def complement(self) -> SetObject: ...
    def __or__(self, other: SetObject) -> SetObject: ...
    def __and__(self, other: SetObject) -> SetObject: ...

class ChosenSubsetsCategory(FullSubcategory[[Rule], []]):
    @property
    def ObjectType(self) -> type[ChosenSubsetRole]: ...
    @property
    def ElementType(self) -> type[Sets_ChosenSubsets_ElementType]: ...
    @property
    def MorphismType(self) -> type[Sets_ChosenSubsets_MorphismType]: ...
    def __init__(self, ambient: Category[[Rule], []]) -> None: ...
    def name(self) -> str: ...
    def local_role_class(self, role: Role) -> type[CategoryPoint]: ...
    def with_cardinality(self, base_set: SetObject, predicate: MembershipRule, cardinality: CardinalObject) -> SetObject: ...
    def from_enumeration(self, base_set: SetObject, members: tuple[Datum, ...]) -> SetObject: ...
    @retained_method
    def characteristic_morphism_of(self, subset: SetObject) -> SetMap: ...
    def __call__(self, base_set: SetObject, predicate: MembershipRule) -> SetObject: ...
    @retained_method
    def image_of(self, set_map: SetMap) -> SetObject: ...

class ChosenQuotientRole(SetObjectDeclaration):
    def quotient_map(self) -> SetMap: ...
    def underlying_set(self) -> SetObject: ...

class ChosenQuotientsCategory(FullSubcategory[[Rule], []]):
    @property
    def ObjectType(self) -> type[ChosenQuotientRole]: ...
    @property
    def ElementType(self) -> type[Sets_ChosenQuotients_ElementType]: ...
    @property
    def MorphismType(self) -> type[Sets_ChosenQuotients_MorphismType]: ...
    def __init__(self, ambient: Category[[Rule], []]) -> None: ...
    def name(self) -> str: ...
    def local_role_class(self, role: Role) -> type[CategoryPoint]: ...
    def __call__(self, base_set: SetObject, class_of: Callable[[Datum], Datum], membership_rule: MembershipRule) -> SetObject: ...
