from dataclasses import dataclass

from sage_categories.cat.category import Category as Category
from sage_categories.cat.category import CategoryOfCategories as CategoryOfCategories
from sage_categories.cat.functors import Functor as Functor
from sage_categories.cat.morphisms import MorphismCategory as MorphismCategory
from sage_categories.cat.native import (
    NativeMorphismRealization as NativeMorphismRealization,
)
from sage_categories.cat.native import (
    NativeMorphismRealizations as NativeMorphismRealizations,
)
from sage_categories.cat.native import (
    NativeObjectRealization as NativeObjectRealization,
)
from sage_categories.cat.native import (
    NativeObjectRealizations as NativeObjectRealizations,
)
from sage_categories.cat.predicates import assume as assume
from sage_categories.engines.julia_bridge import OscarHandle as OscarHandle

__all__ = [
    "OscarRingConstruction",
    "oscar_element_handle",
    "oscar_morphism_handle",
    "oscar_native_morphism",
    "oscar_native_object",
    "oscar_object_handle",
    "reconstruct_oscar_element",
    "reconstruct_oscar_morphism",
    "reconstruct_oscar_object",
    "retain_oscar_native_morphism",
    "retain_oscar_native_object",
]

@dataclass(frozen=True, eq=False, slots=True)
class OscarRingConstruction:
    data: object

def retain_oscar_native_object(value: CategoryOfCategories.ElementType, native: object, construction: object) -> NativeObjectRealization[object, OscarRingConstruction]: ...
def oscar_native_object(value: CategoryOfCategories.ElementType) -> NativeObjectRealization[object, OscarRingConstruction]: ...
def retain_oscar_native_morphism(value: MorphismCategory.ObjectType, native: object) -> NativeMorphismRealization[object]: ...
def oscar_native_morphism(value: MorphismCategory.ObjectType) -> NativeMorphismRealization[object]: ...
def oscar_object_handle(value: CategoryOfCategories.ElementType) -> OscarHandle: ...
def oscar_element_handle(value: CategoryOfCategories.ElementType) -> OscarHandle: ...
def oscar_morphism_handle(value: MorphismCategory.ObjectType) -> OscarHandle: ...
def reconstruct_oscar_element(ring: CategoryOfCategories.ElementType, native: OscarHandle) -> CategoryOfCategories.ElementType: ...
def reconstruct_oscar_object(native: OscarHandle, construction: object) -> CategoryOfCategories.ElementType: ...
def reconstruct_oscar_morphism(source: CategoryOfCategories.ElementType, target: CategoryOfCategories.ElementType, native: OscarHandle) -> MorphismCategory.ObjectType: ...
def construction(value: CategoryOfCategories.ElementType) -> object: ...
def integer_ring(construction_data: object) -> CategoryOfCategories.ElementType: ...
def prime_field(characteristic: int, construction_data: object) -> CategoryOfCategories.ElementType: ...
def polynomial_ring(
    base: CategoryOfCategories.ElementType, names: tuple[str, ...], construction_data: object
) -> tuple[CategoryOfCategories.ElementType, tuple[CategoryOfCategories.ElementType, ...]]: ...
def quotient_ring(
    source: CategoryOfCategories.ElementType, relations: tuple[CategoryOfCategories.ElementType, ...], construction_data: object
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]: ...
def polynomial_coefficient_map(base: CategoryOfCategories.ElementType, polynomial: CategoryOfCategories.ElementType) -> MorphismCategory.ObjectType: ...
def principal_localization(
    source: CategoryOfCategories.ElementType, element: CategoryOfCategories.ElementType, construction_data: object
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]: ...
def retain_prime_ideal(value: object, ring: CategoryOfCategories.ElementType, generators: tuple[CategoryOfCategories.ElementType, ...]) -> None: ...
def prime_ideal_generators(value: object) -> tuple[CategoryOfCategories.ElementType, ...]: ...
def prime_ideal_contains(value: object, element: CategoryOfCategories.ElementType) -> bool: ...
def retain_prime_ideal_preimage(value: object, mapping: MorphismCategory.ObjectType, target_prime: object) -> None: ...
def retain_prime_ideal_extension(value: object, mapping: MorphismCategory.ObjectType, source_prime: object) -> None: ...
def localization_at_prime(
    ring: CategoryOfCategories.ElementType, prime: object, construction_data: object
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]: ...
def stalk_map(
    mapping: MorphismCategory.ObjectType,
    source_localized: CategoryOfCategories.ElementType,
    target_localized: CategoryOfCategories.ElementType,
    target_localization: MorphismCategory.ObjectType,
) -> MorphismCategory.ObjectType: ...
def presented_ring_homomorphism(
    source: CategoryOfCategories.ElementType, target: CategoryOfCategories.ElementType, generator_images: tuple[CategoryOfCategories.ElementType, ...]
) -> MorphismCategory.ObjectType: ...
def localization_extension(
    localized: CategoryOfCategories.ElementType, target: CategoryOfCategories.ElementType, base_map: MorphismCategory.ObjectType
) -> MorphismCategory.ObjectType: ...
def inverse_unit(element: CategoryOfCategories.ElementType) -> CategoryOfCategories.ElementType: ...
def principal_localization_from_native(
    source: CategoryOfCategories.ElementType, element: CategoryOfCategories.ElementType, native_localized: object, native_map: object, construction_data: object | None = None
) -> tuple[CategoryOfCategories.ElementType, MorphismCategory.ObjectType]: ...
